### ISSUE TITLE
stopAnimation方法无效

### ISSUE THREAD

**Issue by lipangniu** [svga/SVGAPlayer-Android#102]
在使用时,播放完动画后调用stopAnimation没有任何作用,那连续播放内存怎样去释放呢

**Comment by PonyCui** [comment]
Use stopAnimation to stop animation, not use to release memory.

**Comment by PonyCui** [comment]
内存就由 GC 进行回收。

**Comment by lipangniu** [comment]
但IOS那边这个方法是可以用的,机制不一样吗?

**Comment by PonyCui** [comment]
安卓的内存回收机制了解一下

**Comment by lipangniu** [comment]
内存回收我会仔细去了解下,前面你说stopAnimation是停止动画,那我调用这个方法后再去startAnimation,为什么就开启不了

**Comment by PonyCui** [comment]
Please provide a demo.
