### ISSUE TITLE
android.graphics.Path.finalize() timed out after 30 seconds

### ISSUE THREAD

**Issue by GoingAI** [svga/SVGAPlayer-Android#103]
![image](https://user-images.githubusercontent.com/9779970/50417292-843d4000-0860-11e9-884c-563547d06b23.png)

**Comment by PonyCui** [comment]
Could you provide a demo?

**Comment by GoingAI** [comment]
这是线上统计到崩溃日志，能够提供的信息有：
1.我们在 ListView、RecyclerView等列表中使用
2.崩溃的设备信息
![image](https://user-images.githubusercontent.com/9779970/50417809-48f04080-0863-11e9-8104-9ce8042236c2.png)

**Comment by PonyCui** [comment]
Maybe is an Android System BUG https://www.jianshu.com/p/0119c682d2b8
