### ISSUE TITLE
SVGA动画消失

### ISSUE THREAD

**Issue by wwangbin** [svga/SVGAPlayer-Android#104]
问题描述：当svga动画离开屏幕再回到屏幕时，svga动画控件消失。
问题复现：在viewpager中，第一个页面有svga动画正在播放，但是当切到第三个页面再回来，动画就消失不见了；或者在一个recycleview场景中滑出屏幕再回来也会出现svga动画消失的问题。

**Comment by lgengsy** [comment]
我也遇见了

**Comment by lgengsy** [comment]
最后怎么解决的 ？？

**Comment by lgengsy** [comment]
这个跟动画没有关系，是Viewpager回收机制导致的。

**Comment by lujun525** [comment]
最后咋解决的啊
