### ISSUE TITLE
svga文件声音问题

### ISSUE THREAD

**Issue by lipangniu** [svga/SVGAPlayer-Android#106]
在svga文件中加入声音后,内存就无法释放,不加声音可以释放,请问是文件问题还是释放需要其它处理

**Comment by PonyCui** [comment]
可能是 Player 里面的 SoundPool 需要释放，我这里看一下。

**Comment by lipangniu** [comment]
有结果了吗?我自己在soundPool的stop方法后面跟release方法还是不行

**Comment by PonyCui** [comment]
可以提供一个有问题的 svga 文件吗？就在这里上传。

**Comment by lipangniu** [comment]
今天又测试了下,发现系统8.0的可以回收但很慢,8.0以下就不行了
[500b.zip](https://github.com/yyued/SVGAPlayer-Android/files/2745060/500b.zip)

**Comment by PonyCui** [comment]
好的，我尝试一下。

**Comment by PonyCui** [comment]
Fixed on tag 2.4.0
你尝试一下
