### ISSUE TITLE
text和stroke为啥不支持alpha变化呢？

### ISSUE THREAD

**Issue by 1290846731** [svga/SVGAPlayer-Android#107]
如题：为啥text和stroke不支持alpha呢？  是漏了吗？   ios是支持的

**Comment by PonyCui** [comment]
支持的

**Comment by 1290846731** [comment]
> 支持的

那开源的没加？   插入的text和shape的stroke，代码里面真的没有，看上去是漏的，shape的其他几个都加了

**Comment by PonyCui** [comment]
呃……好像是有这个问题，我再确认一下。

**Comment by 1290846731** [comment]
> > 支持的
> 
> 那开源的没加？ 插入的text和shape的stroke，代码里面真的没有，看上去是漏的，shape的其他几个都加了



> > 支持的
> 
> 那开源的没加？ 插入的text和shape的stroke，代码里面真的没有，看上去是漏的，shape的其他几个都加了



> 呃……好像是有这个问题，我再确认一下。

麻烦
