### ISSUE TITLE
特效资源好像没有释放，从而导致oom，怎么办？

### ISSUE THREAD

**Issue by sjl164** [svga/SVGAPlayer-Android#109]
看日志是 SVGAVideoEntity中的resetImages方法。
不停加载新的特效，并且在方法中不断创建bitmap，但是没有释放之前的，引起oom 怎么办！！

**Comment by sjl164** [comment]
设计师给的文件在10M左右，我看了大佬你之前的issues，给出的建议是优化svga文件。
想请问一下，有没有办法释放之前的资源占用内存呢？

**Comment by PonyCui** [comment]
正常的文件理应在 500K 以下，在 http://svga.io 中可以查看内存占用情况。

**Comment by PonyCui** [comment]
你应该始终要求设计师保证这样的输出要求

**Comment by sjl164** [comment]
好的，感谢。
那要怎样让资源最优化呢？有什么建议吗

**Comment by PonyCui** [comment]
不要使用序列帧，减少 PNG 宽高。
