### ISSUE TITLE
2.4.2 version SVGAImageView removed，soundpool did not release

### ISSUE THREAD

**Issue by 456838** [svga/SVGAPlayer-Android#111]
## Attention

* Do not ask any usage question, issue board is a issue board, accept library bugs only.
* If you are facing any usage problem, read the README again.

## Issue Template

2.4.2 version SVGAImageView removed，soundpool did not release .
resolution :  when SVGAImageView  is called onDetachedFromWindow function,release soundpool

**Comment by PonyCui** [comment]
或许你可以先尝试一下这个 commit
	dependencies {
	        implementation 'com.github.yyued:SVGAPlayer-Android:850624093c'
	}
看看有没有解决问题？
我也不确定 finalize 是否一定会被调用。

**Comment by 456838** [comment]
com.github.yyued:SVGAPlayer-Android:850624093c' 没有调用到prepare方法。
实际使用2.4.2版本中存在部分情况下调用到invokeCompleteCallback没有被调用，看情况是解析音频和SoundPool.setOnLoadCompleteListener没有回调。

**Comment by PonyCui** [comment]
可能是 SoundPool 不稳定导致的。

**Comment by errnull** [comment]
已经修复了 Audio 没有清理的问题。
将在下个版本发布。

**Comment by errnull** [comment]
v2.5.3 中修复此问题
