### ISSUE TITLE
Failed to allocate a 769872 byte allocation with 712658 free bytes and 695KB until OOM

### ISSUE THREAD

**Issue by snowf07** [svga/SVGAPlayer-Android#116]
Failed to allocate a 769872 byte allocation with 712658 free bytes and 695KB until OOM
com.opensource.svgaplayer.SVGAVideoEntity.resetImages(SVGAVideoEntity.kt:88)

dalvik.system.VMRuntime.newNonMovableArray(Native Method)
--
2 android.graphics.BitmapFactory.nativeDecodeByteArray(Native Method)
3 android.graphics.BitmapFactory.decodeByteArray(BitmapFactory.java:522)
4 com.opensource.svgaplayer.SVGAVideoEntity.resetImages(SVGAVideoEntity.kt:88)
5 com.opensource.svgaplayer.SVGAVideoEntity.<init>(SVGAVideoEntity.kt:57)
6 com.opensource.svgaplayer.SVGAParser.parse(SVGAParser.kt:182)
7 com.opensource.svgaplayer.SVGAParser.access$parse(SVGAParser.kt:25)
8 com.opensource.svgaplayer.SVGAParser$parse$3.invoke(SVGAParser.kt:95)
9 com.opensource.svgaplayer.SVGAParser$parse$3.invoke(SVGAParser.kt:25)
10 com.opensource.svgaplayer.SVGAParser$FileDownloader$resume$1.run(SVGAParser.kt:61)
11 java.lang.Thread.run(Thread.java:818)

**Comment by PonyCui** [comment]
Check your svga file first, don't export large size png.

**Comment by snowf07** [comment]
thanks

**Comment by summeryi** [comment]
我也遇到过类似的问题，svga 文件不是很大，就500k 左右，但是一直放在哪里播放最后就oom
