### ISSUE TITLE
改变图层的颜色？

### ISSUE THREAD

**Issue by ansen666** [svga/SVGAPlayer-Android#123]
您好，我想给一个svga动画，改变图层的颜色可以吗？我看了你们的使用教程，只有用canvas画一个图层上去。

**Comment by PonyCui** [comment]
你要改变的是什么图层的颜色

**Comment by PonyCui** [comment]
应该可以用这个方法来实现 https://github.com/yyued/SVGAPlayer-Android/wiki/Dynamic-Drawer

**Comment by ansen666** [comment]
嗯。。。谢谢您的回复  我用setDynamicDrawer方法解决了，，，，我现在是用Canvas动态绘画Bitmap。

但是碰到了一个新的问题，就是我给SVGAImageView设置弧度，或者给Bitmap设置弧度都无效？麻烦您帮忙看看。

**Comment by PonyCui** [comment]
最好提供一个 Demo 以复现问题

**Comment by ansen666** [comment]
您好  运行效果图在这个图片上:http://sowcar.com/t6/692/1553841136x986907160.jpg

svga控件的我设置了shape背景，背景颜色是红色，并且设置了android:radius属性28dp。

运行之后，svga动画就是正方形了，没有弧度了。那个淡绿色背景就是svga动画。

**Comment by PonyCui** [comment]
Draw Cavnas 的时候要使用 drawRoundRect

**Comment by ansen666** [comment]
我都试过了。。。对图片的bitmap裁剪了，就是使用的drawRoundRect，也有可能我用的方法不对，我自己再看看吧，谢谢了哈
