### ISSUE TITLE
ScrollView中嵌套Svga，不显示

### ISSUE THREAD

**Issue by luobanghong** [svga/SVGAPlayer-Android#129]
<?xml version="1.0" encoding="utf-8"?>
<RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="300dp"
    android:layout_height="300dp"
    >
    <ScrollView
        android:layout_width="match_parent"
        android:layout_height="match_parent">

    <RelativeLayout
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:focusable="true"
        android:focusableInTouchMode="true"
        >
        <com.opensource.svgaplayer.SVGAImageView
            android:id="@+id/svga_a_in"
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            app:source="level_c_in.svga"
            app:autoPlay="true"
            />

    </RelativeLayout>
    </ScrollView>

</RelativeLayout>

**Comment by PonyCui** [comment]
You must specific the width and height as int.

**Comment by imxiaopeng** [comment]
在回调中设置布局参数：
 public void onComplete(@NotNull SVGAVideoEntity svgaVideoEntity) {
                SVGARect videoSize = svgaVideoEntity.getVideoSize();
                double width = videoSize.getWidth();
                double height = videoSize.getHeight();
                RelativeLayout.LayoutParams params= (RelativeLayout.LayoutParams) sv.getLayoutParams();
                params.width= (int) width;
                params.height= (int) height;
                sv.setLayoutParams(params);
                sv.setVideoItem(svgaVideoEntity);
                sv.startAnimation();
            }

**Comment by luobanghong** [comment]
thanks，it's ok.




| |
罗帮洪
邮箱：15701669792@163.com
|

签名由 网易邮箱大师 定制

在2019年05月22日 18:24，xiaopeng 写道：

在回调中设置布局参数：
public void onComplete(@NotNull SVGAVideoEntity svgaVideoEntity) {
SVGARect videoSize = svgaVideoEntity.getVideoSize();
double width = videoSize.getWidth();
double height = videoSize.getHeight();
RelativeLayout.LayoutParams params= (RelativeLayout.LayoutParams) sv.getLayoutParams();
params.width= (int) width;
params.height= (int) height;
sv.setLayoutParams(params);
sv.setVideoItem(svgaVideoEntity);
sv.startAnimation();
}
