### ISSUE TITLE
小米手机动画结束时，屏幕会有全屏空白闪动

### ISSUE THREAD

**Issue by zsndev** [svga/SVGAPlayer-Android#13]
红米note 4x手机，当loops=1，动画结束时，会有个全屏的空白页面从右边进入，然后消失
经多次测试后，补充：
有问题时，SVGAImageView的宽高都是match_parent，当我给定一个具体值后不在出现空白页

**Comment by PonyCui** [comment]
请提供一个可重现的 Sample 发送到 help@svga.io
