### ISSUE TITLE
Request an unique id property for the svga file 

### ISSUE THREAD

**Issue by peerless2012** [svga/SVGAPlayer-Android#130]
When i use `Glide` to load `svga` file, the glide will pass the `InputStream` to me, so i don't know where to unzip the file, whith the unique id, i can build the cache file path.

**Comment by PonyCui** [comment]
Maybe use the InputStream md5 digest?

**Comment by peerless2012** [comment]
Is there any articals to see why the parser need a cache key?

**Comment by PonyCui** [comment]
Because 1.0 format is zip format, needs a place to unzip.

**Comment by peerless2012** [comment]
So, use inputstream to genarate a md5 value may be a good way to generate a cache key, and there may no longer to pass a cache key to the parser.

**Comment by PonyCui** [comment]
That's right.

**Comment by peerless2012** [comment]
In issue #115 , I use glide to download and cache svga file and parse the svga file to `SVGAVideoEntity` , the Glide only pass me the inputstream, So it will be great to add a sync decode from stream method to the `SVGAParser`.

**Comment by errnull** [comment]
We will look at issue #115
