### ISSUE TITLE
Cache按HttpResponseCache设置还是不生效

### ISSUE THREAD

**Issue by zedazheng** [svga/SVGAPlayer-Android#134]
debug来到了SVGAParser类，decodeFromInputStream方法，没有走进这个判断 if (bytes.size > 4 && bytes[0].toInt() == 80 && bytes[1].toInt() == 75 && bytes[2].toInt() == 3 && bytes[3].toInt() == 4)  走了else

**Comment by zedazheng** [comment]
设置了max-age的header

**Comment by PonyCui** [comment]
并不是通过这里判断是否存在缓存

**Comment by zedazheng** [comment]
@PonyCui 哦，那有可能是什么问题呢

**Comment by zedazheng** [comment]
File httpCacheDir = new File(getCacheDir(), "http");
HttpResponseCache.install(httpCacheDir, 1024 * 1024 * 128);

**Comment by PonyCui** [comment]
要判断是否存在缓存，应根据是否有发生网络流量。

**Comment by zedazheng** [comment]
@PonyCui 嗯，谢谢，我就是一直在找本地缓存的文件找不到，是设置的缓存目录问题，已经可以了，看到没发生网络流量行为了
