### ISSUE TITLE
怎么使用在PC项目中

### ISSUE THREAD

**Issue by nellyc0319** [svga/SVGAPlayer-Android#136]
不好意思，实在没地方问了，作为一个设计师，操心着开发实现的问题
我们是一个PC POS 项目，用C++写的代码

**Comment by PonyCui** [comment]
那要看你用的是什么框架，QT 还是别的？

**Comment by nellyc0319** [comment]
QT

**Comment by PonyCui** [comment]
那你需要参照格式写一个 QT Player

**Comment by nellyc0319** [comment]
是否有一个详细的参考步骤，因为我是设计师，只动web的代码，看你们写ios和安卓写了一个礼拜，写一个QT player需要1个礼拜么？
稳重说到你们的项目中应该也有PC项目，是否可提供参考😄

**Comment by PonyCui** [comment]
我们也没有写过 QT Player 呢，不过实现一个应该难度不大吧。

**Comment by nellyc0319** [comment]
lottie也没相似的方法，小公司，您懂的，没有方法很难推进去

**Comment by nellyc0319** [comment]
是否可以用web方法嵌入呢

> 在 2019年5月9日，16:42，PonyCui <notifications@github.com> 写道：
> 
> QT Player

**Comment by PonyCui** [comment]
可以的，但你需要把 web 设为透明。
