### ISSUE TITLE
URL parse cache

### ISSUE THREAD

**Issue by wangyuanfei** [svga/SVGAPlayer-Android#14]
参数为url进行解析时 如果本地没有缓存 会 走http 请求 请求回来后 会根据：
        if (bytes.size > 4 && bytes[0].toInt() == 80 && bytes[1].toInt() == 75 && bytes[2].toInt() == 3 && bytes[3].toInt() == 4) 
判断是否进行本地缓存，bytes这里的前几个自己是哪里定义的？为什么我的sbga里面前几个字节不满足缓存要求？导致不能使用缓存的代码，请问怎么才能解决。
感谢解答

**Comment by PonyCui** [comment]
https://github.com/yyued/SVGAPlayer-Android#cache
