### ISSUE TITLE
Android 播放svga文件动画帧数和设计师设计的帧数不一致

### ISSUE THREAD

**Issue by Kuki93** [svga/SVGAPlayer-Android#143]
Android 播放svga文件动画帧数和设计师设计的帧数不一致，android前后会少一些，ios没有这个问题

**Comment by PonyCui** [comment]
性能问题导致丢帧

**Comment by Kuki93** [comment]
这又一部最新的魅族16s ，cpu是骁龙855

**Comment by errnull** [comment]
你好，方便提供一下相关的 .svga 文件用于定位问题吗？
可以将资源发送到 help@svga.io ,我们会尽快处理，并且保护版权不做他用。
@Kuki93

**Comment by errnull** [comment]
Reply timed out
