### ISSUE TITLE
设计缺陷

### ISSUE THREAD

**Issue by shuwenyouxi** [svga/SVGAPlayer-Android#144]
decodeFromURL方法中的 ParseCompletion,源码中是NonNull.
但是应该是要Nullable的,防止泄漏(莫非你们绑定lifecycle了?)

**Comment by PonyCui** [comment]
你是说 callback 可能被释放？

**Comment by shuwenyouxi** [comment]
```
//在一个View里

val svgaCallback = object : SVGAParser.ParseCompletion? {
    ...
}

SVGAParser(context.applicationContext).decodeFromURL(URL(url), svgaCallback)

override fun onDetachedFromWindow() {
        super.onDetachedFromWindow()
        svgaCallback = null
    }
```
我希望要这样,但是decodeFromURL方法的第二个参数不能是nullable

**Comment by shuwenyouxi** [comment]
@PonyCui

**Comment by PonyCui** [comment]
貌似没有这个必要将 svgaCallback 设为 null

**Comment by hehuiran** [comment]
> 貌似没有这个必要将 svgaCallback 设为 null

ParseCompletion 有很大的可能会造成泄露，因为onComplete方法中持有了外部activity中的SVGAImageView，decodeFromURL又是一个耗时操作，你们没有考虑到这一点吗

**Comment by PonyCui** [comment]
@errnull 这里确实可以优化一下。

**Comment by errnull** [comment]
Already fixed ae36dc3.
