### ISSUE TITLE
svga path shape动画导致内存持续增长

### ISSUE THREAD

**Issue by jiangerji** [svga/SVGAPlayer-Android#146]
在某些手机，svga中有使用Path路径绘制的shape动画的，svga会在绘制动画的过程中，动态的生成各种path来绘制shape动画，60帧的动画，可能最后会生成几千个参数不同的path对象,数量有可能更多，由于硬件加速的实现问题，path的参数稍有不同，某些手机会为每一个不同path绘制分配一块新的内存绘制，从而导致动画一直进行的话，分配的内存会一直持续增长，在le max 2这个手机上实验，demo里面加载会增长到300M，我们现在是让设计不使用shape动画来解决的

可以优化一下drawShape里面的path transform的计算

[party_feed_live_entrance.svga.zip](https://github.com/yyued/SVGAPlayer-Android/files/3210766/party_feed_live_entrance.svga.zip)

**Comment by PonyCui** [comment]
其实还是希望尽量少用 shape，因为 shape 的绘制确实太耗性能了。

**Comment by goodjok** [comment]
看了下源代码，bitmap没有recycle

**Comment by lic2050** [comment]
想问一下最新的2.4.7版本这个问题解决了没有，我现在用的2.4.6，也遇到这个问题

**Comment by goodjok** [comment]
path的确是个巨坑，生成将近上万个path，感觉都不是太科学

**Comment by errnull** [comment]
你好，这个需要 AE 插件支持，
可以麻烦提供一下这个动效的 AE 源文件吗，
发送到 help@svga.io,这边仅做测试使用。
@jiangerji

**Comment by errnull** [comment]
issue merge to
AE-Converter
See [#12](https://github.com/svga/SVGA-AEConverter/issues/12)

**Comment by 1wayticket** [comment]
> 在某些手机，svga中有使用Path路径绘制的shape动画的，svga会在绘制动画的过程中，动态的生成各种path来绘制shape动画，60帧的动画，可能最后会生成几千个参数不同的path对象,数量有可能更多，由于硬件加速的实现问题，path的参数稍有不同，某些手机会为每一个不同path绘制分配一块新的内存绘制，从而导致动画一直进行的话，分配的内存会一直持续增长，在le max 2这个手机上实验，demo里面加载会增长到300M，我们现在是让设计不使用shape动画来解决的
> 
> 可以优化一下drawShape里面的path transform的计算
> 
> [party_feed_live_entrance.svga.zip](https://github.com/yyued/SVGAPlayer-Android/files/3210766/party_feed_live_entrance.svga.zip)

我想问下 如果关闭硬件加速会不会好一些
