### ISSUE TITLE
导出的svga文件很大

### ISSUE THREAD

**Issue by heyijieyouxgs** [svga/SVGAPlayer-Android#147]
设计出的61张png的图片，大概5M多，生成的gif也是5M多，生成的svga文件也5M多，完全没有你们所说的压成几百K的样子，是不是生成文件的时候有什么设置？

**Comment by PonyCui** [comment]
用序列帧做出来的动画，怎么压都是徒劳。

**Comment by heyijieyouxgs** [comment]
那要用什么做动画？用AE吗？

**Comment by PonyCui** [comment]
http://svga.io/designer.html

**Comment by heyijieyouxgs** [comment]
我们是按这个文档做的，然后用的序列帧png到处svga文件，文件太大，现在卡在这里了，按你的说法，不能用序列帧，那应该用什么？就是开始设计的动画要用什么设计

**Comment by PonyCui** [comment]
就是不能用序列帧
