### ISSUE TITLE
使用Bitmap替换元素时宽度问题

### ISSUE THREAD

**Issue by moviesguo** [svga/SVGAPlayer-Android#148]
我在一个svga中替换一个宽度为600的元素,Bitmap的宽度为240,这个时候图片就会被放大,想问一下是不是必须要相同的时候才会正常显示

**Comment by 1290846731** [comment]
做动画设置的尺寸，图片会按照这个尺寸缩放

**Comment by PonyCui** [comment]
比例需要保持一致。
