### ISSUE TITLE
请问release版本中带okio的和不带okio的有什么差别

### ISSUE THREAD

**Issue by zsndev** [svga/SVGAPlayer-Android#15]
请问release版本中带okio的和不带okio的有什么差别，比如
2.0.6-okio-1.13.0 与 2.0.6
在首页的readme中，默认用的是不带okio的，是因为它更好么？我们该怎么选择？

**Comment by PonyCui** [comment]
没有什么区别，你可以使用不带 okio 的。
只是为了照顾某些客户端，强制使用 okio 1.13.0 版本。
