### ISSUE TITLE
startAnimation memory leak

### ISSUE THREAD

**Issue by talentlo** [svga/SVGAPlayer-Android#151]
* GC ROOT org.chromium.ui.base.WindowAndroid.mVSyncMonitor
* references org.chromium.ui.VSyncMonitor.mChoreographer
* references android.view.Choreographer.mCallbackQueues
* references array android.view.Choreographer$CallbackQueue[].[1]
* references android.view.Choreographer$CallbackQueue.mHead
* references android.view.Choreographer$CallbackRecord.action
* references android.animation.AnimationHandler$1.this$0 (anonymous implementation of android.view.Choreographer$FrameCallback)
* references android.animation.AnimationHandler.mAnimationCallbacks
* references java.util.ArrayList.elementData
* references array java.lang.Object[].[0]
* references android.animation.ValueAnimator.mUpdateListeners
* references java.util.ArrayList.elementData
* references array java.lang.Object[].[0]
* references com.opensource.svgaplayer.SVGAImageView$startAnimation$$inlined$let$lambda$1.this$0 (anonymous implementation of android.animation.ValueAnimator$AnimatorUpdateListener)
* references com.puddingmall.common.view.SVGAView.mContext
* leaks com.puddingmall.MainActivity instance

**Comment by 1290846731** [comment]
解析完成，动画执行前被销毁了没有清掉？

**Comment by andansky** [comment]
> 解析完成，动画执行前被销毁了没有清掉？

怎么清？

**Comment by yuanfangyan** [comment]
你好请问现在解决了吗

**Comment by errnull** [comment]
![截屏2019-12-27上午9 59 03](https://user-images.githubusercontent.com/28481578/71496686-87ae4180-288f-11ea-96b0-03752fc00b86.png)
进入控制器，解析动效，不播放，返回。
重复以上步骤，确实有内存没有降下来，
考虑可能是解析的 Bitmap 没有及时释放。
issue 合并至 #175
