### ISSUE TITLE
调用SVGADynamicEntity.setDynamicText方法文字居中问题

### ISSUE THREAD

**Issue by ansen666** [svga/SVGAPlayer-Android#153]
您好，请教一个问题，我调用SVGADynamicEntity类的setDynamicText方法动态设置文字，但是文字在画布上居中了，其实我想要靠左对齐的效果，这个能有办法解决吗？  谢谢

运行效果图:http://chuantu.xyz/t6/702/1560329732x2073530527.png

svga动画被我用红色的框圈起来了，麻烦您帮忙看看，谢谢。

**Comment by PonyCui** [comment]
https://github.com/yyued/SVGAPlayer-Android/wiki/Dynamic-Drawer
用 Canvas API 自己画
