### ISSUE TITLE
只能读取assets和网络文件吗？下载带sdk的文件能不能直接播放？

### ISSUE THREAD

**Issue by xieguangshun** [svga/SVGAPlayer-Android#154]
## Attention

* Do not ask any usage question, issue board is a issue board, accept library bugs only.
* If you are facing any usage problem, read the README again.

## Issue Template

Issue Description(What's your problem)

How To Reappear(How to reappear the issue)

Any Attachment(Provide a sample about your issue)

------ 中文分割线 ------

## 注意 

* 不要在 Issue 板块提问使用问题，Issue 板块只接受 Bug 反馈。
* 如果遇到使用上的问题，仔细阅读 README。

## Issue 模板

请尽量使用英文提交 Issue

请确切回答：问题的描述、重现方式、附件（提供一个 Demo 以重现问题）

**Comment by xieguangshun** [comment]
需求很恶心，我们的svga文件都1-2M，通过url加载的话，都要5-10秒的延迟，礼物又需要后台配置，所以把所有的svga文件直接放到assets里面，以后添加的动效就没办法播放了，所以现在的想法是，把礼物下载到sd卡，然后用svga播放,但是发现好像只能播放assets里面的文件

**Comment by PonyCui** [comment]
fun decodeFromInputStream(inputStream: InputStream, cacheKey: String, callback: ParseCompletion, closeInputStream: Boolean = false)

**Comment by xieguangshun** [comment]
有没有demo可以看看代码啊？刚刚试了没成功，也没有回调

**Comment by PonyCui** [comment]
你把对应的 InputStream 传进去就可以了

**Comment by xieguangshun** [comment]
可以了，多谢

**Comment by daijunsheng** [comment]
请问怎么实现的，demo里面没有案列，用fun decodeFromInputStream(inputStream: InputStream, cacheKey: String, callback: ParseCompletion, closeInputStream: Boolean = false)也加载不出来，感谢
