### ISSUE TITLE
SVGAParser实例开启线程

### ISSUE THREAD

**Issue by tigershinny** [svga/SVGAPlayer-Android#155]
每次新建SVGAParser，都开启一个线程池，导致多个动画时，线程数太多

**Comment by PonyCui** [comment]
你可以创建一个 Parser 单例

**Comment by tigershinny** [comment]
SVGAImageView loadAttrs时每次开启新线程，而且在这个线程中新建SVGAParser，这部分代码不可控。所有单例解决不了问题

**Comment by PonyCui** [comment]
这里确实可以改进一下，谢谢。

**Comment by xxjy** [comment]
#142 将SVGAParser中的线程池改成了静态变量

**Comment by PonyCui** [comment]
Merged
https://github.com/yyued/SVGAPlayer-Android/pull/142
