### ISSUE TITLE
svg文件放在/data/data/com.XX.XXX/svg

### ISSUE THREAD

**Issue by niuqilin** [svga/SVGAPlayer-Android#16]
不能直接播放svg文件放在/data/data/com.XX.XXX/svg 的文件

**Comment by PonyCui** [comment]
请把文件放在 assets 目录下，否则请自行获取 inputStream。

**Comment by Labmem003** [comment]
自行获取 inputStream播放的时候，有个cacheKey的东西是设计了来干嘛的？

**Comment by PonyCui** [comment]
cacheKey 是提供给 1.0 格式文件使用的，你可以忽略他。
