### ISSUE TITLE
使用了非SDK接口在AndroidQ会报错

### ISSUE THREAD

**Issue by hujiating** [svga/SVGAPlayer-Android#163]
用veridex检测出SVGA使用了下面的非SDK接口

#9: Reflection greylist-max-p Landroid/animation/ValueAnimator;->sDurationScale use(s):
       Lcom/opensource/svgaplayer/SVGAImageView;->startAnimation(Lcom/opensource/svgaplayer/utils/SVGARange;Z)V

**Comment by PonyCui** [comment]
It's necessary to use private api prevent [Developer Option], otherwise, animation will play as a error duration.
