### ISSUE TITLE
我们公司做直播购买的礼物播放问题

### ISSUE THREAD

**Issue by codesdt** [svga/SVGAPlayer-Android#164]
您好，最近我们公司遇到一个不好解决的问题，各种推卸问题，目前是我们购买的礼物，在我们的直播当中显示不全。不知道这是什么原因？

<details>
<summary>Details</summary>

__

</details>

**Comment by codesdt** [comment]
![1561363233576](https://user-images.githubusercontent.com/12639114/60001529-38494780-9699-11e9-81c4-56cb74c23a33.jpg)
更新了图片

**Comment by PonyCui** [comment]
set scaleType.

**Comment by codesdt** [comment]
对，设置了，但是显示的效果还是这样的 没有变化。

经过我测试 在你们的demo当中通过assets加载播放可以，为什么通过网络就不行了？

**Comment by PonyCui** [comment]
最好能提供一个 Demo

**Comment by codesdt** [comment]
谢谢您了，好像代码设置可以。
