### ISSUE TITLE
如何控制动画的宽高？我有个动画展示的场景是在半屏下播放的

### ISSUE THREAD

**Issue by 330132662** [svga/SVGAPlayer-Android#165]
如何控制动画的宽高？我有个动画展示的场景是在半屏下播放的，我在xml中写了宽高之后，动画就显示不选了。

**Comment by PonyCui** [comment]
设置 scaleType

**Comment by 330132662** [comment]
> 设置 scaleType

试过。。动画是小了，但是他所占用的屏幕面积还是那么大

**Comment by PonyCui** [comment]
最好能提供一个 Demo

**Comment by 330132662** [comment]
> 最好能提供一个 Demo

感谢回复~我终于自己捣鼓好了   ，可以通过宽高限制大小了。
https://github.com/330132662/SvgaTest
