### ISSUE TITLE
SVGAImageView 在recyclerciew中使用有问题

### ISSUE THREAD

**Issue by hehuiran** [svga/SVGAPlayer-Android#167]
我在item中SVGAImageView的布局：
<com.opensource.svgaplayer.SVGAImageView
        android:id="@+id/svga_frequency"
        android:layout_width="15dp"
        android:layout_height="15dp"
        android:layout_marginEnd="4dp"
        android:scaleType="centerCrop"
        app:source="anim/frequency.svga"
        app:autoPlay="true"
        app:layout_constraintEnd_toStartOf="@+id/tv_count"
        app:layout_constraintBottom_toBottomOf="@+id/tv_count"
        app:layout_constraintTop_toTopOf="@+id/tv_count"/>
结果发现上下滑动由于复用的问题部分item的SVGAImageView不播放了，即使我在适配器中的onbindviewhold方法中调用了SVGAImageView.startAnimation方法，还是不播放，我看源码发现解析自定义属性时只要设置了source属性就会new一个thread并且start，这样的话在recyclerview中会创建无数个线程，我尝试用另外的方式去解决在recyclerview中使用：
item中SVGAImageView的布局修改成
 <com.opensource.svgaplayer.SVGAImageView
        android:id="@+id/svga_frequency"
        android:layout_width="15dp"
        android:layout_height="15dp"
        android:layout_marginEnd="4dp"
        android:scaleType="centerCrop"
        app:autoPlay="false"
        app:layout_constraintEnd_toStartOf="@+id/tv_count"
        app:layout_constraintBottom_toBottomOf="@+id/tv_count"
        app:layout_constraintTop_toTopOf="@+id/tv_count"/>
去掉了source并且autoPlay="false"，我在fragment中直接解析svga文件得到SVGAVideoEntity，
SVGAParser parser = new SVGAParser(getContext());
        parser.decodeFromAssets("anim/frequency.svga", new SVGAParser.ParseCompletion() {
            @Override
            public void onComplete(SVGAVideoEntity svgaVideoEntity) {
                SVGADrawable drawable = new SVGADrawable(svgaVideoEntity);
                initRecyclerViewAndLoadData(drawable);
            }

            @Override
            public void onError() {
                LiveRoomLogger.getDefault().writeFormat(TAG, "decodeFromAssets.onError", "frequency.svga 解析失败");
                initRecyclerViewAndLoadData(null);
            }
        });
然后实例化SVGADrawable ，把SVGADrawable 通过recyclerview的adapter的构造方法传入，
public AudioSubAdapter(SVGADrawable drawable) {
        super(R.layout.audio_item_audio_list);
        this.mDrawable = drawable;
    }
然后在adapter的onbindviewhold方法中
SVGAImageView svga = helper.getView(R.id.svga_frequency);
        if (mDrawable != null) {
            svga.setVisibility(View.VISIBLE);
            svga.setImageDrawable(mDrawable);
            svga.startAnimation();
        }else {
            svga.setVisibility(View.GONE);
        }
发现还是不行，动画都播不出来，所以我想问该框架能否在recyclerview中使用？

**Comment by PonyCui** [comment]
使用代码，不使用 xml 可以更灵活地处理这种情况。

**Comment by hehuiran** [comment]
item中的SVGAImageView，我在布局中把source去掉了
<com.opensource.svgaplayer.SVGAImageView
        android:id="@+id/svga_frequency"
        android:layout_width="15dp"
        android:layout_height="15dp"
        android:layout_marginEnd="4dp"
        android:scaleType="centerCrop"
        app:autoPlay="true"
        app:layout_constraintEnd_toStartOf="@+id/tv_count"
        app:layout_constraintBottom_toBottomOf="@+id/tv_count"
        app:layout_constraintTop_toTopOf="@+id/tv_count"/>
然后在adapter的onbindviewholder方法中：
SVGAImageView svga = helper.getView(R.id.svga_frequency);
        SVGAParser parser = new SVGAParser(mContext);
        parser.decodeFromAssets("anim/frequency.svga", new SVGAParser.ParseCompletion() {
            @Override
            public void onComplete(SVGAVideoEntity svgaVideoEntity) {
                SVGADrawable drawable = new SVGADrawable(svgaVideoEntity);
                svga.setImageDrawable(drawable);
                svga.startAnimation();
            }

            @Override
            public void onError() {

            }
        });
发现还是有复用问题，部分item上下滑动后动画不播放了，画布也被清空了

**Comment by PonyCui** [comment]
在 view 被复用时，重新设置 videoItem 并调用 startAnimation。

**Comment by PPTing** [comment]
我们在项目里也遇到了这个问题，在 RecyclerView 滑回已经展示过的部分 item 时没有重新走入 `onBindViewHolder` 方法，所以尝试在 `onViewAttachedToWindow` 中解析和重新播放动画，基本能解决问题

```
   override fun onViewAttachedToWindow(holder: ViewHolder) {
        super.onViewAttachedToWindow(holder)
        val svga = adapter.items[holder.adapterPosition] as Svga
        if (holder.itemSvga.drawable != null && TextUtils.equals(svga.name,holder.name)){
            Log.d("PPTing","restart animation at ${holder.adapterPosition}")
            holder.itemSvga.startAnimation()
        }else{
            val parser = SVGAParser(holder.itemView.context)

            parser.parse(svga.name,object : SVGAParser.ParseCompletion{
                override fun onComplete(videoItem: SVGAVideoEntity) {
                    Log.d("Svga","on complete ${holder.adapterPosition}")
                    val drawable = SVGADrawable(videoItem)
                    holder.itemSvga.setImageDrawable(drawable)
                    holder.itemSvga.startAnimation()
                    holder.name = svga.name
                }

                override fun onError() {
                    Log.d("","on error ${holder.adapterPosition}")
                }
            })
        }
    }
```

**Comment by nanako889** [comment]
在Recyclerview中使用，滑动一会之后，程序就无响应了，有谁遇到过？

**Comment by MitchZhang** [comment]
> 在 view 被复用时，重新设置 videoItem 并调用 startAnimation。

重新调用也不行

**Comment by MitchZhang** [comment]
> 在 view 被复用时，重新设置 videoItem 并调用 startAnimation。

重新调用也不行

**Comment by YuanTiger** [comment]
最近我在开发用户头像添加SVGA动画时也遇到了同样的问题。

@PPTing 的方法我试了一下，是可以解决问题的。但是通过日志打印可以发现，这样写是存在性能问题的，比如刚刚打开一个列表，这时每个条目都会执行`onBindViewHolder()`和`onViewAttachedToWindow()`两个方法，导致条目初始化2遍。并且当条目滑出滑进时，每个条目进入都会执行`onViewAttachedToWindow()`,有些条目进入的同时也会执行`onBindViewHolder()`。

想要解决这个问题的关键在于`onBindViewHolder()`为什么会不执行，查阅了一些RecyclerView的缓存知识，了解到RecyclerView会有三级缓存，默认启动了两级。其中一级缓存的是刚刚滑出屏幕的holder，也就是说当某个holder刚刚被滑出屏幕时，马上重新将它再滑动到屏幕中，是不会执行`onBindViewHolder()`的，这一级缓存的条目数默认为2。

调用`recyclerView.setItemViewCacheSize(0)`就可以将这一级的缓存数量设置为0，本以为可以解决问题，但是不知道为什么还是总有1个刚刚滑出屏幕的条目，马上再把它滑回来，仍然会不执行`onBindViewHolder()`。但是确实生效了，因为在设置之前，大概有3、4个连续条目会不执行`onBindViewHolder()`。

所以想请教一下能不能解决这个问题。。

感谢作者大大的开源。

**Comment by wcngsb** [comment]
我们的项目中也有这个问题，这个问题的影响还是挺大的，麻烦尽量解决下

**Comment by cosmochina** [comment]
当RecyclerView中的item不可见之后会调用SVGImageView的onDetachedFromWindow
修改这个方法然后在RecyclerView中的SVGImageView设置clearsAfterDetached=false就可以了

   override fun onDetachedFromWindow() {
        super.onDetachedFromWindow()
        if (clearsAfterDetached) {
            stopAnimation(true)
            clear()
        } else {
            stopAnimation(false)
        }
    }

**Comment by painld6** [comment]
试试更新到 2.5.14，并且设置 SVGAImageView#clearAfterDetached 和 SVGAImageView#clearAfterStop 这两个属性为 false

**Comment by LuJN** [comment]
> 在Recyclerview中使用，滑动一会之后，程序就无响应了，有谁遇到过？

请问你解决了吗

**Comment by binbinyYang** [comment]
解决了吗 我也遇到    recyclerciew中用不了svga 他压根不显示

**Comment by XuHX** [comment]
> 

解决了吗
