### ISSUE TITLE
怎么控制宽度高度？

### ISSUE THREAD

**Issue by TopTime1** [svga/SVGAPlayer-Android#168]
比如说动画画布是400*400，我不想我加载出来的动画四周有边距，在回调里设置宽高，好想没啥效果，animationView.setMaxHeight((int)videoItem.getVideoSize().getHeight());
                animationView.setMaxWidth((int)videoItem.getVideoSize().getWidth());

**Comment by PonyCui** [comment]
LayoutParams

**Comment by TopTime1** [comment]
ok
