### ISSUE TITLE
HttpResponseCache问题

### ISSUE THREAD

**Issue by jasonsz** [svga/SVGAPlayer-Android#17]
我按照文章所说的设置了Cache，但是svga文件并没有缓存下来，是什么情况？

**Comment by PonyCui** [comment]
如果HTTP请求 Response Header 没有设置 max-cache 是不会被缓存的。

**Comment by jasonsz** [comment]
URL netSvgaUrl = null;
		URLConnection connection;
		try {
			netSvgaUrl = new URL(url);
			connection = netSvgaUrl.openConnection();
			connection.addRequestProperty("Cache-Control", "only-if-cached");
			connection.addRequestProperty("Cache-Control", "max-age=0");
		} catch (Exception e) {
			e.printStackTrace();
		}
svgaParser.parse(netSvgaUrl, new SVGAParser.ParseCompletion(){});

我这样写了之后还是没有缓存，是哪里设置错吗？

**Comment by jasonsz** [comment]
谢谢，是我之前文件存储的路径弄的有问题
