### ISSUE TITLE
部署香港服务的地址这个SVGA不能播放，国内的都是可以的

### ISSUE THREAD

**Issue by moanyuan** [svga/SVGAPlayer-Android#170]
http://hw.static.djdl2009.com/201927/15621399564c17bb.svga

**Comment by PonyCui** [comment]
请自行查找原因

**Comment by moanyuan** [comment]
> 
> 
> 请自行查找原因

 这是SVGAsdk 内部报的错误，外部使用没有任何问题。包括连接在IOS 上也是可以播放的，请帮忙查找下原因，谢谢
