### ISSUE TITLE
动画暂停之后svga动画消失不见了

### ISSUE THREAD

**Issue by MinardWu** [svga/SVGAPlayer-Android#172]
pauseAnimation停之后svga动画消失不见了，背景还在

**Comment by PonyCui** [comment]
那你应该使用 stopAnimation

**Comment by MinardWu** [comment]
> 那你应该使用 stopAnimation

用了stopAnimation也没有用，我的需求是暂停的时候让svga动画和背景都能留着

**Comment by PonyCui** [comment]
pauseAnimation 是可以保持动画内容的，或者你提供一个 Demo 看看问题？

**Comment by MinardWu** [comment]
> pauseAnimation 是可以保持动画内容的，或者你提供一个 Demo 看看问题？

问了下基础库那边开发，应该是我们修改出来的bug，麻烦大佬了

**Comment by PonyCui** [comment]
好的
