### ISSUE TITLE
关于内存部分的设计缺陷

### ISSUE THREAD

**Issue by goodjok** [svga/SVGAPlayer-Android#175]
仔细分析了下整个库的源代码，内存机制做得不是很好：

1、首先bitmap没有做recycle,只是简单的把缓存list清理掉，代码好几处都是这个问题

2、path数组数据回收不是很及时，会对一些使用频次高或者内存消耗大的应用增加负担，我看代码都是定义的一些final数组数据，只能在对象被回收的时候才会释放，没有考虑实际使用场景里面，最合理的做法是 调用  setDrawable(null) 方法的时候，传空对象的时候把这些数组数据都要清空干净，并且要保证gc及时清理的状态

3、BitmapFactory 创建 bitmap的时候需要把 OOM异常捕获住，保证即使无法显示图片也不要出现崩溃

以上是个人总结的三个致命性问题，希望引起重视。

**Comment by errnull** [comment]
谢谢你的反馈。
p3 已经加上了 OutOfMemoryError Catch 9b20272;
p2 目前正在整理中...
p1 从 doc 里面看到 bitmap 似乎不建议主动调用 recycle
![3hrpsy43n5](https://user-images.githubusercontent.com/28481578/64613370-8d7b3680-d408-11e9-884e-86631ce481a7.jpg)
@goodjok

**Comment by goodjok** [comment]
那是在ImageView使用场景中被设置到BitmapDrawable中，BitmapDrawable会自动回收，当前功能是bitmap绘制到画布上的处理方式，需要自己回收。

@errnull

**Comment by PonyCui** [comment]
嗯……这确实需要考虑一下是否有不一样的地方。

**Comment by PonyCui** [comment]
然而之前尝试过添加 recycle，出现了一堆莫名奇妙的 crash，才去掉的。

**Comment by goodjok** [comment]
第一个问题其实很好复现，你就反复的用 SVGAParser.decodeFromAssets  生成 SVGADrawable，然后赋值给  SVGAImageView.setImageDrawable
做个长时间多次循环这样的处理，看内存或者等待OOM出现

其它使用bitmap的地方 得做 bitmap.isRecycled 判断，估计你说的是出现被recycle的bitmap又被使用的crash吧？

另外集合类编辑使用可能存在concurrent问题，也得注意

@errnull  @PonyCui

**Comment by PonyCui** [comment]
值得测试一下

**Comment by HalyangDream** [comment]
> 值得测试一下

怎么解决这个OOM的问题

**Comment by zxzx74147** [comment]
希望能从外部设置ImageLoader。

发现源码里使用BitmapFactory.decodeXXX方式载入图片，这样有三个问题，一是上面说的，回收问题比较头痛；二是与App已有图片内存管理分裂，相当于多了一个图片内存空间，不好控制大小；三是对于svga的复用不友好，如果在列表里面使用多个重复的svga动画，每次都会进行一次decode并增加一倍内存占用。希望能够暴露出ImageLoader接口接口给App实现，App一般都使用了诸如Glide、Picasso等比较成熟的图片加载框架，把图片加载都统一管理，回收、内存、复用等问题都会得到解决，SDK把图片加载工作外放给App接管也是比较流行的做法。

希望能够采纳，谢谢！

**Comment by PonyCui** [comment]
@zxzx74147 这个提议不太现实，当前 decode 的数据源是 bytes 而不是所谓的 url，另外，我们并不希望由一个外部的 Manager 控制这些 decode 后的 Bitmap 引用，可能导致意外的 Recycle。

**Comment by MaryDQ** [comment]
内存问题有进展吗

**Comment by daishengda2018** [comment]
处理了 SVGAImageView 两个明显内存泄漏点，已经提交 [PR地址](https://github.com/svga/SVGAPlayer-Android/pull/251)，请各位大佬 Review.

**Comment by zhej** [comment]
> 处理了 SVGAImageView 两个明显内存泄漏点，已经提交 [PR地址](https://github.com/svga/SVGAPlayer-Android/pull/251)，请各位大佬 Review.

我更新svga2.5.3的版本，发现没有，你这个的版本号是多少

**Comment by daishengda2018** [comment]
> > 处理了 SVGAImageView 两个明显内存泄漏点，已经提交 [PR地址](https://github.com/svga/SVGAPlayer-Android/pull/251)，请各位大佬 Review.
> 
> 我更新svga2.5.3的版本，发现没有，你这个的版本号是多少

处理的代码已经合并进主分支了，但维护者还没有发布版本。 @errnull @PonyCui 可以发布个新的版本吗？

**Comment by zenglihao** [comment]
同求新版本 @errnull  @PonyCui

**Comment by daishengda2018** [comment]
最近对 SVGA 的内存问题做了进一步跟踪和修改，过两天在确定稳定后将会贡献给组织，先做个预告：

1. Bitmap 等资源的清理工作：在 SVGA 播放播放完成后，清理 Drawable、Bitmap 的强引用，达到可GC的目的，这一步效果很明显。
2. 创建 Btimap 时根据 View Size 计算采样率，减少内存消耗。

经过这两个步骤，内存消耗的改观还是挺明显的。

除此之外还做了代码结构的重构、线程的使用方式、移除对于 finalize 的使用等。敬请期待。

**Comment by PonyCui** [comment]
@daishengda2018 期待

**Comment by daishengda2018** [comment]
> 最近对 SVGA 的内存问题做了进一步跟踪和修改，过两天在确定稳定后将会贡献给组织，先做个预告：
> 
> 1. Bitmap 等资源的清理工作：在 SVGA 播放播放完成后，清理 Drawable、Bitmap 的强引用，达到可GC的目的，这一步效果很明显。
> 2. 创建 Btimap 时根据 View Size 计算采样率，减少内存消耗。
> 
> 经过这两个步骤，内存消耗的改观还是挺明显的。
> 
> 除此之外还做了代码结构的重构、线程的使用方式、移除对于 finalize 的使用等。敬请期待。

代码已经提交 #263 请各位 review。

**Comment by easternHong** [comment]
https://github.com/YvesCheung/SVGAGlidePlugin
看下这个

**Comment by l476175728** [comment]
> 同求新版本 @errnull @PonyCui

@errnull @PonyCui

**Comment by daishengda2018** [comment]
各位同学，在 2.5.5 版本中存在一个 bug 会导致低于 Api 21 的手机奔溃，对于此问题的详细描述请参阅 #266  。现已修复请升级版本 [2.5.6](https://github.com/svga/SVGAPlayer-Android/releases/tag/2.5.6)

**Comment by daishengda2018** [comment]
> 谢谢你的反馈。
> p3 已经加上了 OutOfMemoryError Catch [9b20272](https://github.com/svga/SVGAPlayer-Android/commit/9b202722c8d4e3140cf8f0426937c5ca3f99415d);
> p2 目前正在整理中...
> p1 从 doc 里面看到 bitmap 似乎不建议主动调用 recycle
> ![3hrpsy43n5](https://user-images.githubusercontent.com/28481578/64613370-8d7b3680-d408-11e9-884e-86631ce481a7.jpg)
> @goodjok

SVGA 内部源码中 try cache 了 OOM 异常，我认为这是不可取的。遇到问题最好的办法就是直接面对他。try cache 后直接导致发生 OOM 时无法定位到根本原因，解决问题的思路完全被带歪。 所以我建议以后的版本中移除 try cache OOM，库不完善我们完善库，业务场景有问题我们优化场景。这种方案看似解决了问题实质上埋下了更大的雷。

**Comment by iostyle** [comment]
> > 谢谢你的反馈。
> > p3 已经加上了 OutOfMemoryError Catch [9b20272](https://github.com/svga/SVGAPlayer-Android/commit/9b202722c8d4e3140cf8f0426937c5ca3f99415d);
> > p2 目前正在整理中...
> > p1 从 doc 里面看到 bitmap 似乎不建议主动调用 recycle
> > ![3hrpsy43n5](https://user-images.githubusercontent.com/28481578/64613370-8d7b3680-d408-11e9-884e-86631ce481a7.jpg)
> > @goodjok
> 
> SVGA 内部源码中 try cache 了 OOM 异常，我认为这是不可取的。遇到问题最好的办法就是直接面对他。try cache 后直接导致发生 OOM 时无法定位到根本原因，解决问题的思路完全被带歪。 所以我建议以后的版本中移除 try cache OOM，库不完善我们完善库，业务场景有问题我们优化场景。这种方案看似解决了问题实质上埋下了更大的雷。

说得好👏
