### ISSUE TITLE
你好 怎么在imageview上动态添加文字

### ISSUE THREAD

**Issue by Licarey** [svga/SVGAPlayer-Android#176]
## Attention

* Do not ask any usage question, issue board is a issue board, accept library bugs only.
* If you are facing any usage problem, read the README again.

## Issue Template

Issue Description(What's your problem)

How To Reappear(How to reappear the issue)

Any Attachment(Provide a sample about your issue)

------ 中文分割线 ------

## 注意 

* 不要在 Issue 板块提问使用问题，Issue 板块只接受 Bug 反馈。
* 如果遇到使用上的问题，仔细阅读 README。

## Issue 模板

请尽量使用英文提交 Issue

请确切回答：问题的描述、重现方式、附件（提供一个 Demo 以重现问题）

**Comment by PonyCui** [comment]
https://github.com/yyued/SVGAPlayer-Android/wiki/Dynamic-Text-Layout
看文档再提问

**Comment by Licarey** [comment]
嗯 不好意思 可以了




------------------ 原始邮件 ------------------
发件人: "PonyCui"<notifications@github.com>;
发送时间: 2019年8月8日(星期四) 下午4:11
收件人: "yyued/SVGAPlayer-Android"<SVGAPlayer-Android@noreply.github.com>;
抄送: "∑═/aiq═→"<313685617@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [yyued/SVGAPlayer-Android] 你好 怎么在imageview上动态添加文字 (#176)




Closed #176.
