### ISSUE TITLE
loopCount="1",the animation is slower than the desired effect.

### ISSUE THREAD

**Issue by duqian291902259** [svga/SVGAPlayer-Android#177]
if set loopCount="1",the animation is slower than the desired effect.

but when it loops(loopCount="0"  or more counts) it's ok.

**Comment by PonyCui** [comment]
could you provide an example?

**Comment by duqian291902259** [comment]
> could you provide an example?

I have created a pull request to you. scaling the duration of animation to modify the speed.

**Comment by PonyCui** [comment]
I don't think we need a parameter to change the speed of animation.

**Comment by duqian291902259** [comment]
How to send you samples?Sometimes, we have requirements to change speed.Any way,if no need for it,I must implement it to project with source.

**Comment by PonyCui** [comment]
Why need to change the speed? How about ask designer provide another file?

**Comment by errnull** [comment]
> How to send you samples? Sometimes, we have requirements to change speed. Anyway, if no need for it, I must implement it to project with the source.

Could you please upload your samples to repositories and post the URL here.
@duqian291902259

**Comment by errnull** [comment]
Reply timed out
