### ISSUE TITLE
动态文本和图像

### ISSUE THREAD

**Issue by wangyubao** [svga/SVGAPlayer-Android#18]
按照文档添加动态文本和图像没效果，是对SVGA动画有要求吗？

**Comment by PonyCui** [comment]
你需要和设计师沟通好对应的 ImageKey
ImageKey 就是素材的文件名

**Comment by wangyubao** [comment]
感谢回复！很喜欢这个框架
SVGADrawable drawable = new SVGADrawable(videoItem, dynamicItem);
如果是动态图像 videoItem 这个原动图里的素材要和dynamicItem的key对应是吧？
动态文本也是这样吗？

**Comment by PonyCui** [comment]
是的
