### ISSUE TITLE
用代码动态添加什么都不显示

### ISSUE THREAD

**Issue by i91h1r** [svga/SVGAPlayer-Android#183]
在recycleview 的adapter  xml里面写一个FrameLayout，然后通过服务器传的个数动态添加到FrameLayout 中，运行起来不显示 请问是什么情况哦？

 SVGAImageView collegeIv = new SVGAImageView(holder.itemView.getContext());
    
        holder.collegeItemLayoutBinding.fl.addView(collegeIv);
        
            SVGAParser parser = new SVGAParser(holder.itemView.getContext());
    
                parser.decodeFromAssets("test2.svga", new SVGAParser.ParseCompletion() {
                    @Override
                    public void onComplete(@NotNull SVGAVideoEntity videoItem) {
                        collegeIv.setVideoItem(videoItem);
                        collegeIv.startAnimation();
                    }
                    @Override
                    public void onError() {
                
                    }
                });

**Comment by PonyCui** [comment]
请补充可重现的 Demo

**Comment by errnull** [comment]
@hyr0318

**Comment by hyr0318** [comment]
@errnull  这个已经解决  固定一个宽高就可以正常显示了。但是有另外一个问题，加载本地svga资源时候，第一次安装app 进入界面会不加载，退出当前界面 再进入就正常显示

**Comment by i91h1r** [comment]
@errnull  @PonyCui 这个已经解决 固定一个宽高就可以正常显示了。但是有另外一个问题，加载本地svga资源时候，第一次安装app 进入界面会不加载，退出当前界面 再进入就正常显示

**Comment by errnull** [comment]
这个问题场景不是很清晰，可以提供一个 Demo 方便排查吗？
@hyr0318

**Comment by errnull** [comment]
Reply timed out
