### ISSUE TITLE
【2.4.7版本】带有音频的svga加载音频失败后就没有任何回调事件，阻塞队列问题

### ISSUE THREAD

**Issue by xiaojianglaile** [svga/SVGAPlayer-Android#186]
## Attention
 
![image](https://user-images.githubusercontent.com/10496088/65370995-84545a00-dc91-11e9-8768-02ffef83581d.png)

**Comment by errnull** [comment]
你好可以提供一下相关的 svga 测试文件吗，
发到 help@svga.io 仅做测试使用。
@xiaojianglaile

**Comment by Datcon** [comment]
ok,收到------------------ 原始邮件 ------------------
发件人: "詹瞻在欢聚"<notifications@github.com>
发送时间: 2019年12月24日(星期二) 下午3:28
收件人: "yyued/SVGAPlayer-Android"<SVGAPlayer-Android@noreply.github.com>;
抄送: "Datcon"<liu546705@foxmail.com>;"Manual"<manual@noreply.github.com>;
主题: Re: [yyued/SVGAPlayer-Android] 【2.4.7版本】带有音频的svga加载音频失败后就没有任何回调事件，阻塞队列问题 (#186)



你好可以提供一下相关的 svga 测试文&#x4EF6;吗，
 发到 help@svga.io 仅做测试使用。
 
&mdash;

**Comment by errnull** [comment]
已收到反馈，原因定位到，
即将修复。

**Comment by errnull** [comment]
v2.5.3 中修复此 issue
