### ISSUE TITLE
parser.decodeFromURL()方法，没有执行缓存策略

### ISSUE THREAD

**Issue by huanghuihao** [svga/SVGAPlayer-Android#187]
您好：
我在Application的onCreate()方法中已经配置了缓存目录信息:
File cacheDir = new File(App.this.getCacheDir().getAbsolutePath());
HttpResponseCache.install(cacheDir, 1024 * 1024 * 128);

生成在缓存目录里面会有两个文件一个的后缀是“.0”一个的后缀是“.1”。
根据buildCacheKey()方法找到的路径，不含后缀，直接就找不到之前在cache目录里面下载的文件。这样parser.decodeFromURL()每次都是走的从网络读取。

**Comment by zicen** [comment]
我也遇到了同样的问题。版本 SVGAPlayer-Android:2.4.7
![image](https://user-images.githubusercontent.com/18431596/69396501-6650b780-0d1d-11ea-942c-47fd5803601b.png)

**Comment by PonyCui** [comment]
这个缓存是由 HttpResponseCache 进行管理的，是否命中，是由 Android 系统决定的。
如果需要使用定制化的缓存策略，建议使用 OKHTTP 库进行请求。

**Comment by zicen** [comment]
> 这个缓存是由 HttpResponseCache 进行管理的，是否命中，是由 Android 系统决定的。
> 如果需要使用定制化的缓存策略，建议使用 OKHTTP 库进行请求。
如何使用 OKHttp 去请求，缓存这个呢？文档上没有看到相关的介绍

**Comment by zicen** [comment]
你好，请问这个问题调查的怎么样了？另外可否给个 OKHttp 请求的示例，我这边直接使用 OKHttp 请求，还是没有命中到缓存。断点调试就是 `buildCacheKey` 这个方法获取的文件名和本地存的不一样而已。
![image](https://user-images.githubusercontent.com/18431596/70431397-f29e0100-1ab7-11ea-98fb-6264d0e26438.png)

**Comment by zicen** [comment]
我懂了，这个 isCached 返回值是没关系的，虽然这个 isCached 返回了 false 但是只要请求的时候没有产生流量就是使用缓存了。可以抓包看到。
