### ISSUE TITLE
动态替换多个element 只有最后一个element生效了

### ISSUE THREAD

**Issue by DamonMinko** [svga/SVGAPlayer-Android#188]
SVGADynamicEntity dynamicEntity = new SVGADynamicEntity();
                                TextPaint textPaint = new TextPaint();
                                textPaint.setColor(Color.WHITE);
                                textPaint.setTextSize(28);
                                dynamicEntity.setDynamicText("wdnmd", textPaint, "leftname");
                                SVGADrawable drawable = new SVGADrawable(videoItem, dynamicEntity);
                                SVGADynamicEntity dynamicEntity1 = new SVGADynamicEntity();
                                dynamicEntity1.setDynamicText("dmndw",textPaint,"rightname");
                                SVGADrawable drawable1 = new SVGADrawable(videoItem, dynamicEntity1);

                                SVGADynamicEntity dynamicEntity2 = new SVGADynamicEntity();
                                dynamicEntity2.setDynamicImage(bitmaps.get(0),"leftuser");
                                SVGADrawable drawable2 = new SVGADrawable(videoItem, dynamicEntity2);

                                SVGADynamicEntity dynamicEntity3 = new SVGADynamicEntity();
                                dynamicEntity3.setDynamicImage(bitmaps.get(1),"rightuser");
                                SVGADrawable drawable3 = new SVGADrawable(videoItem, dynamicEntity3);

                                mSvgaImageView.setImageDrawable(drawable);
                                mSvgaImageView.setImageDrawable(drawable1);
                                mSvgaImageView.setImageDrawable(drawable2);
//                                mSvgaImageView.setImageDrawable(drawable3);
                                mSvgaImageView.startAnimation();

**Comment by PonyCui** [comment]
哥，你这个是什么意思~

```
mSvgaImageView.setImageDrawable(drawable);
mSvgaImageView.setImageDrawable(drawable1);
mSvgaImageView.setImageDrawable(drawable2);
```

自己要不要想想为什么要 setImageDrawable，这不是 BUG，请仔细想一下为什么。
