### ISSUE TITLE
内存溢出

### ISSUE THREAD

**Issue by niuqilin** [svga/SVGAPlayer-Android#19]
直接使用该框架播放svg动画时，多次播放动画 会出现内存溢出
Failed to allocate a 1325462 byte allocation with 541118 free bytes and 528KB until OOM
com.opensource.svgaplayer.SVGAVideoEntity.resetImages(SVGAVideoEntity.kt:84)

**Comment by PonyCui** [comment]
你的 SVGA 文件在输出时是否提示内存占用过大？
如果是，需要设计师优化 PNG 素材后再输出。
