### ISSUE TITLE
SVGAParser cache 缓存策略问题

### ISSUE THREAD

**Issue by iostyle** [svga/SVGAPlayer-Android#190]
缓存路径是写死的 context.cacheDir.absolutePath + "/" + cacheKey + "/"

**Comment by iostyle** [comment]
并且下载文件后缀为 .0 .1 是什么意思 如果自己写缓存策略的话，该用哪个

**Comment by PonyCui** [comment]
如果你使用的 svga 文件格式为 2.0，则完全不用关心该问题。
如果你仍然使用 1.0 的格式，这个问题其实也可以忽略，它只是一个临时缓存。

**Comment by zicen** [comment]
1. svga 文件格式为 2.0 还是 1.0 怎么看？
2. 为什么说不用关心这个问题？缓存如果没有命中的话，就没有意义了啊。我这边就是 decodeFromURL 
isCached 判断直接就false 了。缓存目录是有文件的，但是没有命中。

**Comment by PonyCui** [comment]
@zicen 1.0 格式文件不建议继续使用，1.0 格式文件缓存是使用 unzip 后的文件 decode，2.0 不需要这一步。
Parser 不负责缓存的管理，交由 Downloaer 进行缓存管理。
至于缓存是否命中，不是 Parser 的问题。
