### ISSUE TITLE
请问 放在一个recycleview列表里面，屏幕滑出当前item之后再重新滑出来，svga动图消失了，当前item 的普通imageview 没有这种现象。请问是什么问题？

### ISSUE THREAD

**Issue by i91h1r** [svga/SVGAPlayer-Android#194]

**Comment by shuikeyi** [comment]
源码写死了在onDetachedFromWindow()里回收所有资源，太坑了

**Comment by sun55** [comment]
同問，如何處理？

**Comment by errnull** [comment]
issue merge #167

**Comment by songliao-branch** [comment]
@shuikeyi 我看了下 并没有回收啊
![e076eb822b4910e6a62e7d3e9e2af70](https://user-images.githubusercontent.com/8410255/104677300-253b1400-5724-11eb-973a-1ab2511d8936.png)
