### ISSUE TITLE
是否支持在React Native 中使用？

### ISSUE THREAD

**Issue by hello-jun** [svga/SVGAPlayer-Android#195]
YY团队，你好！我们一直在寻找RN上友好的动画实现方案，请问贵方player是否支持RN？期待您的回复

**Comment by errnull** [comment]
你好。之前做过 SVGAPlayer React 的尝试，
https://github.com/yyued/SVGAPlayer-iOS/blob/master/SVGAPlayer-React.podspec
不过现在已经不再维护。
React 上可以尝试使用 
https://github.com/PonyCui/SVGAPlayer-SVG#svgaplayer-svg
将 SVGA 转成 SVG 再 Web 组件中播放。

**Comment by BANG88** [comment]
@errnull 可以继续维护吗？应该改动不是很多

**Comment by BANG88** [comment]
https://github.com/bang88/react-native-svga-player

**Comment by hello-jun** [comment]
> https://github.com/bang88/react-native-svga-player

非常感谢 @bang88 ，目前已在团队中采用Lottie实现动画方案，但后续我会尝试实验性地使用您开发的player
