### ISSUE TITLE
在线播放器内存计算

### ISSUE THREAD

**Issue by 1290846731** [svga/SVGAPlayer-Android#196]
请问在线播放器的内存计算是怎么算的？
在线播放器显示的内存占用为什么和真实在客户端中播放的差这么多？
Android和IOS的内存占用是否有明显区别
内存占用和帧率是否有比较大的关系？
如果要对设计师做约束应当如何约束？（总不能每给一个动画，我们放到客户端跑一下看一下内存占用吧）（目前想到的是做一个简单的工具，检查动画内图片尺寸是否超过动画尺寸，是否还有其他维度？）

**Comment by PonyCui** [comment]
所有元素（PNG）面积 * 4 就是粗略的内存占用

**Comment by PonyCui** [comment]
http://svga.io/svga-preview.html
拖入 SVGA 文件就可以看到占用

**Comment by 1290846731** [comment]
> http://svga.io/svga-preview.html
> 拖入 SVGA 文件就可以看到占用

但是在这个地址看到的内存占用和在客户端的内存占用差别很大
