### ISSUE TITLE
请问，添加文本的时候，字号的大小是怎么适配的

### ISSUE THREAD

**Issue by fdh19979** [svga/SVGAPlayer-Android#197]
看了文档没有写画笔的字号是怎么适配
textPaint.setTextSize(28);
我按照正常的SP转PX以后设置进去，字会变的非常大

经过更换svgaImageview的尺寸发现，这个字号是跟这个尺寸相对的，尺寸越大，字就越大，所以这个字号适配是应该有一个比例值的

**Comment by fdh19979** [comment]
经过分析代码找到一种适配方式
根据绘制bitmap的像素宽度W，bitmap在屏幕上显示的像素宽度C，字号的像素值S，得出绘制时画笔的像素大小s=S*W/C

有个缺陷是绘制bitmap尺寸不能直接拿到，需要反射获取SVGAVideoEntity的Images变量

建议能够有更友好的字号适配方案

**Comment by errnull** [comment]
你好，Dynamic Text 只提供最基本样式的文本替换，
可以使用：
fun setDynamicImage(bitmap: Bitmap, forKey: String) {
fun setDynamicDrawer(drawer: (canvas: Canvas, frameIndex: Int) -> Boolean, forKey: String) {
等 API 将自定义样式文本主动渲染，然后再替换进动效。
@fdh19979
