### ISSUE TITLE
Android端现在支持添加多SVGARange播放吗？

### ISSUE THREAD

**Issue by truyayong** [svga/SVGAPlayer-Android#199]
Android端现在支持添加多SVGARange播放吗，就像web端的
`player.startAnimationWithRangeList([{
        location: 0,
        length: 20
      }, {
        location: 130,
        length: 130
      }]);`
若不支持是因为什么呢，有什么坑吗

**Comment by PonyCui** [comment]
其实这个 range 的实现并不难，开发者可以自行封装实现的。
