### ISSUE TITLE
加载assets 目录下svga感觉有点慢

### ISSUE THREAD

**Issue by HeroZ-Dodge** [svga/SVGAPlayer-Android#2]
如题，我在assets 目录下放置了两个svga文件，大小是200 - 300 左右，设置了两个按钮用来加载这两个动画，点击按钮加载的时候，或者切换的是，能感觉到明显的延迟，请问这个情况是否正常

**Comment by PonyCui** [comment]
这个延迟有多久，具体还需要看动画脚本是否特别复杂，一般来说，纯位图的动画，加载和播放性能都是最好的。
