### ISSUE TITLE
AE2020 export error

### ISSUE THREAD

**Issue by HiCatcat** [svga/SVGAPlayer-Android#200]
When using AE2020 export, the following popup window will appear.

![1](https://user-images.githubusercontent.com/57614500/69510063-4962f100-0f76-11ea-9285-3ec83a73ce2c.png)

![2](https://user-images.githubusercontent.com/57614500/69510068-4ec03b80-0f76-11ea-9a16-9a1b6c3fed8f.png)

**Comment by errnull** [comment]
将会支持。
关注： https://github.com/svga/SVGA-AEConverter/issues/11
