### ISSUE TITLE
Android M开始支持StaticLayout setMaxLine

### ISSUE THREAD

**Issue by chenhuiming** [svga/SVGAPlayer-Android#202]
SVGACanvasDrawer
dynamicLayoutText
var layout = StaticLayout(it.text, 0, it.text.length, it.paint, drawingBitmap.width, it.alignment, it.spacingMultiplier, it.spacingAdd, false)
可以支持下StaticLayout设置maxLine，常用的应用场景需要。
Android M开始支持StaticLayout setMaxLine
-》
val staticLayout1 = if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.M) {
                      StaticLayout.Builder.obtain(guardTextBuilder, 0, guardTextBuilder.length, textPaint, generateGuardView.width)
                            .setAlignment(Layout.Alignment.ALIGN_NORMAL)
                            .setEllipsize(TextUtils.TruncateAt.MIDDLE)
                            .setLineSpacing(0.0f, 1.0f)
                            .setIncludePad(false)
                            .setMaxLines(2).build()
                } else {
                      StaticLayout(guardTextBuilder, 0, guardTextBuilder.length,
                              textPaint, generateGuardView.width,
                            Layout.Alignment.ALIGN_NORMAL,
                            1.0f, 0.0f,
                            false,
                            TextUtils.TruncateAt.MIDDLE, 3)
                }

**Comment by PonyCui** [comment]
https://github.com/yyued/SVGAPlayer-Android/commit/8c6a43caa25c2979bc6e0861707184a77001c83f
