### ISSUE TITLE
OOM问题

### ISSUE THREAD

**Issue by lylylywww** [svga/SVGAPlayer-Android#209]
OOM  issues 
when i click the gift button ,do'not stop for about 300 times ,the system crash
this is the error code
parser.decodeFromURL(url, new SVGAParser.ParseCompletion() {
                @Override
                public void onComplete(SVGAVideoEntity svgaVideoEntity) {
                    SVGADrawable drawable = new SVGADrawable(svgaVideoEntity);
                    svgaImageView.setImageDrawable(drawable);
                    svgaImageView.startAnimation();
                   // svgaImageView.setClearsAfterStop(true);
                }
this is the Log 
Process: com.wasxxx.xx.live, PID:28491
java.lang.outOfMemoryError; pthread_create(1040KB stack) failed: try again
at java.lang.thread.nativeCreate(native method)
at java.lang.thread.start(Thread.java:753)
at com.opensource.svgaplayer.SVGAParser$FileDownloader.resume(SVGAParser.kt:78)
at com.opensource.svgaplayer.SVGAParser.decodeFromURL(SVGAParser.kt:111)
at com.xxx.app.live.view.gift.SvgaView.startAnimFirst(SvgaView.java:185)

the question is what should i do to avoid oom in that code?  thank you a lot

**Comment by lylylywww** [comment]
implementation 'com.github.yyued:SVGAPlayer-Android:2.4.4'

**Comment by liuleshuai** [comment]
升级2.5.2-beta试试吧，代码里catch住了

**Comment by errnull** [comment]
See #189
