### ISSUE TITLE
Parser 线程的使用问题

### ISSUE THREAD

**Issue by OrekieSun** [svga/SVGAPlayer-Android#212]
使用过程中发现每 new 一个 parser 都会创建一个 threadPool ，而文档里是这么推荐使用的：
![image](https://user-images.githubusercontent.com/19424042/71140425-2f05f580-224c-11ea-9738-f4f5342e0621.png)
并没有说及 Parser 的资源消耗，在动画运用密集的地方如果这么粗暴使用非常容易创建无数的无用线程池，建议能更新一下文档，声明一下这样使用的危险，并且建议对 parser 进行复用

**Comment by PonyCui** [comment]
是的，这需要说明一下。

**Comment by errnull** [comment]
你好，基于你的疑问有三点回答。
1. SVGAParser 中使用 threadPoolExecutor 是 `companion object`，<br>
**new** 出来 Parser 对象会共用一个线程池静态对象，<br>
所以不存在问题描述中的：`非常容易创建无数的无用线程池` 这种情况。
2. 频繁创建 Parser 对象确实会有额外的资源消耗，
而且构造函数传入的 context,
有可能在 Activity 销毁时还被强引用导致内存泄漏。
将提供一个 `shareParser(Context) ` 的 API 让开发者自行管理，
官方建议在 Application 中传入 context 并初始化，
这样子便不用考虑 Activity 销毁时的内存泄漏问题<br>
以及过多创建 Parser 消耗额外资源。
3. 通常使用 Executors 工厂方法配置线程池，<br>
将使用：`Executors.newCachedThreadPool()` 
让系统自行管理。
@OrekieSun

**Comment by errnull** [comment]
v2.5.3 中修复此 issue
