### ISSUE TITLE
不支持设置透明度吗？

### ISSUE THREAD

**Issue by Duosl** [svga/SVGAPlayer-Android#217]

**Comment by errnull** [comment]
支持，
可以关注一下AE特性表。
https://docs.qq.com/sheet/DT3Z2ektWRnZPaFJM?c=B29A0A0&tab=nrwudd
@Duosl

**Comment by Duosl** [comment]
@errnull 感谢回答！不知道用什么方式实现呢？

我这边看了一下源码，发现`SVGADrawable#setAlpha(Int) `的方法是一个空实现，用普通的`ImageView#setAlpha(Int)` 是无法实现的。

望指教，非常感谢！

**Comment by errnull** [comment]
你好，空实现是因为设置了 Alpha 会导致 Canvas 中部分值异常，
如果需要设置动效透明度，请在源文件中设置。
如果需要设置隐藏，可以使用 SVGADrawable#setVisibility
@Duosl

**Comment by Duosl** [comment]
嗯嗯 好的 @errnull  谢谢您了
我这边需要实现的是一个滑动的过渡效果，暂时没想到其他好的方式

**Comment by errnull** [comment]
在原来动效的基础上增加一段透明度动画可以解决吗？

**Comment by Duosl** [comment]
正在进行尝试中...

**Comment by PonyCui** [comment]
用另一个 View 包住 SVGAImageView，然后改变这个 View 的透明度就可以了。

**Comment by Duosl** [comment]
嗯嗯  @PonyCui 这个方案是可以的。我这边现在正是通过这种方式解决的。
@PonyCui  @errnull  非常感谢你们的帮助

**Comment by tangedegushi** [comment]
> @errnull 感谢回答！不知道用什么方式实现呢？
> 
> 我这边看了一下源码，发现`SVGADrawable#setAlpha(Int) `的方法是一个空实现，用普通的`ImageView#setAlpha(Int)` 是无法实现的。
> 
> 望指教，非常感谢！

可以通过view的setAlpha(float)设置
