### ISSUE TITLE
请提供一个 SVGAVideoEntity 占用内存大小的方式。

### ISSUE THREAD

**Issue by leoyuuu** [svga/SVGAPlayer-Android#225]
在使用 Svga 时我们会缓存一部分 SVGAVideoEntity 对象，使用缓存策略时我们希望可以获取到一个 SVGAVideoEntity 对象占用的内存大小，以此来确定我们是否需要移除该对象。
比如说 LruCache 时计算当前缓存的数据一共占用了多大的内存。

**Comment by PonyCui** [comment]
I think there's very difficult to provide a way to measure memory usage.

**Comment by leoyuuu** [comment]
I am not interest the total memory usage. I am interest in the bitmaps. cause somrtimes our UE may use woo many images in one svga file



---原始邮件---
发件人: "PonyCui"<notifications@github.com&gt;
发送时间: 2020年1月19日(周日) 上午10:14
收件人: "yyued/SVGAPlayer-Android"<SVGAPlayer-Android@noreply.github.com&gt;;
抄送: "刘煜"<1115144940@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题: Re: [yyued/SVGAPlayer-Android] 请提供一个 SVGAVideoEntity 占用内存大小的方式。 (#225)



I think there's very difficult to provide a way to measure memory usage.

**Comment by PonyCui** [comment]
The SVGAConverter already provide the memory usage tips, and you can check the memory usage with https://svga.io

**Comment by rauk123** [comment]
You can use java reflection. Like this
`
val imagesFiled: Field = videoEntity.javaClass.getDeclaredField("imageMap") 
 imagesFiled.isAccessible = true
 val images: HashMap<String, Bitmap> = imagesFiled.get(videoEntity) as HashMap<String, Bitmap>
 var total = 0f
 for (entry in images) {
      total += entry.value.height * entry.value.width * 4
 }
`
Then, we got total bytes~
