### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by markheyf** [svga/SVGAPlayer-Android#226]
val drawable = drawable as? SVGADrawable ?: return false 会出现点击事件无法响应

**Comment by PonyCui** [comment]
return false 相当于中断整个 method 的运行

**Comment by markheyf** [comment]
> return false 相当于中断整个 method 的运行

可以改成return super.onTouchEvent(event)吗？经测试return false 会出现点击事件无法响应

**Comment by PonyCui** [comment]
是的，这是需要改的。

**Comment by markheyf** [comment]
> 是的，这是需要改的。

麻烦改下重新更新个版本？

**Comment by markheyf** [comment]
val drawable = drawable as? SVGADrawable ?: return false 能改成 return super.onTouchEvent(event)？
