### ISSUE TITLE
无法动画位置置底问题

### ISSUE THREAD

**Issue by peihp** [svga/SVGAPlayer-Android#228]
发现必须设置android:layout_height="match_parent"，如果设置成android:layout_height="wrap_content"，动画就没法显示，所以想要把动画置底无法实现，研究了几天不知道怎么解决，烦请帮忙解答，万分感谢！

**Comment by PonyCui** [comment]
不支持 wrap_content

**Comment by peihp** [comment]
非常感谢帮忙解答，可以请问大佬您一下，如果要设置动画在屏幕最底部展示要怎么改呢？手机长屏幕情况下

**Comment by PonyCui** [comment]
scaleType

**Comment by peihp** [comment]
好的，非常感谢大佬！虽然有些动画离底部还有点距离，感谢浪费了您宝贵的时间答复！
