### ISSUE TITLE
大牛好:viewpager+fragment，每一页有一个svg，会卡顿吗？

### ISSUE THREAD

**Issue by OnlyYouMyLove** [svga/SVGAPlayer-Android#23]
大牛您好：
        我想问下是否有释放内存的API呢？我运行了下，发现开启关闭这样的重复，内存会不断升高，而且不会释放内存，求解。
        盼复

**Comment by PonyCui** [comment]
有一个地方存在内存泄露，在 master 分支已修复。

**Comment by PonyCui** [comment]
2.1.0 Release
