### ISSUE TITLE
HttpResponseCache.install（）崩溃

### ISSUE THREAD

**Issue by good-good-study** [svga/SVGAPlayer-Android#233]
HttpResponseCache.install(getExternalCacheDir(), 1024 * 1024 * 200);
在Debug版本时 没问题， 但是release版本的apk安装上运行后就崩溃（已配置混淆规则）

Caused by: java.lang.RuntimeException: Stub!  at a.a(HttpResponseCache.java:2)

**Comment by PonyCui** [comment]
https://github.com/yyued/SVGAPlayer-Android#proguard-rules

Add proguard rules.

**Comment by PonyCui** [comment]
有没有更具体的信息

**Comment by good-good-study** [comment]
没有， 就提示了Caused by: java.lang.RuntimeException: Stub! at a.a(HttpResponseCache.java:2) ， debug版本没问题，不知道因为啥

**Comment by good-good-study** [comment]
刚刚试了下， 只要去掉 HttpResponseCache.install(getExternalCacheDir(), 1024 * 1024 * 200); 这行代码就可以了， 但是我还想配置缓存该怎么整啊

**Comment by PonyCui** [comment]
getExternalCacheDir 换成 getCacheDir

**Comment by good-good-study** [comment]
还是不行，还是一样的错 ，debug版本一直没问题

**Comment by painld6** [comment]
https://stackoverflow.com/a/22014164
这种报错貌似和环境有关，确认下使用的环境有没有问题
