### ISSUE TITLE
潜在安全漏洞：ZipperDown解压路径穿越漏洞

### ISSUE THREAD

**Issue by dnsliu** [svga/SVGAPlayer-Android#234]
版本2.0.3，不知道后面修复了没有。

APK安全风险(API调用)：ZipperDown解压路径穿越漏洞 下方是具体项目和具体调用：
具体项目：
com/opensource/svgaplayer/SVGAParser.java
具体调用：
.getNextEntry()
修复建议: 请检查以上API调用，确认并修复该问题，修复建议如下： 在调用getName()函数获取解压文件名时，应检测路径中是否包含"../" , 使文件解压到期望的目录

**Comment by PonyCui** [comment]
You can submit a Pull Request, thank you!
