### ISSUE TITLE
svga循环播放，如果带声音，循环的时候声音会停顿两秒左右

### ISSUE THREAD

**Issue by Kuki93** [svga/SVGAPlayer-Android#235]
循环播放带声音的svga动画，每次循环声音不能平滑过渡，每次大概会停顿两秒

**Comment by Kuki93** [comment]
看源码是使用soundPool的播放的，只适合短促的音效

**Comment by painld6** [comment]
检查下 SVGA 内部是否使用短音频，目前是不支持长音频 #321
