### ISSUE TITLE
如果svga文件带声音的话，声音播放不全。感觉应该是因为svga文件中带有自定义素材

### ISSUE THREAD

**Issue by jjdy2006** [svga/SVGAPlayer-Android#241]
## Attention

* Do not ask any usage question, issue board is a issue board, accept library bugs only.
* If you are facing any usage problem, read the README again.

## Issue Template

Issue Description(What's your problem)

How To Reappear(How to reappear the issue)

Any Attachment(Provide a sample about your issue)

------ 中文分割线 ------

## 注意 

* 不要在 Issue 板块提问使用问题，Issue 板块只接受 Bug 反馈。
* 如果遇到使用上的问题，仔细阅读 README。

## Issue 模板

请尽量使用英文提交 Issue

请确切回答：问题的描述、重现方式、附件（提供一个 Demo 以重现问题）

**Comment by jjdy2006** [comment]
录了一个歌曲，大概也就三句，每次播放到自定义素材的时候，声音就断掉了

**Comment by jjdy2006** [comment]
问题找到了，是因为svga源码中使用的是soundpool播放的音频，它只能播放短暂的音频，希望作者能兼容mediaPlayer方式播放

**Comment by h-zhouwenjun** [comment]
你好，有解决么？

**Comment by painld6** [comment]
> 问题找到了，是因为svga源码中使用的是soundpool播放的音频，它只能播放短暂的音频，希望作者能兼容mediaPlayer方式播放

MediaPlayer 对于 SVGA 来说太重了，你可以选择把音频切分成短音频后在对应片段是播放
