### ISSUE TITLE
About SVGA mute (关于SVGA静音)

### ISSUE THREAD

**Issue by Felix1030** [svga/SVGAPlayer-Android#247]
Can you provide a way to turn off SVGA music
可否提供一个关闭SVGA音乐的方法

**Comment by PonyCui** [comment]
你可以自己 fork 一个分支出来，加上静音能力就可以了。

**Comment by tall-nuts** [comment]
借机插个楼，@PonyCui svga动画如果内置了音频，自动播放动画时会自动播放音频不需要额外调用api是么？

**Comment by PonyCui** [comment]
@pengfeigao 不需要

**Comment by iostyle** [comment]
我觉得这应该是一个基础功能，没有这个方法让我感到很意外。

**Comment by Khaos116** [comment]
+1

**Comment by 392354412** [comment]
请问添加静音功能了吗？

**Comment by iostyle** [comment]
https://github.com/iostyle/SVGAPlayer-Android

**Comment by iostyle** [comment]
https://github.com/iostyle/SVGAPlayer-Android
implementation 'com.github.iostyle:SVGAPlayer-Android:2.5.17'
我对decodeInputStream加了静音支持，有其他需要自己参考着改一下吧
