### ISSUE TITLE
fillMode没有效果

### ISSUE THREAD

**Issue by LQ74520** [svga/SVGAPlayer-Android#256]
- 
![1590401427(1)](https://user-images.githubusercontent.com/43640812/82803399-06e18900-9eb3-11ea-8df9-cf559219b452.jpg)
当播放完成一遍之后，并没有在最后静止，怎么回事儿啊？？？

**Comment by PonyCui** [comment]
Forward

**Comment by LQ74520** [comment]
> 向前

也一样不行，两个都试了的，效果是一样的，一遍播放完成之后，就消失了，就没了，没有静止

**Comment by zengke328** [comment]
> ![1590401427(1)](https://user-images.githubusercontent.com/43640812/82803399-06e18900-9eb3-11ea-8df9-cf559219b452.jpg)
> 当播放完成一遍之后，并没有在最后静止，怎么回事儿啊？？？

我也遇到相同需求，在onFinished()回调中，执行svga.pauseAnimation();可以实现

**Comment by LQ74520** [comment]
> > ![1590401427（1）](https://user-images.githubusercontent.com/43640812/82803399-06e18900-9eb3-11ea-8df9-cf559219b452.jpg)
> > 当播放完成一遍之后，并没有在最后静止，怎么回事儿啊？？？
> 
> 我也遇到相同需求，在onFinished（）局部中，执行svga.pauseAnimation（）;可以实现

还是一样的，onFinished里面设置了svga.pauseAnimation（）;还是一样的会完成之后清空画布，没有效果

**Comment by LQ74520** [comment]
> > ![1590401427（1）](https://user-images.githubusercontent.com/43640812/82803399-06e18900-9eb3-11ea-8df9-cf559219b452.jpg)
> > 当播放完成一遍之后，并没有在最后静止，怎么回事儿啊？？？
> 
> 我也遇到相同需求，在onFinished（）局部中，执行svga.pauseAnimation（）;可以实现

不对，是根本没有走onFinished这个回调，也没做其他操作呀，为啥没有走呢

**Comment by zengke328** [comment]
> > > ![1590401427（1）](https://user-images.githubusercontent.com/43640812/82803399-06e18900-9eb3-11ea-8df9-cf559219b452.jpg)
> > > 当播放完成一遍之后，并没有在最后静止，怎么回事儿啊？？？
> > 
> > 
> > 我也遇到相同需求，在onFinished（）局部中，执行svga.pauseAnimation（）;可以实现
> 
> 还是一样的，onFinished里面设置了svga.pauseAnimation（）;还是一样的会完成之后清空画布，没有效果

clearsAfterStop这个你设置成false试下

**Comment by LQ74520** [comment]
> > > > ![1590401427（1）](https://user-images.githubusercontent.com/43640812/82803399-06e18900-9eb3-11ea-8df9-cf559219b452.jpg)
> > > > 当播放完成一遍之后，并没有在最后静止，怎么回事儿啊？？？
> > > 
> > > 
> > > 我也遇到相同需求，在onFinished（）局部中，执行svga.pauseAnimation（）;可以实现
> > 
> > 
> > 还是一样的，onFinished里面设置了svga.pauseAnimation（）;还是一样的会完成之后清空画布，没有效果
> 
> clearsAfterStop这个你设置成false试下

![1590551533(1)](https://user-images.githubusercontent.com/43640812/82975989-8df84380-a010-11ea-89c7-a23381657f49.jpg)
  true  false都尝试了下的，都进不了那个onFinished的回调里面

**Comment by LQ74520** [comment]
> > > > ![1590401427（1）](https://user-images.githubusercontent.com/43640812/82803399-06e18900-9eb3-11ea-8df9-cf559219b452.jpg)
> > > > 当播放完成一遍之后，并没有在最后静止，怎么回事儿啊？？？
> > > 
> > > 
> > > 我也遇到相同需求，在onFinished（）局部中，执行svga.pauseAnimation（）;可以实现
> > 
> > 
> > 还是一样的，onFinished里面设置了svga.pauseAnimation（）;还是一样的会完成之后清空画布，没有效果
> 
> clearsAfterStop这个你设置成false试下

找到问题了，就xml里面设置一下就可以了的，不行的问题在svga上面，最后是空白的，或者是动画显示结束了，但是还没结束，期间是空白的
