### ISSUE TITLE
setDynamicImage(bitmap: Bitmap, forKey: String)无效

### ISSUE THREAD

**Issue by Adaclass** [svga/SVGAPlayer-Android#257]
if (toBmp != null) {
        dynamicEntity.setDynamicImage(toBmp, "bd_xdgb_yt"); // Here is the KEY implementation.
    }

if (null != bitmapToSeat) {
       dynamicEntity.setDynamicImage(bitmapToSeat, "img_2103112936");
}
同一个SVG里面两个地方设置，第一个有效，第二个无效，这个方法有监听事件吗

**Comment by painld6** [comment]
是在 ParseCompletion#onComplete 中设置的吗？

**Comment by painld6** [comment]
而且对应的 key 是 svga 文件内部定义好的 key，不是随便设置的
