### ISSUE TITLE
能否提供纯java版本，因为Kotlin在apk合入固件编译的时候会有odex优化问题、

### ISSUE THREAD

**Issue by zhongzixing** [svga/SVGAPlayer-Android#259]
17:54:45 dex2oatd F 06-06 17:54:43 84301 84301 method_verifier.cc:5278] Verification error in int kotlin.UByte.compareTo(java.lang.Object)
17:54:45 dex2oatd F 06-06 17:54:43 84301 84301 method_verifier.cc:5278] int kotlin.UByte.compareTo(java.lang.Object) failed to verify: int kotlin.UByte.compareTo(java.lang.Object): [0x6] invoke-super/virtual can't be used on private method int kotlin.UByte.compareTo-7apg3OU(byte)
17:54:45 dex2oatd F 06-06 17:54:43 84301 84301 method_verifier.cc:5278] 
17:54:45 dex2oatd F 06-06 17:54:43 84301 84301 method_verifier.cc:5278] Verification error in int kotlin.UInt.compareTo(java.lang.Object)
17:54:45 dex2oatd F 06-06 17:54:43 84301 84301 method_verifier.cc:5278] int kotlin.UInt.compareTo(java.lang.Object) failed to verify: int kotlin.UInt.compareTo(java.lang.Object): [0x6] invoke-super/virtual can't be used on private method int kotlin.UInt.compareTo-WZ4Q5Ns(int)
17:54:45 dex2oatd F 06-06 17:54:43 84301 84301 method_verifier.cc:5278] 
17:54:45 dex2oatd F 06-06 17:54:43 84301 84301 method_verifier.cc:5278] Verification error in int kotlin.ULong.compareTo(java.lang.Object)
17:54:45 dex2oatd F 06-06 17:54:43 84301 84301 method_verifier.cc:5278] int kotlin.ULong.compareTo(java.lang.Object) failed to verify: int kotlin.ULong.compareTo(java.lang.Object): [0x6] invoke-super/virtual can't be used on private method int kotlin.ULong.compareTo-VKZWuLQ(long)
17:54:45 dex2oatd F 06-06 17:54:43 84301 84301 method_verifier.cc:5278] 
17:54:45 dex2oatd F 06-06 17:54:43 84301 84301 method_verifier.cc:5278] Verification error in int kotlin.UShort.compareTo(java.lang.Object)
17:54:45 dex2oatd F 06-06 17:54:43 84301 84301 method_verifier.cc:5278] int kotlin.UShort.compareTo(java.lang.Object) failed to verify: int kotlin.UShort.compareTo(java.lang.Object): [0x6] invoke-super/virtual can't be used on private method int kotlin.UShort.compareTo-xj2QHRw(short)
17:54:45 dex2oatd F 06-06 17:54:43 84301 84301 method_verifier.cc:5278] 
17:54:45 dex2oatd F 06-06 17:54:45 84301 84301 compiler_driver.cc:907] Had a hard failure verifying all classes, and was asked to abort in such situations. Please check the log.
17:54:45 error: out/target/product/qssi/obj/APPS/Browser_intermediates/dexpreopt.sh:25 exited with status 1
17:54:45 error in command:

**Comment by PonyCui** [comment]
把 Kotlin 重新翻译成 Java 吧，代码量不算很大。
