### ISSUE TITLE
同一个svga文件，在部分机型上会出现 EOFException

### ISSUE THREAD

**Issue by androidCircle** [svga/SVGAPlayer-Android#260]
###  java.io.EOFException
 okio.Buffer.require(Buffer.java:109)
 com.squareup.wire.ProtoReader.readFixed32(ProtoReader.java:355)
 com.squareup.wire.ProtoAdapter$10.decode(ProtoAdapter.java:357)
 com.squareup.wire.ProtoAdapter$10.decode(ProtoAdapter.java:347)
 com.opensource.svgaplayer.proto.Transform$ProtoAdapter_Transform.decode(Transform.java:232)
 com.opensource.svgaplayer.proto.Transform$ProtoAdapter_Transform.decode(Transform.java:199)
 com.opensource.svgaplayer.proto.FrameEntity$ProtoAdapter_FrameEntity.decode(FrameEntity.java:241)
 com.opensource.svgaplayer.proto.FrameEntity$ProtoAdapter_FrameEntity.decode(FrameEntity.java:208)
 com.opensource.svgaplayer.proto.SpriteEntity$ProtoAdapter_SpriteEntity.decode(SpriteEntity.java:157)
 com.opensource.svgaplayer.proto.SpriteEntity$ProtoAdapter_SpriteEntity.decode(SpriteEntity.java:131)
 com.opensource.svgaplayer.proto.MovieEntity$ProtoAdapter_MovieEntity.decode(MovieEntity.java:219)
 com.opensource.svgaplayer.proto.MovieEntity$ProtoAdapter_MovieEntity.decode(MovieEntity.java:185)
 com.squareup.wire.ProtoAdapter.decode(ProtoAdapter.java:203)
 com.squareup.wire.ProtoAdapter.decode(ProtoAdapter.java:185)
 com.opensource.svgaplayer.SVGAParser.parse(SVGAParser.kt:203)
 com.opensource.svgaplayer.SVGAParser.access$parse(SVGAParser.kt:23)
 com.opensource.svgaplayer.SVGAParser$parse$3.invoke(SVGAParser.kt:99)
 com.opensource.svgaplayer.SVGAParser$parse$3.invoke(SVGAParser.kt:23)
 com.opensource.svgaplayer.SVGAParser$FileDownloader$resume$1.run(SVGAParser.kt:59)
 java.lang.Thread.run(Thread.java:919)

**Comment by painld6** [comment]
请问是哪些机型出现这个问题？知道 Android 的版本号码？
