### ISSUE TITLE
线程池问题

### ISSUE THREAD

**Issue by boundaryforever** [svga/SVGAPlayer-Android#261]
1.线程池采用 Executors.newCachedThreadPool()，当同时操作比较多的时候也会出现内存问题！可否采用固定数量，限制最多是多少个！

**Comment by daishengda2018** [comment]
在此场景下 newCachedThreadPool 是应对快速解析资源的，任何解析的任务都会立即得到响应，如果采用常规手法肯定是要有缓冲队列，让任务排队等待处理得不到及时响应。在这种角度看 newCachedThreadPool  是合理的。
对于你提到的内存问题，只有超密集的创建成百上千的线程时，才会有OOM的可能性，但是这对于App来说这是极其少见且不正常的。如果出现了这么高的并发性，请将矛头指向使用场景与方式。

对此我认为：不用担心 newCachedThreadPool 潜在问题，这在 SVGA 这种场景下几乎不可能发生，而且最终创建的线程可能就那几个，不会太大规模。如果你的场景对实时性要求不高或者有着自己的考虑，可以自行通过 SVGAParser.setThreadPoolExecutor() 实现自己的线程池。

但是有一点是需要改进的：给线程池中的每个线程命名。
