### ISSUE TITLE
可否支持svga文件路径是raw目录

### ISSUE THREAD

**Issue by XZQ** [svga/SVGAPlayer-Android#269]
我把svga文件放到工程的raw目录，可否根据资源ID来访问？  Bigo员工xiazhiqiang@bigo.sg

**Comment by PonyCui** [comment]
你可以自行封装一下，使用 https://github.com/svga/SVGAPlayer-Android/wiki/APIs#parseinputstream-inputstream-cachekey-string-callback-parsecompletion-closeinputstream-boolean--false InputStream 传入就可以了
