### ISSUE TITLE
某些svga加载时会出现没有走onComplete和onError的问题

### ISSUE THREAD

**Issue by FzQ1940523** [svga/SVGAPlayer-Android#272]
## Attention

* Do not ask any usage question, issue board is a issue board, accept library bugs only.
* If you are facing any usage problem, read the README again.

## Issue Template

Issue Description(What's your problem)

How To Reappear(How to reappear the issue)

Any Attachment(Provide a sample about your issue)

------ 中文分割线 ------

## 注意 

* 不要在 Issue 板块提问使用问题，Issue 板块只接受 Bug 反馈。
* 如果遇到使用上的问题，仔细阅读 README。

## Issue 模板

请尽量使用英文提交 Issue

请确切回答：问题的描述、重现方式、附件（提供一个 Demo 以重现问题）

**Comment by boboxiaodd** [comment]
我怀疑是和声音播放有关
https://stackoverflow.com/a/45088851
但我不会改 :(

**Comment by painld6** [comment]
建议使用下新版本 2.5.14 试试看
