### ISSUE TITLE
svga 到输入字节流异常 

### ISSUE THREAD

**Issue by zzh-xhz** [svga/SVGAPlayer-Android#276]
## Attention

* Do not ask any usage question, issue board is a issue board, accept library bugs only.
* If you are facing any usage problem, read the README again.

## Issue Template

Issue Description(What's your problem)

How To Reappear(How to reappear the issue)

Any Attachment(Provide a sample about your issue)

------ 中文分割线 ------

## 注意 

* 不要在 Issue 板块提问使用问题，Issue 板块只接受 Bug 反馈。
* 如果遇到使用上的问题，仔细阅读 README。

## Issue 模板

请尽量使用英文提交 Issue

请确切回答：问题的描述、重现方式、附件（提供一个 Demo 以重现问题）
ng**
![image](https://user-images.githubusercontent.com/54203806/88509391-8d315d00-d013-11ea-83cf-414cc8a82caa.png)

![image](https://user-images.githubusercontent.com/54203806/88509395-90c4e400-d013-11ea-8dab-d06e0e0cd3d7.png)

**Comment by painld6** [comment]
请问用的是哪个版本呢？以及能否提供下相关 demo 或 svga 文件？
