### ISSUE TITLE
v2.5.5+ 版本后，能否让调用方自行决定在SVGAImageVie#onDetachedFromWindow时，是否需要释放资源？

### ISSUE THREAD

**Issue by Duosl** [svga/SVGAPlayer-Android#279]
**问题描述：**
我司基于SVGA组件封装了一个常用组件，需要在页面下拉刷新后，可以直接重新播放SVGA，而不希望重新解析和重新加载SVGA资源，在v2.5.3版本运行正常，但在v2.5.5后，下拉刷新后，SVGA就消失不见了，通过阅读源码发现，在SVGAImageVie#onDetachedFromWindow时，SVGA资源以及被清空了，所以导致我司组件不能正常使用。

**修改建议：**
可否通过新增一个flag，让调用方自行决定是否需要在SVGAImageVie#onDetachedFromWindow时，是否需要释放SVGA资源，并允许调用方自行管理相关SVGAVideoEntity，方便实现自己的缓存策略

**Comment by youxiachai** [comment]
@Duosl 你不把view remove掉,不就不会调onDetachedFromWindow....

**Comment by Duosl** [comment]
@youxiachai 因为我司这个组件会用在RecyclerView中，布局是会被复用的，所以这个onDetachedFromWindow 不太受我们控制

**Comment by youxiachai** [comment]
@Duosl 感觉你们这个组件实现有点问题...按道理而言如果是RV, view复用不就重新加载了,这个时候onDetachedFromWindow 你控制不控制也不重要啊
毕竟都重新加载了....这个时候你还控制不了?
可能没理解到,我只是提下自己的疑问,可能理解错了..

**Comment by Duosl** [comment]
@youxiachai  不好意思，我没有解释清楚。这个组件内部实现了一些小的缓存策略，如果数据相同的话，组件内部就不会重新解析SVGA数据了，在这种情况下（svga资源不变），我们是可以直接进行SVGA的播放，而不需要重新进行资源解析。（我们项目SVGA用的比较多，频繁解析的话也是比较耗费资源的）。
新版本(v2.5.5)每次detach时，强制释放了内存，这也会导致我们缓存失效，所以希望能够将detach时，是否释放资源的决定权交给开发者。

**Comment by lazy2b** [comment]
我也是类似情况。目前只能自己fork代码修改实现了。可以参考下：https://github.com/lazy2b/SVGAPlayer-Android/tree/2.5.8.local.cache

**Comment by lazy2b** [comment]
> @youxiachai 不好意思，我没有解释清楚。这个组件内部实现了一些小的缓存策略，如果数据相同的话，组件内部就不会重新解析SVGA数据了，在这种情况下（svga资源不变），我们是可以直接进行SVGA的播放，而不需要重新进行资源解析。（我们项目SVGA用的比较多，频繁解析的话也是比较耗费资源的）。
> 新版本(v2.5.5)每次detach时，强制释放了内存，这也会导致我们缓存失效，所以希望能够将detach时，是否释放资源的决定权交给开发者。

直接引用2.5.10，已经开放了clear添加了clearsAfterDetached标记。
