### ISSUE TITLE
作为ImageView使用，onTouchEvent拦截了事件

### ISSUE THREAD

**Issue by iostyle** [svga/SVGAPlayer-Android#281]
@SuppressLint("ClickableViewAccessibility")
    override fun onTouchEvent(event: MotionEvent?): Boolean {
        if (event?.action != MotionEvent.ACTION_DOWN) {
            return super.onTouchEvent(event)
        }
        val drawable = getSVGADrawable() ?: return false
        for ((key, value) in drawable.dynamicItem.mClickMap) {
            if (event.x >= value[0] && event.x <= value[2] && event.y >= value[1] && event.y <= value[3]) {
                mItemClickAreaListener?.let {
                    it.onClick(key)
                    return true
                }
            }
        }
        return super.onTouchEvent(event)
    }

如果不是SVGADrawable直接return，如果设置普通图片的话将不再响应点击事件，建议将return后面的代码加一个非空判断比较合适

**Comment by chenyunecjtu** [comment]
楼主解决了吗

**Comment by iostyle** [comment]
> 楼主解决了吗

先暂时通过两个控件切换吧

**Comment by Liuyyf** [comment]
可以在外面包一层, 让外层响应点击事件

**Comment by iostyle** [comment]
@painld6 release
