### ISSUE TITLE
NullPointerException 异常！！！

### ISSUE THREAD

**Issue by OBaKai** [svga/SVGAPlayer-Android#284]
![image](https://user-images.githubusercontent.com/24663585/89849839-f9879100-dbbb-11ea-9fc7-e5d10d3eb698.png)

由于上边传入的loop为null的情况下，会导致空指针。

![image](https://user-images.githubusercontent.com/24663585/89849859-03a98f80-dbbc-11ea-85cd-1566275b8017.png)

为啥要用context去拿looper
能改成直接用Loop.getMainLooper()的吧。

**Comment by df13954** [comment]
遇到同样问题，现在10几个奔溃

**Comment by painld6** [comment]
> 遇到同样问题，现在10几个奔溃

试下新版本？如果仍有问题可以提下 issue

**Comment by df13954** [comment]
使用新版本之后，没有发生过这个空指针问题了。应该是修复了。
