### ISSUE TITLE
v2.5.3之后的版本在RecyclerView上面不能复用SVGAVideoEntity吗？

### ISSUE THREAD

**Issue by lazy2b** [svga/SVGAPlayer-Android#287]
使用场景：直播类应用礼物列表。
核心代码如下：//每次点击选中开始播放，离开后显示最后一帧。
if (oldPosition != -1) {
            getAdapter().notifyItemChanged(oldPosition);
        }
        if (newPosition != -1) {
            getAdapter().notifyItemChanged(newPosition);
        }
下图为onBindViewHolder内部代码
![image](https://user-images.githubusercontent.com/8064190/90123714-de6e7a00-dd91-11ea-83a3-abeaee8c800e.png)
下图为全部点击播放后的效果
![image](https://user-images.githubusercontent.com/8064190/90124221-9ef45d80-dd92-11ea-8ec0-5005681a56bf.png)
经验证：
1 单独在一个Fragment里面使用SVGAImageView播放不同的svga远程文件在设置clearAfterStop=false之后是可以复用Entity的，设置clearAfterStop=true则不行。
2 在RecyclerView中怎么设置都是上图的结果，如果每次都重新用decodeFromURL加载就可以正常显示，但是效率和用户体验不好。

**Comment by lazy2b** [comment]
在v2.5.3之前的版本这样实现是没有问题的。就是播放过多会OOM和变卡。

**Comment by zfnian** [comment]
我也遇到这个问题了，缓存的  SVGAVideoEntity 使用后无效，这是为啥啊？

**Comment by lazy2b** [comment]
> 我也遇到这个问题了，缓存的 SVGAVideoEntity 使用后无效，这是为啥啊？

因为SVGAImageView里面在onDetachToWindow里面自动调用了clear().里面把entity也自动clear了。目前没办法我自己fork了一个分支修改这些逻辑。你可以参考下:https://github.com/lazy2b/SVGAPlayer-Android/tree/2.5.8.local.cache

**Comment by zfnian** [comment]
好的，多谢

> > 我也遇到这个问题了，缓存的 SVGAVideoEntity 使用后无效，这是为啥啊？
> 
> 因为SVGAImageView里面在onDetachToWindow里面自动调用了clear().里面把entity也自动clear了。目前没办法我自己fork了一个分支修改这些逻辑。你可以参考下:https://github.com/lazy2b/SVGAPlayer-Android/tree/2.5.8.local.cache

**Comment by lazy2b** [comment]
> 好的，多谢
> 
> > > 我也遇到这个问题了，缓存的 SVGAVideoEntity 使用后无效，这是为啥啊？
> > 
> > 
> > 因为SVGAImageView里面在onDetachToWindow里面自动调用了clear().里面把entity也自动clear了。目前没办法我自己fork了一个分支修改这些逻辑。你可以参考下:https://github.com/lazy2b/SVGAPlayer-Android/tree/2.5.8.local.cache

大佬们已经合并我的代码了。可以直接引用2.5.10

**Comment by liuchenc** [comment]
我使用的版本是2.5.8的,在RecyclerView中无法复用显示,请问怎么解决?

**Comment by zfnian** [comment]
把github上svga的代码clone下来，改下面这里就行了







------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "svga/SVGAPlayer-Android"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年12月30日(星期三) 下午3:38
收件人:&nbsp;"svga/SVGAPlayer-Android"<SVGAPlayer-Android@noreply.github.com&gt;;
抄送:&nbsp;"Messi赵丰年"<582021237@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [svga/SVGAPlayer-Android] v2.5.3之后的版本在RecyclerView上面不能复用SVGAVideoEntity吗？ (#287)





 
我使用的版本是2.5.8的,在RecyclerView中无法复用显示,请问怎么解决?

**Comment by liuchenc** [comment]
请问改哪里啊?

**Comment by chenxi2035** [comment]
同样请问改在哪里？

**Comment by painld6** [comment]
如果是旧版本，删除掉源码中 SVGAImageView 中 onDetachToWindow 中的 clear 相关方法即可

**Comment by lazy2b** [comment]
> 请问改哪里啊?
示例如下：

`
public class GiftAdapter extends RecyclerView.Adapter<GiftAdapter.GiftViewHolder> {
    private Map<Gift, SVGAVideoEntity> giftMap = new HashMap<>();

    @Override
    public void onBindViewHolder(@NonNull GiftViewHolder holder, int position) {
        Gift gift = getItem(position);
        holder.svgaImageView.setClearsAfterDetached(false);
        SVGAVideoEntity entity = giftMap.get(gift);
        if (entity == null) {
            SVGAParser parser = new SVGAParser(holder.svgaImageView.getContext());
            try {
                parser.decodeFromURL(new URL(gift.svgaUrl), new SVGAParser.ParseCompletion() {
                    @Override
                    public void onComplete(@NonNull SVGAVideoEntity svgaVideoEntity) {
                        giftMap.put(gift, svgaVideoEntity);
                        holder.svgaImageView.setVideoItem(svgaVideoEntity);
                        holder.svgaImageView.startAnimation();
                    }

                    @Override
                    public void onError() {

                    }
                });
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        } else {
            holder.svgaImageView.setVideoItem(entity);
            holder.svgaImageView.startAnimation();
        }

    }

    public void clearSvgaCache() {
        for (SVGAVideoEntity entity : giftMap.values()) {
            entity.clear();
        }
        giftMap.clear();
    }

    static class GiftViewHolder extends RecyclerView.ViewHolder {

        private SVGAImageView svgaImageView;

        public GiftViewHolder(@NonNull View itemView) {
            super(itemView);
            svgaImageView = itemView.findViewById(R.id._gift);
        }
    }
}
`

**Comment by chenxi2035** [comment]
> > 请问改哪里啊?
> > 示例如下：
> 
> `
> public class GiftAdapter extends RecyclerView.Adapter<GiftAdapter.GiftViewHolder> {
> private Map<Gift, SVGAVideoEntity> giftMap = new HashMap<>();
> 
> ```
> @Override
> public void onBindViewHolder(@NonNull GiftViewHolder holder, int position) {
>     Gift gift = getItem(position);
>     holder.svgaImageView.setClearsAfterDetached(false);
>     SVGAVideoEntity entity = giftMap.get(gift);
>     if (entity == null) {
>         SVGAParser parser = new SVGAParser(holder.svgaImageView.getContext());
>         try {
>             parser.decodeFromURL(new URL(gift.svgaUrl), new SVGAParser.ParseCompletion() {
>                 @Override
>                 public void onComplete(@NonNull SVGAVideoEntity svgaVideoEntity) {
>                     giftMap.put(gift, svgaVideoEntity);
>                     holder.svgaImageView.setVideoItem(svgaVideoEntity);
>                     holder.svgaImageView.startAnimation();
>                 }
> 
>                 @Override
>                 public void onError() {
> 
>                 }
>             });
>         } catch (MalformedURLException e) {
>             e.printStackTrace();
>         }
>     } else {
>         holder.svgaImageView.setVideoItem(entity);
>         holder.svgaImageView.startAnimation();
>     }
> 
> }
> 
> public void clearSvgaCache() {
>     for (SVGAVideoEntity entity : giftMap.values()) {
>         entity.clear();
>     }
>     giftMap.clear();
> }
> 
> static class GiftViewHolder extends RecyclerView.ViewHolder {
> 
>     private SVGAImageView svgaImageView;
> 
>     public GiftViewHolder(@NonNull View itemView) {
>         super(itemView);
>         svgaImageView = itemView.findViewById(R.id._gift);
>     }
> }
> ```
> 
> }
> `

谢谢~

**Comment by lazy2b** [comment]
> 请问改哪里啊?

写了个简单示例，看上面回复。

**Comment by chenxi2035** [comment]
@lazy2b 已经看到了~我是说谢谢~~~
