### ISSUE TITLE
2.5.3版本及之前可成功播放，2.5.3之后无法成功播放，某些svg需要设置loopCount>1才能播放

### ISSUE THREAD

**Issue by Dengszzzzz** [svga/SVGAPlayer-Android#288]
2.5.3版本及之前可成功播放，2.5.3之后无法成功播放，
从下载的缓存里取出，放到SVGA.IO 网站上可正常播放。
2.5.3之后  loopCount=1无法播放，loopCount>1可播放

svg文件：http://pic.yyxingqiu.com/svgtest.zip

**Comment by Dengszzzzz** [comment]
https://github.com/Dengszzzzz/DAndroid_kt/blob/master/test.zip

**Comment by painld6** [comment]
可以对 SVGAImageView 设置 clearsAfterStop = false，默认播放完后清除，所以需要设置 false 保留解析后的文件

至于为什么需要设置 loopCount > 1，看了下你提交的 svga 文件中有两份描述动画文件，就是这个导致解析后触发了两次播放，但因为 loopCount = 1，所以看起来是没有 SVGAImageView 没有触发播放，实际上是次数用完了导致播放已经停止了
