### ISSUE TITLE
targetSdkVersion 29，部分Android Q的手机无法显示动效

### ISSUE THREAD

**Issue by FzQ1940523** [svga/SVGAPlayer-Android#289]
## Attention

* Do not ask any usage question, issue board is a issue board, accept library bugs only.
* If you are facing any usage problem, read the README again.

## Issue Template

Issue Description(What's your problem)

How To Reappear(How to reappear the issue)

Any Attachment(Provide a sample about your issue)

------ 中文分割线 ------

## 注意 

* 不要在 Issue 板块提问使用问题，Issue 板块只接受 Bug 反馈。
* 如果遇到使用上的问题，仔细阅读 README。

## Issue 模板

请尽量使用英文提交 Issue

请确切回答：问题的描述、重现方式、附件（提供一个 Demo 以重现问题）

**Comment by jialiningjialining** [comment]
你遇见的哪些型号的手机呢？

**Comment by FzQ1940523** [comment]
> 你遇见的哪些型号的手机呢？

targetSdk 29   
用户手机系统 Android Q
问题：无论是本地的svga文件，还是网络加载的资源，都无法显示
部分机型：
CPH1911
SM-J810F
SM-J810G
STK-L21
Mi 9T
HMA-L29

**Comment by painld6** [comment]
> > 你遇见的哪些型号的手机呢？
> 
> targetSdk 29
> 用户手机系统 Android Q
> 问题：无论是本地的svga文件，还是网络加载的资源，都无法显示
> 部分机型：
> CPH1911
> SM-J810F
> SM-J810G
> STK-L21
> Mi 9T
> HMA-L29

用的是什么版本？

**Comment by FzQ1940523** [comment]
用的2.5.3，后来换了2.5.11也有这个问题



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Tobi <notifications@github.com&gt;
发送时间: 2020年9月22日 19:59
收件人: svga/SVGAPlayer-Android <SVGAPlayer-Android@noreply.github.com&gt;
抄送: Zzz <825554486@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[svga/SVGAPlayer-Android] targetSdkVersion 29，部分Android Q的手机无法显示动效 (#289)





   
你遇见的哪些型号的手机呢？
  
targetSdk 29
 用户手机系统 Android Q
 问题：无论是本地的svga文件，还是网络加载的资源，都无法显示
 部分机型：
 CPH1911
 SM-J810F
 SM-J810G
 STK-L21
 Mi 9T
 HMA-L29
  
用的是什么版本？

**Comment by painld6** [comment]
> 用的2.5.3，后来换了2.5.11也有这个问题 发自我的iPhone
> […](#)
> ------------------ 原始邮件 ------------------ 发件人: Tobi <notifications@github.com&gt; 发送时间: 2020年9月22日 19:59 收件人: svga/SVGAPlayer-Android <SVGAPlayer-Android@noreply.github.com&gt; 抄送: Zzz <825554486@qq.com&gt;, Author <author@noreply.github.com&gt; 主题: 回复：[svga/SVGAPlayer-Android] targetSdkVersion 29，部分Android Q的手机无法显示动效 (#289) 你遇见的哪些型号的手机呢？ targetSdk 29 用户手机系统 Android Q 问题：无论是本地的svga文件，还是网络加载的资源，都无法显示 部分机型： CPH1911 SM-J810F SM-J810G STK-L21 Mi 9T HMA-L29 用的是什么版本？ — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

尝试下 2.5.9，如果仍然不行的话，希望能提供个会出问题 svga 文件给到这边测试下 : )

**Comment by FzQ1940523** [comment]
好的👌。但是出问题的时候，是所有的svga都不行，并不是单个svga 的问题



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Tobi <notifications@github.com&gt;
发送时间: 2020年9月22日 20:15
收件人: svga/SVGAPlayer-Android <SVGAPlayer-Android@noreply.github.com&gt;
抄送: Zzz <825554486@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[svga/SVGAPlayer-Android] targetSdkVersion 29，部分Android Q的手机无法显示动效 (#289)





  
用的2.5.3，后来换了2.5.11也有这个问题 发自我的iPhone
 …
 ------------------ 原始邮件 ------------------ 发件人: Tobi <notifications@github.com&gt; 发送时间: 2020年9月22日 19:59 收件人: svga/SVGAPlayer-Android <SVGAPlayer-Android@noreply.github.com&gt; 抄送: Zzz <825554486@qq.com&gt;, Author <author@noreply.github.com&gt; 主题: 回复：[svga/SVGAPlayer-Android] targetSdkVersion 29，部分Android Q的手机无法显示动效 (#289) 你遇见的哪些型号的手机呢？ targetSdk 29 用户手机系统 Android Q 问题：无论是本地的svga文件，还是网络加载的资源，都无法显示 部分机型： CPH1911 SM-J810F SM-J810G STK-L21 Mi 9T HMA-L29 用的是什么版本？ — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.
  
尝试下 2.5.9，如果仍然不行的话，希望能提供个会出问题 svga 文件给到这边测试下 : )

**Comment by XuWei0205** [comment]
遇到了相同的问题，使用的是2.5.6，android Q在播放完部分有音频的SVGA之后后面的SVGA有一定概率无法播放

**Comment by fdh19979** [comment]
我也遇到类似的问题，海外用户反馈无法观看动效
最终找到了问题所在
应用启动的时候重置一下动画缩放时间就可以了
https://github.com/svga/SVGAPlayer-Android/issues/314
