### ISSUE TITLE
只有声音的svga播放地址，有的时候可以播放，有的时候不能播放

### ISSUE THREAD

**Issue by Datcon** [svga/SVGAPlayer-Android#291]
已升级至2.5.8
http://img2.ylike.com/media/music.10.svga

**Comment by lazy2b** [comment]
可以尝试下我新fork的代码分支
https://github.com/lazy2b/SVGAPlayer-Android/tree/2.5.8.local.cache
1 SVGAParser.kt 添加缓存SVGA文件到本地的扩展[SVGACache.kt]
  调用示例:在Application.onCreate()里面,SVGACache.onCreate(this,SVGACache.Type.File)即会在decodeFromURL
  里面自动处理缓存逻辑
2 SVGADrawable.kt SVGAImageView.kt SVGAVideoEntity.kt 公开clear()方法.
3 SVGAImageView.kt 添加clearsAfterDetached,默认true,不影响原来功能呢,用于控制imageview在onDetach的时候是否
  要自动调用clear().暂时为需要给RecyclerView缓存drawable或者entity的人士提供临时解决方案.用完记得调用clear()!!!!!!!
4 SVGAVideoEntity.kt generateAudioFileMap 方法每次打开同一个文件会解压一次mp3.缓存文件夹会越来越大.改为固定名字.
5 SVGAVideoEntity.kt 里面soundPool如果解析时load同一个svga的声音文件会出现无回调的情况,导致这里的callback不执行,
  原因暂时未知.目前解决方案是公开imageview,drawable,entity的clear(),然后在播放带声音的svgaimageview处,
  把解析完的drawable或者entity缓存下来,下次直接播放.用完再调用clear()!!!!!!!没有声音的不存在此问题.
  (真实场景如下:持续以队列形式播放同一个带声音的svga,由于2.5.8自动clear(),且clear()相关方法没有公开,
  只能一直重新decodeFromURL同一个远程svga文件,会导致onComplete与onError不回调)

**Comment by lazy2b** [comment]
应该跟我的场景类似
