### ISSUE TITLE
加载两个asset中的sbga特别慢

### ISSUE THREAD

**Issue by SemiraChen** [svga/SVGAPlayer-Android#294]
我加载两张svga
一张播放一次之后播放另一张，一进activity之后加载完毕直接播放，但是加载需要两三秒是业务不能忍受的。
求解
我使用的是两个svga控件，控制显示隐藏。求解啊，我已经换了三种方案

  svgaParserVoice = SVGAParser.Companion.shareParser();
        svgaParserVoice.decodeFromAssets("voice.svga", new SVGAParser.ParseCompletion() {
            @Override
            public void onComplete(@NotNull SVGAVideoEntity videoItem) {
                Log.v("CSYTest", "onComplete");
                svgaVideoEntityVoice = videoItem;
//                svgVoice.setVideoItem(videoItem);
//                flag++;
//                if (flag == 1) {
//                    svgBk.stepToFrame(0, true);
//                }
            }

            @Override
            public void onError() {
            }
        });

        svgaParser = SVGAParser.Companion.shareParser();
        svgaParser.decodeFromAssets("loading.svga", new SVGAParser.ParseCompletion() {
            @Override
            public void onComplete(@NotNull SVGAVideoEntity videoItem) {
                svgaVideoEntity = videoItem;
//                svgBk.setVideoItem(videoItem);
//                Log.v("CSYTest", "svgaParser--onComplete");
//                flag++;
//                if (flag == 1) {
//                    svgBk.stepToFrame(0, true);
//                }
            }

            @Override
            public void onError() {
            }
        });

## Attention

* Do not ask any usage question, issue board is a issue board, accept library bugs only.
* If you are facing any usage problem, read the README again.

## Issue Template

Issue Description(What's your problem)

How To Reappear(How to reappear the issue)

Any Attachment(Provide a sample about your issue)

------ 中文分割线 ------

## 注意 

* 不要在 Issue 板块提问使用问题，Issue 板块只接受 Bug 反馈。
* 如果遇到使用上的问题，仔细阅读 README。

## Issue 模板

请尽量使用英文提交 Issue

请确切回答：问题的描述、重现方式、附件（提供一个 Demo 以重现问题）

**Comment by lazy2b** [comment]
是clear的问题。自己fork代码公开clear方法。然后添加是否要在onDetachView里面自动清除资源的标记。然后就可以缓存 SVGADrawable和SvgaVideoEntity而不用每次都decodeFromAssets了。用完自己调用clear即可。可参考我自己fork修改的一个分支：https://github.com/lazy2b/SVGAPlayer-Android/tree/2.5.8.local.cache
