### ISSUE TITLE
解析asset  下的 a.svga文件   会缓存key    是否可以设置不添加缓存key

### ISSUE THREAD

**Issue by 18337137379** [svga/SVGAPlayer-Android#295]
解析asset  下的 a.svga文件   会缓存key     buildCacheDir(cacheKey).exists()    先播放 a.svga    在把a.svga   删掉 再把b。svga  名字改成 a.svga   因为有缓存  还是会播放直接旧的 a得  动画  并不会播放 b得动画（ps  b只是把名字改成了a）  
是否可以加个不设置缓存key 得方法

**Comment by painld6** [comment]
嗯，我们考虑下怎么处理，现阶段你可以直接使用 SVGAParser#decodeFromInputStream 方法，然后自定义自己的 CacheKey 避免这个问题
