### ISSUE TITLE
2.5.10远程依赖不上，是不是没编出来啊🥺

### ISSUE THREAD

**Issue by OBaKai** [svga/SVGAPlayer-Android#297]
![image](https://user-images.githubusercontent.com/24663585/92209167-224f2d80-eebf-11ea-98dd-198bf4c3b1c1.png)

**Comment by Duosl** [comment]
+1

**Comment by youxiachai** [comment]
用11 吧。。。 10 编译失败了。

**Comment by chenyunecjtu** [comment]
2.5.11 版本，做普通的imageview使用，点击事件有时会无效
