### ISSUE TITLE
 java.lang.OutOfMemoryError com.opensource.svgaplayer.SVGAParser.byte[] inflate(byte[])(SourceFile:352)

### ISSUE THREAD

**Issue by HelloJokerWord** [svga/SVGAPlayer-Android#298]
## Attention

* Do not ask any usage question, issue board is a issue board, accept library bugs only.
* If you are facing any usage problem, read the README again.

## Issue Template

Issue Description(What's your problem)
Error log statistics：

java.io.ByteArrayOutputStream.expand(ByteArrayOutputStream.java:91)
--
2 java.io.ByteArrayOutputStream.write(ByteArrayOutputStream.java:201)
3 com.opensource.svgaplayer.SVGAParser.byte[] inflate(byte[])(SourceFile:352)
4 com.opensource.svgaplayer.SVGAParser.java.lang.ref.WeakReference access$getMContextRef$p(com.opensource.svgaplayer.SVGAParser)(SourceFile:28)
5 ##_parent_##10##_parent_##
6 ##_child_## java.lang.String access$buildCacheKey$d7d22e3(java.lang.String)##_child_##
7 ##_child_## void access$decodeFromCacheKey(com.opensource.svgaplayer.SVGAParser,java.lang.String,com.opensource.svgaplayer.SVGAParser$ParseCompletion)##_child_##
8 ##_child_## java.lang.String access$buildCacheKey$5a6785b2(java.net.URL)##_child_##
9 ##_child_## void access$invokeErrorCallback(com.opensource.svgaplayer.SVGAParser,java.lang.Exception,com.opensource.svgaplayer.SVGAParser$ParseCompletion)##_child_##
10 ##_child_## byte[] access$readAsBytes$4373cb43(java.io.InputStream)##_child_##
11 ##_child_## java.io.File access$buildCacheDir(com.opensource.svgaplayer.SVGAParser,java.lang.String)##_child_##
12 ##_child_## void access$unzip(com.opensource.svgaplayer.SVGAParser,java.io.InputStream,java.lang.String)##_child_##
13 ##_child_## byte[] access$inflate$758363c3(byte[])##_child_##
14 ##_child_## void access$invokeCompleteCallback(com.opensource.svgaplayer.SVGAParser,com.opensource.svgaplayer.SVGAVideoEntity,com.opensource.svgaplayer.SVGAParser$ParseCompletion)##_child_##
15 ##_child_## java.util.concurrent.atomic.AtomicInteger access$getThreadNum$cp()##_child_##
16 com.opensource.svgaplayer.SVGAParser$decodeFromInputStream$1.void run()(SourceFile:187)
17 java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
18 java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
19 java.lang.Thread.run(Thread.java:841)

How To Reappear(How to reappear the issue)
 ## Android 4.4.4,level 19  will appear

Any Attachment(Provide a sample about your issue)

------ 中文分割线 ------

## 注意 

* 不要在 Issue 板块提问使用问题，Issue 板块只接受 Bug 反馈。
* 如果遇到使用上的问题，仔细阅读 README。

## Issue 模板

请尽量使用英文提交 Issue

请确切回答：问题的描述、重现方式、附件（提供一个 Demo 以重现问题）

**Comment by painld6** [comment]
能描述下使用场景吗？看错误信息是在解析 svga 时出现的
