### ISSUE TITLE
帧图片做成的SVGA是不是占用内存会很大？

### ISSUE THREAD

**Issue by leogentleman** [svga/SVGAPlayer-Android#30]
你好，设计做了个用帧图片做成的SVGA，用项目提供的示例载入，发现内存竟从30+M一路涨到300M，是设计制作的方法不对，还是本来就会占用较大的内存？YY有在低端手机上做过测试吗？有没有因此多了很多OOM？谢谢！

**Comment by PonyCui** [comment]
本来就不适合这样的方式制作动画

**Comment by PonyCui** [comment]
这样的动画在导出的时候也会有明确提示 “会导致应用崩溃”
