### ISSUE TITLE
顯示SVGA動畫顏色不正確 黃色變成紅色

### ISSUE THREAD

**Issue by yabee5566** [svga/SVGAPlayer-Android#300]
<com.opensource.svgaplayer.SVGAImageView
        android:id="@+id/sound_ripple_img"
        android:layout_width="80dp"
        android:layout_height="80dp"
        app:source="sound_wave.svga" />

我的程式碼樸實無華 svga檔案也是
就一個圈圈的黃色波紋圖
問題是他在iOS上面顯示是黃色
這網站顯示也是黃色
偏偏到Android上就變成紅色
請問是鬼月鬧鬼嗎？ 還是是什麼原因造成呢
https://svga.io/svga-preview.html

![image](https://user-images.githubusercontent.com/6916871/93160813-bfbe2300-f743-11ea-9c6e-d7226e0293b8.png)

[soundwave(1).zip](https://github.com/svga/SVGAPlayer-Android/files/5222229/soundwave.1.zip)

**Comment by painld6** [comment]
我们这边排查下，看看是哪里的问题，感谢提供的 svga 文件

**Comment by painld6** [comment]
已经在新版本修复了，到时候可以试下

**Comment by yabee5566** [comment]
辛苦了 可惜我們趕時間轉用Lottie了
