### ISSUE TITLE
缓存问题

### ISSUE THREAD

**Issue by zijinzhiyun** [svga/SVGAPlayer-Android#301]
1.是否可以公开设置SVGACache缓存目录方法？
2.是否可以公开删除SVGACache缓存目录方法？
3.iOS有内存级缓存，Android是否考虑增加内存级缓存？

**Comment by shenshuo** [comment]
if (bytes.size > 4 && bytes[0].toInt() == 80 && bytes[1].toInt() == 75 && bytes[2].toInt() == 3 && bytes[3].toInt() == 4) {
                        LogUtils.info(TAG, "decode from zip file")
                        if (!SVGACache.buildCacheDir(cacheKey).exists() || isUnzipping) {
                            synchronized(fileLock) {
                                if (!SVGACache.buildCacheDir(cacheKey).exists()) {
                                    isUnzipping = true
                                    LogUtils.info(TAG, "no cached, prepare to unzip")
                                    ByteArrayInputStream(bytes).use {
                                        unzip(it, cacheKey)
                                        isUnzipping = false
                                        LogUtils.info(TAG, "unzip success")
                                    }
                                }
                            }
                        }
                        this.decodeFromCacheKey(cacheKey, callback)
                    }

这串代码好像导致的所加载的svga都没有缓存 所有的都从远端下载

**Comment by painld6** [comment]
1、尽量保持应用级的 cache 目录去缓存就可以了，而且 Android 10 之后更新了分区存储，后续自定义意义不是很大
2、可以
3、会考量

**Comment by painld6** [comment]
> if (bytes.size > 4 && bytes[0].toInt() == 80 && bytes[1].toInt() == 75 && bytes[2].toInt() == 3 && bytes[3].toInt() == 4) {
> LogUtils.info(TAG, "decode from zip file")
> if (!SVGACache.buildCacheDir(cacheKey).exists() || isUnzipping) {
> synchronized(fileLock) {
> if (!SVGACache.buildCacheDir(cacheKey).exists()) {
> isUnzipping = true
> LogUtils.info(TAG, "no cached, prepare to unzip")
> ByteArrayInputStream(bytes).use {
> unzip(it, cacheKey)
> isUnzipping = false
> LogUtils.info(TAG, "unzip success")
> }
> }
> }
> }
> this.decodeFromCacheKey(cacheKey, callback)
> }
> 
> 这串代码好像导致的所加载的svga都没有缓存 所有的都从远端下载

decodeFromCacheKey 是这个方法内部有问题，可以更新最新版试试

**Comment by zjj1379805106** [comment]
你好，我使用最新的2.5.15版本的SVGAPlayer-Android时遇到了一个关于缓存方面的问题。我使用SVGA默认的缓存机制从远端加载一个文件，结果查看本地缓存生成了两个同名文件，文件带后缀名，分别为.0和.1。这样导致下次加载同个远端文件的时候本地找不到该文件名的文件。请问这该如何处理？
例如加载此远程文件地址”https://images.zhibo.tv/svga/gift/bieshu.svga"，本地会生成两个缓存文件分别为7373df9cf7697e29bb299bbfcbe2c5e3.0与7373df9cf7697e29bb299bbfcbe2c5e3.1。

**Comment by zijinzhiyun** [comment]
> 1、尽量保持应用级的 cache 目录去缓存就可以了，而且 Android 10 之后更新了分区存储，后续自定义意义不是很大
> 2、可以
> 3、会考量

目前是缓存在私有的cache的svga目录下，希望可以放在getFilesDir或者getExternalFilesDir目录下。
