### ISSUE TITLE
targetSdkVersion 必须28吗？targetSdkVersion 29，部分华为P40 Pro （Android Q）的手机无法显示动效

### ISSUE THREAD

**Issue by jialiningjialining** [svga/SVGAPlayer-Android#302]
targetSdkVersion 必须28吗？targetSdkVersion 29，部分华为P40 Pro （Android Q）的手机无法显示动效其他手机没有验证

**Comment by jialiningjialining** [comment]
targetSdkVersion 必须28吗？targetSdkVersion 29，部分华为P40 Pro （Android Q）的手机无法显示动效

**Comment by painld6** [comment]
使用的是哪个版本？

**Comment by jialiningjialining** [comment]
使用的是2.5.8

**Comment by jialiningjialining** [comment]
> 使用的是哪个版本？

我是使用的2.5.8，我是在远程真机测试的，无法显示动效的手机是所有的svga都无法显示

**Comment by painld6** [comment]
> > 使用的是哪个版本？
> 
> 我是使用的2.5.8，我是在远程真机测试的，无法显示动效的手机是所有的svga都无法显示

那可以试下最新的版本，如果还有问题可以继续反馈下

**Comment by jialiningjialining** [comment]
> > > 使用的是哪个版本？
> > 
> > 
> > 我是使用的2.5.8，我是在远程真机测试的，无法显示动效的手机是所有的svga都无法显示
> 
> 那可以试下最新的版本，如果还有问题可以继续反馈下

远程找了一个无法展示华为P40 真机，升级到2.5.12还是不行

**Comment by painld6** [comment]
> > > > 使用的是哪个版本？
> > > 
> > > 
> > > 我是使用的2.5.8，我是在远程真机测试的，无法显示动效的手机是所有的svga都无法显示
> > 
> > 
> > 那可以试下最新的版本，如果还有问题可以继续反馈下
> 
> 远程找了一个无法展示华为P40 真机，升级到2.5.12还是不行

方便提供一个 svga 文件，让我们测试吗？：)

**Comment by fdh19979** [comment]
我也遇到类似的问题，海外用户反馈无法观看动效
最终找到了问题所在
应用启动的时候重置一下动画缩放时间就可以了
https://github.com/svga/SVGAPlayer-Android/issues/314
