### ISSUE TITLE
Why SVGADrawable is not public？Do I have to use SVGAImageView？

### ISSUE THREAD

**Issue by FhrShadow** [svga/SVGAPlayer-Android#303]
For some reason, I have to draw svga in a SurfaceView. So I `lockCanavs()` and `svgaDrawable.draw(canvas)`

But I see that
```kotlin
//SVGADrawable.class
var currentFrame = 0
     internal set (value)
```
```kotlin
//SVGADrawable.class
var cleared = true
     internal set (value)
```
emmmmmmmmmmmm

Okay, if you don't motify `cleared`, the `svgaDrawable.draw(canvas)` will return immediately. if you don't motify currentFrame, can't play next frame.

I motify them by reflection. it's work. But, performance.

So, why they are internal? Do I have to use SVGAImageView？

**Comment by painld6** [comment]
At present, SVGADrawable serves SVGAImageView, so we don’t want to modify SVGADrawable externally.
