### ISSUE TITLE
2.5.11版本无法解析assets目录的svga

### ISSUE THREAD

**Issue by mouse1019** [svga/SVGAPlayer-Android#304]
查询代码发现，缓存被修改过，缓存目录是cache/svga/xxxx，代码读取目录仍然是 cache/xxxx，导致解析失败。
麻烦大佬，查查是否确实存在此问题？谢谢了~~~（2.5.9版本正常）

定位到的代码片段是   SVGACache.kt
fun onCreate(context: Context?, type: Type) {
        if (isInitialized()) return
        context ?: return
        cacheDir = "${context.cacheDir.absolutePath}/svga/"
        File(cacheDir).takeIf { !it.exists() }?.mkdir()
        this.type = type
    }

**Comment by painld6** [comment]
嗯，确实是，内部有个方法没有使用到 SVGACache 导致的，新版本已修复
