### ISSUE TITLE
設定scaleType="fitXY"不會填滿整個SVGAImageView

### ISSUE THREAD

**Issue by yabee5566** [svga/SVGAPlayer-Android#307]
我的SVGA檔案比SVGAImageView小 
設定scaleType="fitXY"
動畫卻沒有填滿還是小小的

**Comment by painld6** [comment]
因为他默认就是填满整个 SVGAImageView，不需要设置 fixXY，你可以试下 demo

**Comment by yabee5566** [comment]
@painld6  請頓Demo在哪裏？readme沒看到

**Comment by painld6** [comment]
这个库本身也是个 demo 喔，你可以下载后运行下代码就知道了
