### ISSUE TITLE
公司买个其中一个svga 文件,一播放模拟器Profiler内存监控瞬间增加了160mb,请问是啥原因

### ISSUE THREAD

**Issue by KevinPeng31** [svga/SVGAPlayer-Android#308]
公司买个其中一个svga 文件,一播放模拟器Profiler内存监控瞬间增加了160mb,请问是啥原因

**Comment by KevinPeng31** [comment]
http://oss.1231yx.com/'admin/image/20201006/1021cdce34a799ed53dece3dc191297a.svga'  这个svga 地址

**Comment by PonyCui** [comment]
一般来说是因为设计素材不规范导致的，也有可能是矢量元素过多导致。

**Comment by df13954** [comment]
> 公司买个其中一个svga 文件,一播放模拟器Profiler内存监控瞬间增加了160mb,请问是啥原因

我们公司ui给我的动画效果，加载完成之后内存增加了300mb，。。。。。。。

**Comment by PonyCui** [comment]
@ff-frida 那你需要从设计师源头上找原因

**Comment by df13954** [comment]
> @ff-frida 那你需要从设计师源头上找原因

哈哈，我们的设计师很菜，能做出来已经很吃力了。反正出了问题，就把锅给设计师。
