### ISSUE TITLE
耗内存问题。

### ISSUE THREAD

**Issue by stormdzh** [svga/SVGAPlayer-Android#31]
我在使用这个sdk的时候时候，发现很耗内存，在一个viewpager上加载svga控件，发现很卡，之后调试发现，一个svga控件加载一个svga文件就消耗了40m内存，这个怎么优化？

**Comment by PonyCui** [comment]
先看看你的 svga 文件在导出时有没有提示『内存占用过大』

**Comment by protectedMan** [comment]
确实啊，我跑demo用AS自带性能监视器。 发现玫瑰花动画一出来内存占用巨大。内存从30MB到70MB.

**Comment by PonyCui** [comment]
@protectedMan 你说的动画是指哪个

**Comment by protectedMan** [comment]
玫瑰动画啊。你demo里的    rose_2.0.0.svga

**Comment by PonyCui** [comment]
@protectedMan 这个动画是相对复杂的动画，内存占用大是正常的，里面有 188 个元素。

**Comment by protectedMan** [comment]
![image](https://user-images.githubusercontent.com/17565737/35366436-82ac1ddc-01b4-11e8-8349-287b5e364cdd.png)
400MB内存占用，还有救么。我真不知道怎么优化这内存大小了。。。

**Comment by PonyCui** [comment]
@protectedMan 没救，你的素材如果是一大堆的透明空白，这是必然的。

**Comment by PonyCui** [comment]
@protectedMan 我们发现在 AE 转换器上存在一个 BUG，会导致 PSD 矢量素材占用内存问题，正在修复中。

**Comment by PonyCui** [comment]
@protectedMan  这个问题已经修复了，更新 AE 插件重新导出就可以。
yyued/SVGA-AEConverter#11

**Comment by ruidge** [comment]
@protectedMan 你们后来怎么优化的 有什么技巧

**Comment by PonyCui** [comment]
@ruidge 更新 AE 插件就可以解决问题，你遇到了什么问题？

**Comment by ruidge** [comment]
@PonyCui  我们需要显示有3d效果的动画, UI做的帧动画, 显示的时候内存飙升. 有什么好方法 或者说制作技巧

**Comment by PonyCui** [comment]
@ruidge 序列帧是没有办法优化的，SVGA 只支持 2D 动画。
