### ISSUE TITLE
设置SVGAImageView 大小例如200dp*200dp   svga宽高是150px    但是显示的svga动画显示不全   会被截取

### ISSUE THREAD

**Issue by tcwy123456** [svga/SVGAPlayer-Android#310]
## Attention

* Do not ask any usage question, issue board is a issue board, accept library bugs only.
* If you are facing any usage problem, read the README again.

## Issue Template

Issue Description(What's your problem)

How To Reappear(How to reappear the issue)

Any Attachment(Provide a sample about your issue)

------ 中文分割线 ------

## 注意 

* 不要在 Issue 板块提问使用问题，Issue 板块只接受 Bug 反馈。
* 如果遇到使用上的问题，仔细阅读 README。

## Issue 模板

请尽量使用英文提交 Issue

请确切回答：问题的描述、重现方式、附件（提供一个 Demo 以重现

设置SVGAImageView 大小例如200dp*200dp   svga宽高是150px    但是显示的svga动画显示不全   会被截取
![image](https://user-images.githubusercontent.com/14146345/95808268-b0c89180-0d3e-11eb-88fe-7bbdcfe294e1.png)

**Comment by painld6** [comment]
有没有尝试在 http://svga.io/svga-preview.html 看效果？是否和设计稿的一致。
另外，请问下你使用的版本是多少？

**Comment by tcwy123456** [comment]
最新 版本   是Android版本的

**Comment by tcwy123456** [comment]
看了  svga动画大小是150px*150px

**Comment by tcwy123456** [comment]
看了  SVGA动画宽高是150*150px   使用的是最新版本的

**Comment by painld6** [comment]
方便把 demo 或者 svga 文件附上来吗？
