### ISSUE TITLE
Dynamic Text Layout 直接设置paint的textSize 显示效果偏小，是否需要做个sp2px 转换， iOS 和Android 如何保持大小一致

### ISSUE THREAD

**Issue by marvinyangjs** [svga/SVGAPlayer-Android#312]
## Attention

* Do not ask any usage question, issue board is a issue board, accept library bugs only.
* If you are facing any usage problem, read the README again.

## Issue Template

Issue Description(What's your problem)

How To Reappear(How to reappear the issue)

Any Attachment(Provide a sample about your issue)

------ 中文分割线 ------

## 注意 

* 不要在 Issue 板块提问使用问题，Issue 板块只接受 Bug 反馈。
* 如果遇到使用上的问题，仔细阅读 README。

## Issue 模板

请尽量使用英文提交 Issue

请确切回答：问题的描述、重现方式、附件（提供一个 Demo 以重现问题）

**Comment by painld6** [comment]
不太理解你所说的，你是说设置 SVGA 中关于 text 的元素吗？还是别的？

**Comment by marvinyangjs** [comment]
> 不太理解你所说的，你是说设置 SVGA 中关于 text 的元素吗？还是别的？

是的，替换text元素，构造一个staticlayout 需要设置 paint 的大小
[Dynamic Text Layout](https://github.com/svga/SVGAPlayer-Android/wiki/Dynamic-Text-Layout)

如上链接中的
TextPaint textPaint = new TextPaint();
textPaint.setColor(Color.WHITE);
textPaint.setTextSize(28);

显示效果明显比系统TextView 中 setTextSize 小。因为textView 自身对 textsize 做了一个sp的转换。

**Comment by painld6** [comment]
> > 不太理解你所说的，你是说设置 SVGA 中关于 text 的元素吗？还是别的？
> 
> 是的，替换text元素，构造一个staticlayout 需要设置 paint 的大小
> [Dynamic Text Layout](https://github.com/svga/SVGAPlayer-Android/wiki/Dynamic-Text-Layout)
> 
> 如上链接中的
> TextPaint textPaint = new TextPaint();
> textPaint.setColor(Color.WHITE);
> textPaint.setTextSize(28);
> 
> 显示效果明显比系统TextView 中 setTextSize 小。因为textView 自身对 textsize 做了一个sp的转换。

对的，你可以看下 TextPaint 的 setTextSize 的方法注释，上面是有说道，这里的值是以 px 为单位的，但 TextView 的 setTextSize 默认是 sp 为单位的，所以，这里的话你是需要做下转换才行
