### ISSUE TITLE
可以播放getFilesDir()下的svga文件吗

### ISSUE THREAD

**Issue by laoyana** [svga/SVGAPlayer-Android#313]
可以播放getFilesDir()下的svga文件吗

How To Reappear(How to reappear the issue)

Any Attachment(Provide a sample about your issue)

------ 中文分割线 ------

## 注意 

* 不要在 Issue 板块提问使用问题，Issue 板块只接受 Bug 反馈。
* 如果遇到使用上的问题，仔细阅读 README。

## Issue 模板

请尽量使用英文提交 Issue

请确切回答：问题的描述、重现方式、附件（提供一个 Demo 以重现问题）

**Comment by painld6** [comment]
暂时只有加载 assets 路径下 和 url 资源
