### ISSUE TITLE
targetSdkVersion 29，部分海外机型无法显示动效 

### ISSUE THREAD

**Issue by fdh19979** [svga/SVGAPlayer-Android#314]
找到问题所在
用户的手机的动画缩放被错误关闭了，目前发现这种情况在还挺多。

SVGAImageView中使用的反射修改缩放值的方式：
getDeclaredField("sDurationScale") 在 Android 10 中属于受限的灰名单
Accessing hidden field Landroid/animation/ValueAnimator;->sDurationScale:F (greylist-max-p, reflection, denied)

经过测试，可以使用 getDeclaredMethod("setDurationScale", float.class) 代替，这个方法没有出现在灰名单列表中
Accessing hidden method Landroid/animation/ValueAnimator;->setDurationScale(F)V (greylist, reflection, allowed)

灰名单地址
https://developer.android.google.cn/about/versions/10/non-sdk-q?hl=th

================================

targetSdkVersion修改为29以后，部分androidQ手机无法显示动效，主要以海外版机型为主

使用的版本是2.4.2，经过测试2.5.13也一样不行

比如 同样的华为P30 pro 
国行版model VOG-AL00可以显示动效， 海外版model VOG-L29就无法显示动效

无聊是本地svga文件，还是通过网络下载的svga文件，所有的svga文件都无法显示
这里是其中的一个例子
https://showme-livecdn.elelive.net/gift/gift/20201016/1349cfab36a742b0aa93cb0aeb039576.svga

目前发现无法显示动效的海外机型
Mi 9T PRO
Huawei Nova 4e
Huawei P30 PRO

目前手头没有真机做debug测试所以无法确认具体出现问题的位置。

**Comment by shuihuvstuzi** [comment]
> targetSdkVersion修改为29以后，部分androidQ手机无法显示动效，主要以海外版机型为主
> 
> 比如 同样的华为P30 pro
> 国行版model VOG-AL00可以显示动效， 海外版model VOG-L29就无法显示动效
> 
> 无聊是本地svga文件，还是通过网络下载的svga文件，所有的svga文件都无法显示
> 这里是其中的一个例子
> https://showme-livecdn.elelive.net/gift/gift/20201016/1349cfab36a742b0aa93cb0aeb039576.svga
> 
> 目前发现无法显示动效的海外机型
> Mi 9T PRO
> Huawei Nova 4e
> Huawei P30 PRO
> 
> 目前手头没有真机做debug测试所以无法确认具体出现问题的位置。

请问你用的是什么版本？

**Comment by fdh19979** [comment]
> > targetSdkVersion修改为29以后，部分androidQ手机无法显示动效，主要以海外版机型为主
> > 比如 同样的华为P30 pro
> > 国行版model VOG-AL00可以显示动效， 海外版model VOG-L29就无法显示动效
> > 无聊是本地svga文件，还是通过网络下载的svga文件，所有的svga文件都无法显示
> > 这里是其中的一个例子
> > https://showme-livecdn.elelive.net/gift/gift/20201016/1349cfab36a742b0aa93cb0aeb039576.svga
> > 目前发现无法显示动效的海外机型
> > Mi 9T PRO
> > Huawei Nova 4e
> > Huawei P30 PRO
> > 目前手头没有真机做debug测试所以无法确认具体出现问题的位置。
> 
> 请问你用的是什么版本？

几个版本都试了，都不行

**Comment by painld6** [comment]
这边也没有海外机可以复现，国内的也确实没问题，所以，可以尝试下这么做
1、手动开启硬件加速，虽然理论上是默认开启，但不同机型还是有些区别，建议尝试
2、用 SVGALogger 收集下 svga 内部逻辑，看看是哪部分出了问题

**Comment by fdh19979** [comment]
> 这边也没有海外机可以复现，国内的也确实没问题，所以，可以尝试下这么做
> 1、手动开启硬件加速，虽然理论上是默认开启，但不同机型还是有些区别，建议尝试
> 2、用 SVGALogger 收集下 svga 内部逻辑，看看是哪部分出了问题

找到问题所在
用户的手机的动画缩放被错误关闭了，目前发现这种情况在还挺多。

SVGAImageView中使用的反射修改缩放值的方式：
getDeclaredField("sDurationScale") 在 Android 10 中属于受限的灰名单，会被denied
Accessing hidden field Landroid/animation/ValueAnimator;->sDurationScale:F (greylist-max-p, reflection, denied)

经过测试，可以使用 getDeclaredMethod("setDurationScale", float.class) 代替，不属于受限的灰名单，会被allowed
Accessing hidden method Landroid/animation/ValueAnimator;->setDurationScale(F)V (greylist, reflection, allowed)

灰名单地址
https://developer.android.google.cn/about/versions/10/non-sdk-q?hl=th

**Comment by painld6** [comment]
内部使用 ValueAnimator 时确实用了反射的方式，那这块我们完善下逻辑，感谢发现了这个问题

**Comment by zhangxiaojin770** [comment]
> 内部使用 ValueAnimator 时确实用了反射的方式，那这块我们完善下逻辑，感谢发现了这个问题

那这个版本问题什么时候能更新到呢

**Comment by zhangxiaojin770** [comment]
哪个版本能解决掉这个问题 我现在用的是2.5.12

**Comment by painld6** [comment]
> 哪个版本能解决掉这个问题 我现在用的是2.5.12

最新是 2.5.14，可以试下

**Comment by zhangxiaojin770** [comment]
> > 哪个版本能解决掉这个问题 我现在用的是2.5.12
> 
> 最新是 2.5.14，可以试下

2.5.14是稳定版吗

**Comment by painld6** [comment]
> > > 哪个版本能解决掉这个问题 我现在用的是2.5.12
> > 
> > 
> > 最新是 2.5.14，可以试下
> 
> 2.5.14是稳定版吗

嗯，只是反射出现问题，修改测试后是可以的
