### ISSUE TITLE
Svga is not playing.

### ISSUE THREAD

**Issue by youlivear** [svga/SVGAPlayer-Android#315]
When I play any svga file first, it is played. 
But when play again same svga file, it is no played.
By testing several times, SVGA that have ever played one time is not played again.
And by seeing log file, sound is played and step is called. But only svgaimageview is not shown.
![image](https://user-images.githubusercontent.com/71258356/97411438-3e110600-193b-11eb-8a4b-ca22dcf778ac.png)
I want to know. Thanks

**Comment by painld6** [comment]
Note that the clearsAfterStop and clearsAfterDetached inside SVGAImageView is true by default，So it won’t play the second time after playing the first time
