### ISSUE TITLE
如果动画播放的频繁 会造成 renderthread 崩溃

### ISSUE THREAD

**Issue by yangfeng1994** [svga/SVGAPlayer-Android#316]
在直播间中，最多有8个SVGAImageView同时播放的时候，会造成 renderthread 崩溃
[舌头.zip](https://github.com/svga/SVGAPlayer-Android/files/5463750/default.zip)

**Comment by PonyCui** [comment]
你这个是序列帧，请让设计重新使用元素动画方式设计输出。
