### ISSUE TITLE
 startAnimation  设置后 会被方法覆盖 

### ISSUE THREAD

**Issue by jwc793318828** [svga/SVGAPlayer-Android#317]
startAnimation   传递 SVGARange 后 
内部有个onComplete的回调方法 。传递的videoItem 对象后 重新调用startAnimaition 方法是不带range对象的 
然后导致 range对象被重置 。所以如果代码内设置的开始帧数跟结束帧数 就会被覆盖 无效果 

我这边记录下传递下的range 。 如果遇到一样的问题的 可以参考

**Comment by PonyCui** [comment]
就是这样设计的哦
