### ISSUE TITLE
绘制文字设置textAlign 属性无效

### ISSUE THREAD

**Issue by MilkBeeno** [svga/SVGAPlayer-Android#319]
在绘制文字时设置textAligin属性无效：
val textPaint1 = TextPaint()
textPaint1.textAlign = Paint.Align.LEFT
dynamicEntity.setDynamicText(leftUserName, textPaint1, "left_name")
在绘制时textAlign属性会被强制覆盖为 Paint.Align.CENTER：SVGACanvasDrawer#drawTextOnBitmap()
val textCanvas = Canvas(textBitmap)
 drawingTextPaint.isAntiAlias = true
 drawingTextPaint.setStyle(Paint.Style.FILL);
 drawingTextPaint.setTextAlign(Paint.Align.CENTER);

**Comment by clbDream** [comment]
你好.2.6.1版本中设置文字居左无效,还是显示在中间位置
