### ISSUE TITLE
svga带的声音长，声音播放不全. 会中间断掉,有什么办法可以解决这个问题吗

### ISSUE THREAD

**Issue by zjJunZhu** [svga/SVGAPlayer-Android#321]
## Attention

* Do not ask any usage question, issue board is a issue board, accept library bugs only.
* If you are facing any usage problem, read the README again.

## Issue Template

Issue Description(What's your problem)

How To Reappear(How to reappear the issue)

Any Attachment(Provide a sample about your issue)

------ 中文分割线 ------

## 注意 

* 不要在 Issue 板块提问使用问题，Issue 板块只接受 Bug 反馈。
* 如果遇到使用上的问题，仔细阅读 README。

## Issue 模板

请尽量使用英文提交 Issue

请确切回答：问题的描述、重现方式、附件（提供一个 Demo 以重现问题）

**Comment by PonyCui** [comment]
暂时是不支持长音频的

**Comment by jjdy2006** [comment]
这个问题只会出现在安卓端，安卓端源码中声音播放是用soundpool的方式去播放的，这个倒不是svga框架的问题，而是soundpool本身的问题，soundpool本意其实只是播放一个音效文件，对长音频支持不是很好。不过也有解决办法，可以从音乐本身入手，将你要播放的音乐进行转码压缩，降低码率（其实就是牺牲一些音质）。
以MP3音乐文件为例，我目前使用的是12000Hz取样率，128kbps，基本能满足商用需求，音乐最长也可支持到几十秒
