### ISSUE TITLE
提供一个因加载带声音svga引起的SvgaParser无回调的解决方案。

### ISSUE THREAD

**Issue by OBaKai** [svga/SVGAPlayer-Android#322]
起因：由于产品大哥秀了一个豪华需求，其中里边需要使用到大量带声音的svga，因而发现svgaplayer库在加载带声音的svga文件的时候，会有一定概率出现无回调的情况，导致svga无法播放。这让产品大哥非常不满，所有开始了read the fucking source code。

问题定位：锅出在SoundPool这儿，SVGAParser依赖SoundPool OnLoadCompleteListener来回调，SoundPool都不走这个回调，自然SVGAParser也就不回调了。

问题猜测：可能是由于频繁创建SoundPool引起的，这只是猜测。看了SoundPool源码也没大看懂。。。

解决方案：将SoundPool放到单例里边管理
我在项目里边使用SoundPool的话，都是将其放到单例里边使用的。
结合前段时间看了文章，受到启发。 文章连接：Android SoundPool崩溃问题研究 https://zhuanlan.zhihu.com/p/29985198

连接：https://github.com/OBaKai/SVGAPlayer-Android.git 
我定义了一个SVGASoundManager单例类，并在里边管理一个SoundPool。有初始化的情况就会走单例类的逻辑，没有初始化就会走原来svgaplayer库的逻辑。

效果：目前在项目中使用了有段时间，暂时没有发现问题。

代码仅供参考，如果有啥建议或问题一起探讨。

**Comment by PonyCui** [comment]
你可以提一个 PR

**Comment by painld6** [comment]
就仅仅是一个内部带有很多音频的 svga，在加载过程中，会偶尔出 svga 解析失败，然后就导致无法播放，是这样的问题吗？

**Comment by OBaKai** [comment]
> 就仅仅是一个内部带有很多音频的 svga，在加载过程中，会偶尔出 svga 解析失败，然后就导致无法播放，是这样的问题吗？

只要带有音频的svga都可能会出现加载无回调的情况，我这边svga有带一个或者多个的音频的都会出现。

**Comment by PonyCui** [comment]
@painld6 确实有这个问题，值得为此提交一个 commit。

**Comment by painld6** [comment]
> @painld6 确实有这个问题，值得为此提交一个 commit。

好的，后面我完善下

**Comment by a365344743s** [comment]
老板，PR都几个月了，什么时候能解决啊

**Comment by painld6** [comment]
> 老板，PR都几个月了，什么时候能解决啊

目前他的 PR 有些问题需要完善，我这边也有在重新设计这部分，后续重新提 PR 上来，不过你可以参考下他的先用也是可以

**Comment by sharyuke** [comment]
这个问题修复了没呀？我们这边也出现这样的问题。

**Comment by painld6** [comment]
> 这个问题修复了没呀？我们这边也出现这样的问题。

你先用下他这个方案

**Comment by SakyaZsl** [comment]
> https://github.com/OBaKai/SVGAPlayer-Android.git

确实是SoundPool 的回调没走，自己一路debug发现原因就是 val audiosFileMap = generateAudioFileMap(entity) 这个hashmap的文件为空，再往下面逻辑看就是generateAudioMap(entity) 中
 if (fileTag[0].toInt() == 73 && fileTag[1].toInt() == 68 && fileTag[2].toInt() == 51) {
                audiosDataMap[imageKey] = byteArray
            }
这个判断才赋值  没看懂这个过滤条件是干嘛的  所以解决办法就是 audiosFileMap 直接回调  或者去掉这个判断之后也会正常回调

**Comment by SakyaZsl** [comment]
> 起因：由于产品大哥秀了一个豪华需求，其中里边需要使用到大量带声音的svga，因而发现svgaplayer库在加载带声音的svga文件的时候，会有一定概率出现无回调的情况，导致svga无法播放。这让产品大哥非常不满，所有开始了read the fucking source code。
> 
> 问题定位：锅出在SoundPool这儿，SVGAParser依赖SoundPool OnLoadCompleteListener来回调，SoundPool都不走这个回调，自然SVGAParser也就不回调了。
> 
> 问题猜测：可能是由于频繁创建SoundPool引起的，这只是猜测。看了SoundPool源码也没大看懂。。。
> 
> 解决方案：将SoundPool放到单例里边管理
> 我在项目里边使用SoundPool的话，都是将其放到单例里边使用的。
> 结合前段时间看了文章，受到启发。 文章连接：Android SoundPool崩溃问题研究 https://zhuanlan.zhihu.com/p/29985198
> 
> 连接：https://github.com/OBaKai/SVGAPlayer-Android.git
> 我定义了一个SVGASoundManager单例类，并在里边管理一个SoundPool。有初始化的情况就会走单例类的逻辑，没有初始化就会走原来svgaplayer库的逻辑。
> 
> 效果：目前在项目中使用了有段时间，暂时没有发现问题。
> 
> 代码仅供参考，如果有啥建议或问题一起探讨。

确实是SoundPool 的回调没走，自己一路debug发现原因就是 val audiosFileMap = generateAudioFileMap(entity) 这个hashmap的文件为空，再往下面逻辑看就是generateAudioMap(entity) 中
if (fileTag[0].toInt() == 73 && fileTag[1].toInt() == 68 && fileTag[2].toInt() == 51) {
audiosDataMap[imageKey] = byteArray
}
这个判断才赋值 没看懂这个过滤条件是干嘛的 所以解决办法就是 audiosFileMap 直接回调 或者去掉这个判断之后也会正常回调

**Comment by Adaclass** [comment]
> > 起因：由于产品大哥秀了一个豪华需求，其中里边需要使用到大量带声音的svga，因而发现svgaplayer库在加载带声音的svga文件的时候，会有一定概率出现无回调的情况，导致svga无法播放。这让产品大哥非常不满，所有开始了read the fucking source code。
> > 问题定位：锅出在SoundPool这儿，SVGAParser依赖SoundPool OnLoadCompleteListener来回调，SoundPool都不走这个回调，自然SVGAParser也就不回调了。
> > 问题猜测：可能是由于频繁创建SoundPool引起的，这只是猜测。看了SoundPool源码也没大看懂。。。
> > 解决方案：将SoundPool放到单例里边管理
> > 我在项目里边使用SoundPool的话，都是将其放到单例里边使用的。
> > 结合前段时间看了文章，受到启发。 文章连接：Android SoundPool崩溃问题研究 https://zhuanlan.zhihu.com/p/29985198
> > 连接：https://github.com/OBaKai/SVGAPlayer-Android.git
> > 我定义了一个SVGASoundManager单例类，并在里边管理一个SoundPool。有初始化的情况就会走单例类的逻辑，没有初始化就会走原来svgaplayer库的逻辑。
> > 效果：目前在项目中使用了有段时间，暂时没有发现问题。
> > 代码仅供参考，如果有啥建议或问题一起探讨。
> 
> 确实是SoundPool 的回调没走，自己一路debug发现原因就是 val audiosFileMap = generateAudioFileMap(entity) 这个hashmap的文件为空，再往下面逻辑看就是generateAudioMap(entity) 中
> if (fileTag[0].toInt() == 73 && fileTag[1].toInt() == 68 && fileTag[2].toInt() == 51) {
> audiosDataMap[imageKey] = byteArray
> }
> 这个判断才赋值 没看懂这个过滤条件是干嘛的 所以解决办法就是 audiosFileMap 直接回调 或者去掉这个判断之后也会正常回调

大佬牛逼

**Comment by SakyaZsl** [comment]
> > https://github.com/OBaKai/SVGAPlayer-Android.git
> 
> 确实是SoundPool 的回调没走，自己一路debug发现原因就是 val audiosFileMap = generateAudioFileMap(entity) 这个hashmap的文件为空，再往下面逻辑看就是generateAudioMap(entity) 中
> if (fileTag[0].toInt() == 73 && fileTag[1].toInt() == 68 && fileTag[2].toInt() == 51) {
> audiosDataMap[imageKey] = byteArray
> }
> 这个判断才赋值 没看懂这个过滤条件是干嘛的 所以解决办法就是 audiosFileMap 直接回调 或者去掉这个判断之后也会正常回调

五星级补充下  不是SoundPool 的回调 而是 SoundPool的 load方法 因为文件的audiosFileMap 为空，soundPool?.load 根本不会进去，既然load方法都没有进去 ，何来的回调

**Comment by sharyuke** [comment]
> > 这个问题修复了没呀？我们这边也出现这样的问题。
> 
> 你先用下他这个方案

用了，不管用。

**Comment by SakyaZsl** [comment]
整理下思路，给个百分百亲测解决办法，原因看着像是SoundPool OnLoadCompleteListener  首先OnLoadCompleteListener  的回调条件是 soundPool?.load 这个方法，audiosFileMap[audio.audioKey]?.let {} 是在这里调用的 ，但是我自己对比了代码逻辑发现audiosFileMap为空，也就是soundPool?.load 没有调用，就不存在回调 ，然后在一路看代码val audiosFileMap = generateAudioFileMap(entity) 到generateAudioMap(entity: MovieEntity): HashMap<String, ByteArray> 再到   if (fileTag[0].toInt() == 73 && fileTag[1].toInt() == 68 && fileTag[2].toInt() == 51) {
                audiosDataMap[imageKey] = byteArray
            }
符合这个条件就可以算是mp3  这个判断会出现部分音频无法识别！ 也就是造成部分音频svga可以播放 部分音频svga直接不回调。所以解决办法就是  1. audiosFileMap  为空的时候直接回调   2. 改变音频的判断条件 ，audiosFileMap不为空，以上就是比较完整的代码出现原因，和代码修改方案

**Comment by SakyaZsl** [comment]
> > > 这个问题修复了没呀？我们这边也出现这样的问题。
> > 
> > 
> > 你先用下他这个方案
> 
> 用了，不管用。

看我下面的代码描述，这个代码逻辑的漏洞就在下方

**Comment by sharyuke** [comment]
所以还是希望官方更新版本，我们更新一下版本就能解决就好了。

**Comment by SakyaZsl** [comment]
> 所以还是希望官方更新版本，我们更新一下版本就能解决就好了。

private fun setupAudios(entity: MovieEntity, completionBlock: () -> Unit) {
        if (entity.audios == null || entity.audios.isEmpty()) {
            run(completionBlock)
            return
        }
        setupSoundPool(entity, completionBlock)
        val audiosFileMap = generateAudioFileMap(entity)
        //******map为空 直接反馈
        if (audiosFileMap.size == 0) {
            completionBlock()
            return
        }

        this.audioList = entity.audios.map { audio ->
            return@map createSvgaAudioEntity(audio, audiosFileMap)
        }
    }

三行代码解决  MP3播放就请改下格式  或者改过滤条件

**Comment by SakyaZsl** [comment]
> 你可以提一个 PR

哈罗，我刚提交了一个pr  请问这里怎么联系你们 我怎么改正我pr不对的地方

**Comment by painld6** [comment]
感谢大佬们的支持，已经更新到 2.6.0 了

**Comment by 1169927533** [comment]
最新版本并没有解决掉setOnLoadCompleteListener不会回调的问题
