### ISSUE TITLE
 播放的动画在各种手机上不一样

### ISSUE THREAD

**Issue by 1335987402** [svga/SVGAPlayer-Android#325]
<com.opensource.svgaplayer.SVGAImageView
            android:id="@+id/mSVGAKninghtood"
            android:layout_width="match_parent"
            android:layout_height="match_parent" />

有点手机可以全屏播放，有得不是全屏播放，请问这个应该如何设置属性

**Comment by painld6** [comment]
这得需要自己适配，毕竟 svga 内部的切图只有一份，不像整个项目的切图还分成 hdpi、xdpi、xxdpi 等等，所以在不同 dpi 屏幕的机型上就会有不同效果，开发者要自己计算并把宽高设置到 SVGAImageView 上
