### ISSUE TITLE
java.lang.OutOfMemoryError

### ISSUE THREAD

**Issue by liuchenc** [svga/SVGAPlayer-Android#326]
![image](https://user-images.githubusercontent.com/14867909/98813304-ec9a6800-245e-11eb-933a-90f043809c4d.png)

 java.util.Arrays.copyOf(Arrays.java:3256)
--
 java.io.ByteArrayOutputStream.toByteArray(ByteArrayOutputStream.java:178)
com.opensource.svgaplayer.g.a(SVGAParser.kt:356)
com.opensource.svgaplayer.g.a(SVGAParser.kt:28)
com.opensource.svgaplayer.g$f.run(SVGAParser.kt:187)
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
java.lang.Thread.run(Thread.java:761)

**Comment by liuchenc** [comment]
用的2.5.8的版本还是会造成java.lang.OutOfMemoryError
![image](https://user-images.githubusercontent.com/14867909/106565047-1ac4ab00-6569-11eb-9567-cb5a187a7df6.png)

**Comment by painld6** [comment]
要注意，不能一次性加载大量的 SVGA 文件，毕竟 SVGA 仅仅做下载和解析
