### ISSUE TITLE
关于使用File缓存时的问题

### ISSUE THREAD

**Issue by diguagege** [svga/SVGAPlayer-Android#328]
我们在线上使用file缓存的时候，遇到一个问题，日志如下
Caused by android.system.ErrnoException: open failed: ENOENT (No such file or directory)
       at libcore.io.Posix.open(Posix.java)
       at libcore.io.BlockGuardOs.open(BlockGuardOs.java:186)
       at java.io.File.createNewFile(File.java:935)
       at com.opensource.svgaplayer.h$f$a.run(SVGAParser.kt:2)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
       at java.lang.Thread.run(Thread.java:818)

因为createNewFile而导致了这个错误，而我们的做法是在外部调用之前，先确保其目录存在。但是进入此位置，依旧有报错。能否在createNewFile初添加异常处理呢

**Comment by painld6** [comment]
请问用的是什么版本？如果你们确保了目录是否存在后仍会出现，那可能要定位下具体问题，这个错误出现的可能性也不仅仅只是这一种，例如：在创建文件夹时如果在不确定父目录的父级是否存在时，最好用 mkdirs 方法创建；权限问题；存储空间不足等等，都可能引发这个 exception，建议打些 log 收集下

**Comment by diguagege** [comment]
> 请问用的是什么版本？如果你们确保了目录是否存在后仍会出现，那可能要定位下具体问题，这个错误出现的可能性也不仅仅只是这一种，例如：在创建文件夹时如果在不确定父目录的父级是否存在时，最好用 mkdirs 方法创建；权限问题；存储空间不足等等，都可能引发这个 exception，建议打些 log 收集下

我们使用的额是2.5.11版本，最后，我抽出来你们的SvgaParser修改了缓存代码，加了try-catch，没这个问题产生了。其实是否你们可以直接加一个try-catch呢？因为这么多用户的情况下，这个问题一定不可避免。crash比缓存不住来的影响面大的多

![image](https://user-images.githubusercontent.com/6269201/99621575-3557af80-2a63-11eb-8a6c-693e23220396.png)

**Comment by jin123d** [comment]
2.5.13 同样报这个问题，基本上都是vivo、oppo 5.0和6.0的机器

**Comment by diguagege** [comment]
> 2.5.13 同样报这个问题，基本上都是vivo、oppo 5.0和6.0的机器

兄弟你有怎么处理么？

**Comment by painld6** [comment]
明白了，晚点加上这个

**Comment by diguagege** [comment]
> 明白了，晚点加上这个

谢谢兄弟～

**Comment by jin123d** [comment]
> > 请问用的是什么版本？如果你们确保了目录是否存在后仍会出现，那可能要定位下具体问题，这个错误出现的可能性也不仅仅只是这一种，例如：在创建文件夹时如果在不确定父目录的父级是否存在时，最好用 mkdirs 方法创建；权限问题；存储空间不足等等，都可能引发这个 exception，建议打些 log 收集下
> 
> 我们使用的额是2.5.11版本，最后，我抽出来你们的SvgaParser修改了缓存代码，加了try-catch，没这个问题产生了。其实是否你们可以直接加一个try-catch呢？因为这么多用户的情况下，这个问题一定不可避免。crash比缓存不住来的影响面大的多
> 
> ![image](https://user-images.githubusercontent.com/6269201/99621575-3557af80-2a63-11eb-8a6c-693e23220396.png)

加上try-catch后影响文件下载吗？

**Comment by jin123d** [comment]
> > 2.5.13 同样报这个问题，基本上都是vivo、oppo 5.0和6.0的机器
> 
> 兄弟你有怎么处理么？

我是前几天在bugly里面看到这个问题，才来issue上搜到这个问题，暂时没有处理。

**Comment by diguagege** [comment]
> > > 请问用的是什么版本？如果你们确保了目录是否存在后仍会出现，那可能要定位下具体问题，这个错误出现的可能性也不仅仅只是这一种，例如：在创建文件夹时如果在不确定父目录的父级是否存在时，最好用 mkdirs 方法创建；权限问题；存储空间不足等等，都可能引发这个 exception，建议打些 log 收集下
> > 
> > 
> > 我们使用的额是2.5.11版本，最后，我抽出来你们的SvgaParser修改了缓存代码，加了try-catch，没这个问题产生了。其实是否你们可以直接加一个try-catch呢？因为这么多用户的情况下，这个问题一定不可避免。crash比缓存不住来的影响面大的多
> > ![image](https://user-images.githubusercontent.com/6269201/99621575-3557af80-2a63-11eb-8a6c-693e23220396.png)
> 
> 加上try-catch后影响文件下载吗？

不影响，只是影响缓存
