### ISSUE TITLE
java.util.zip.DataFormatException: incorrect header check

### ISSUE THREAD

**Issue by haegyeong** [svga/SVGAPlayer-Android#331]
加载改URL  http://vcn.dududsp.com/file/kg6417co_54ed49t4h8ez5f83ecdba4994.svga  会报这个异常 

![image](https://user-images.githubusercontent.com/15045081/100313654-06f04c00-2ff0-11eb-9e34-f597123c50a8.png)

代码如下：
File cacheDir = new File(getCacheDir(), "http");
        try {
            HttpResponseCache.install(cacheDir, 1024 * 1024 * 128);
            URL url = new URL("http://vcn.dududsp.com/file/kg6417co_54ed49t4h8ez5f83ecdba4994.svga");
            svgaParser.decodeFromURL(url, callback);
        } catch (Exception e) {
            e.printStackTrace();
        }

    SVGAParser.ParseCompletion callback = new SVGAParser.ParseCompletion() {
        @Override
        public void onComplete(SVGAVideoEntity videoItem) {
            svgaImageView.setVisibility(View.VISIBLE);
            svgaImageView.setVideoItem(videoItem);
            svgaImageView.stepToFrame(0, true);
            Log.e(TAG, "onComplete: 播放 data ");
        }

        @Override
        public void onError() {
            Log.e(TAG, "onError: 播放 data " );

        }
    };

**Comment by painld6** [comment]
是用什么版本呢？直接在 demo 上测试发现没有这个问题，可以正常播放

**Comment by grins2193285007** [comment]
同问，我的版本号是SVGAPlayer-Android:2.5.15，本地可以播放，网络播放不了

**Comment by grins2193285007** [comment]
> 是用什么版本呢？直接在 demo 上测试发现没有这个问题，可以正常播放

同问，我的版本号是SVGAPlayer-Android:2.5.15，本地可以播放，网络播放不了

**Comment by sichuanyl** [comment]
用https

**Comment by ifynn** [comment]
我也出现这个问题了，请问具体设么原因？
