### ISSUE TITLE
加载网络文件大于3M,就出现java.net.ProtocolException: unexpected end of stream

### ISSUE THREAD

**Issue by rng2020** [svga/SVGAPlayer-Android#334]
具体描述：
使用svgaParser.decodeFromURL(new URL(url), parseCompletionCallback);加载一个3.5M的svga文件，一段时间后直接回调onError(). 同一个文件测试四五次，能成功一次(下载并播放)【所以和文件没关系】。
出错的Log如下：
W/System.err: java.net.ProtocolException: unexpected end of stream
W/System.err:     at com.android.okhttp.internal.http.Http1xStream$FixedLengthSource.read(Http1xStream.java:396)
W/System.err:     at com.android.okhttp.okio.RealBufferedSource.read(RealBufferedSource.java:50)
W/System.err:     at com.android.okhttp.internal.http.HttpEngine$2.read(HttpEngine.java:779)
W/System.err:     at com.android.okhttp.okio.RealBufferedSource$1.read(RealBufferedSource.java:371)
W/System.err:     at com.opensource.svgaplayer.SVGAParser$FileDownloader$resume$1.run(SVGAParser.kt:59)
W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
W/System.err:     at java.lang.Thread.run(Thread.java:784)
使用的SVGA版本为：2.5.3
但是我使用了最新的2.5.14进行测试，同样存在该问题。
其他：又陆续测试其他几个svga文件，发现一个规律，稍微大点儿的文件大概率首次都会出现该问题，例如4.9M...

分析：同一个文件，有播放成功的情况，因此我觉得和文件没有关系，麻烦帮忙看下这个问题。谢谢！

**Comment by PonyCui** [comment]
如果一个 svga 文件那么大，应该让设计师重新设计。
