### ISSUE TITLE
播放带有声音的SVGA问题

### ISSUE THREAD

**Issue by extracod** [svga/SVGAPlayer-Android#337]
播放带有声音的SVGA确实有很大问题，多次播放后会造成播放不起，无回调，清除缓存无法再次加载有声音的svg,例如：http://static-user-test.kemiba.cn/gift_ani/341609146206090.svga，而且播放声音不完整，多次播放后无法再次播放

**Comment by painld6** [comment]
1、设置循环自动播放，无其他干预，没有复现
2、点击播放，正常播放完毕后再次重新点击播放，没有复现
3、点击播放，在播放过程中再次调用 startAnimation()，使其中断上次播放继而重新开始播放，并尝试数次，依然正常播放，没有复现

所以能否详细说下使用的是什么手机以及系统版本号，以及使用场景，我这边再测试了下

**Comment by lyzqw** [comment]
> 1、设置循环自动播放，无其他干预，没有复现
> 2、点击播放，正常播放完毕后再次重新点击播放，没有复现
> 3、点击播放，在播放过程中再次调用 startAnimation()，使其中断上次播放继而重新开始播放，并尝试数次，依然正常播放，没有复现
> 
> 所以能否详细说下使用的是什么手机以及系统版本号，以及使用场景，我这边再测试了下


在直播中, 播放本地文件, 红米note7, 多次播放音频SVGA, 会拿不到soungPool的回调

**Comment by painld6** [comment]
> 在直播中, 播放本地文件, 红米note7, 多次播放音频SVGA, 会拿不到soungPool的回调

这个多次播放，是每次播放都重新通过 SVGAParser 解析 svga 文件去播放，还是通过重新设置 SVGAVideoEntity 去播放？

**Comment by lyzqw** [comment]
> > 在直播中, 播放本地文件, 红米note7, 多次播放音频SVGA, 会拿不到soungPool的回调
> 
> 这个多次播放，是每次播放都重新通过 SVGAParser 解析 svga 文件去播放，还是通过重新设置 SVGAVideoEntity 去播放？

https 文件 下载本地后, 每次重新加载使用本地文件, 使用完clear资料, 重新设置SVGAVideoEntity来播放; 通过PR 找到有个人设置单例soungPool来解决, 合并后有所改善, 简单测试未发现问题了

**Comment by painld6** [comment]
> 通过PR 找到有个人设置单例soungPool来解决, 合并后有所改善, 简单测试未发现问题了

行，待完善后会做合并处理
