### ISSUE TITLE
java.io.FileNotFoundException

### ISSUE THREAD

**Issue by alienzh** [svga/SVGAPlayer-Android#339]
线上偶先 java.io.FileNotFoundException, 各大厂商的机型都有这个报错，暂时没找到复现路径。

java.lang.Error:java.io.FileNotFoundException: mini_answer_right.svga
--
 java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1168)
 ......
 Caused by:
 java.io.FileNotFoundException:mini_answer_right.svga
 android.content.res.AssetManager.openAsset(Native Method)
 android.content.res.AssetManager.open(AssetManager.java:390)
 android.content.res.AssetManager.open(AssetManager.java:364)
 com.opensource.svgaplayer.g$e.run(SVGAParser.kt:136)
 java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
 java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
 java.lang.Thread.run(Thread.java:764)

**Comment by painld6** [comment]
svga 版本是多少，以及使用的是 assets 加载还是 url 加载？

**Comment by daishengda2018** [comment]
看起来像资源没有打入包里啊

**Comment by alienzh** [comment]
> svga 版本是多少，以及使用的是 assets 加载还是 url 加载？
资源是打进去的，用assets加载的资源，svga 版本 SVGAPlayer-Android:2.5.9

**Comment by hvsimon** [comment]
```
// SVGAParser.kt

    fun decodeFromAssets(name: String, callback: ParseCompletion?) {
        if (mContext == null) {
            LogUtils.error(TAG, "在配置 SVGAParser context 前, 无法解析 SVGA 文件。")
            return
        }
        try {
            LogUtils.info(TAG, "================ decode from assets ================")
            threadPoolExecutor.execute {
                mContext?.assets?.open(name)?.let {
                    this.decodeFromInputStream(it, SVGACache.buildCacheKey("file:///assets/$name"), callback, true)
                }
            }
        } catch (e: java.lang.Exception) {
            this.invokeErrorCallback(e, callback)
        }
    }
```

如果 `open` 拋出 exception，是可以被外層 catch 的嗎？
這邊用到 `ExecutorService `，會需要不同的錯誤處理方式嗎？
