### ISSUE TITLE
contain unsafe unzipping patterns, which may potentially lead to a Zip Path Traversal attack

### ISSUE THREAD

**Issue by TaoSunkist** [svga/SVGAPlayer-Android#340]
## maven-version 
'com.github.svga:SVGAPlayer-Android:2.5.3'
## occur place
com.opensource.svgaplayer.SVGAParser.unzip(inputStream: InputStream, cacheKey: String)
## description 
https://support.google.com/faqs/answer/9294009
We recommend fixing this issue in your app by checking if canonical paths to unzipped files are underneath an expected directory. Specifically, before using a File object created using the return value of ZipEntry's getName() method, always check if the return value of File.GetCanonicalPath() belongs to the intended directory path. For example:
```
InputStream is = new InputStream(untrustedFileName);
ZipInputStream zis = new ZipInputStream(new BufferedInputStream(is));
while((ZipEntry ze = zis.getNextEntry()) != null) {
  File f = new File(DIR, ze.getName());
  String canonicalPath = f.getCanonicalPath();
  if (!canonicalPath.startsWith(DIR)) {
    // SecurityException
  }
  // Finish unzipping…
}
```

**Comment by painld6** [comment]
this problem has been fixed in later versions, you can try the new version 2.5.14

**Comment by xDragonZ** [comment]
Google still can't pick up this fix in latest version, maybe we need to use google recommended way to detect Zip Path Traversal Vulnerability
