### ISSUE TITLE
svga 动画，暂停后，再次恢复播放时候，先设置setImageDrawable 再调用stepToFrame(frame, true),动画依然不显示

### ISSUE THREAD

**Issue by qiushihang** [svga/SVGAPlayer-Android#341]
## Attention

* Do not ask any usage question, issue board is a issue board, accept library bugs only.
* If you are facing any usage problem, read the README again.

## Issue Template

Issue Description(What's your problem)

How To Reappear(How to reappear the issue)

Any Attachment(Provide a sample about your issue)

------ 中文分割线 ------

## 注意 

* 不要在 Issue 板块提问使用问题，Issue 板块只接受 Bug 反馈。
* 如果遇到使用上的问题，仔细阅读 README。

## Issue 模板

请尽量使用英文提交 Issue

请确切回答：问题的描述、重现方式、附件（提供一个 Demo 以重现问题）

**Comment by qiushihang** [comment]
![image](https://user-images.githubusercontent.com/59954939/105449748-ef61d680-5cb3-11eb-9434-d709d9e624d0.png)
断点调试了，发现stepToFrame 执行了内部的startAniamtion，但是仍然看不到动画

**Comment by qiushihang** [comment]
我按照下图方式，先decodeFromAssets整体解析，然后stepToFrame 就解决问题了
![image](https://user-images.githubusercontent.com/59954939/105453920-04dafe80-5cbc-11eb-8eaf-c2b44371b5db.png)

**Comment by ydslib** [comment]
@qiushihang 每次重新播放都必需要重新decode么？复用svgDrawable无法显示
