### ISSUE TITLE
播放带有声音的SVGA收不到回调

### ISSUE THREAD

**Issue by MicroBread** [svga/SVGAPlayer-Android#342]
部分机型加载带声音的网络资源svga动画收不到回调，不带声音的可正常播放。
机型：Redmi Note 8 Pro
系统版本：MIUI 10.4.9.0(PGGCNXM)  Android 9.0

**Comment by daishengda2018** [comment]
贴个资源出来呗，我们试试

**Comment by MicroBread** [comment]
> 贴个资源出来呗，我们试试

https://s.huahua777.com/donghua/gift_animation_zhenaidabaojian.svga
使用2.5.3和2.5.12及2.5.14版本都会出现

**Comment by painld6** [comment]
你们应用场景是如何？方便我们还原

**Comment by PonyCui** [comment]
https://github.com/svga/SVGAPlayer-Android/issues/322

**Comment by painld6** [comment]
已经更新到 2.6.0 了，可以看看文档上更新的内容作相应调整
