### ISSUE TITLE
关于在RecycleView中使用Svga动画，不能复用的问题（在#287 issue closed的基础上仍出现）

### ISSUE THREAD

**Issue by wodemisihuang** [svga/SVGAPlayer-Android#344]
在RecycleView中使用Svga动画，滑动时，依然有存在不能复用的情况，参照#287的做法，setClearsAfterDetached(false)，仍然不起作用

**Comment by wodemisihuang** [comment]
补充一点：测试设备：三星s8+

**Comment by painld6** [comment]
如果是 RecyclerView 的话，clearsAfterStop 最好设置为 false，不然内部资源也会标记为清除

**Comment by lazy2b** [comment]
有缓存么？试试下面的代码？
public class GiftAdapter extends RecyclerView.Adapter<GiftAdapter.GiftViewHolder> {
private Map<Gift, SVGAVideoEntity> giftMap = new HashMap<>();

@Override
public void onBindViewHolder(@NonNull GiftViewHolder holder, int position) {
    Gift gift = getItem(position);
    holder.svgaImageView.setClearsAfterDetached(false);
    SVGAVideoEntity entity = giftMap.get(gift);
    if (entity == null) {
        SVGAParser parser = new SVGAParser(holder.svgaImageView.getContext());
        try {
            parser.decodeFromURL(new URL(gift.svgaUrl), new SVGAParser.ParseCompletion() {
                @Override
                public void onComplete(@NonNull SVGAVideoEntity svgaVideoEntity) {
                    giftMap.put(gift, svgaVideoEntity);
                    holder.svgaImageView.setVideoItem(svgaVideoEntity);
                    holder.svgaImageView.startAnimation();
                }

                @Override
                public void onError() {

                }
            });
        } catch (MalformedURLException e) {
            e.printStackTrace();
        }
    } else {
        holder.svgaImageView.setVideoItem(entity);
        holder.svgaImageView.startAnimation();
    }

}

public void clearSvgaCache() {
    for (SVGAVideoEntity entity : giftMap.values()) {
        entity.clear();
    }
    giftMap.clear();
}

static class GiftViewHolder extends RecyclerView.ViewHolder {

    private SVGAImageView svgaImageView;

    public GiftViewHolder(@NonNull View itemView) {
        super(itemView);
        svgaImageView = itemView.findViewById(R.id._gift);
    }
}
}

**Comment by lazy2b** [comment]
> 在RecycleView中使用Svga动画，滑动时，依然有存在不能复用的情况，参照#287的做法，setClearsAfterDetached(false)，仍然不起作用

有缓存么？试试下面的代码？
public class GiftAdapter extends RecyclerView.Adapter<GiftAdapter.GiftViewHolder> {
private Map<Gift, SVGAVideoEntity> giftMap = new HashMap<>();

@override
public void onBindViewHolder(@nonnull GiftViewHolder holder, int position) {
Gift gift = getItem(position);
holder.svgaImageView.setClearsAfterDetached(false);
SVGAVideoEntity entity = giftMap.get(gift);
if (entity == null) {
SVGAParser parser = new SVGAParser(holder.svgaImageView.getContext());
try {
parser.decodeFromURL(new URL(gift.svgaUrl), new SVGAParser.ParseCompletion() {
@override
public void onComplete(@nonnull SVGAVideoEntity svgaVideoEntity) {
giftMap.put(gift, svgaVideoEntity);
holder.svgaImageView.setVideoItem(svgaVideoEntity);
holder.svgaImageView.startAnimation();
}

            @Override
            public void onError() {

            }
        });
    } catch (MalformedURLException e) {
        e.printStackTrace();
    }
} else {
    holder.svgaImageView.setVideoItem(entity);
    holder.svgaImageView.startAnimation();
}
}

public void clearSvgaCache() {
for (SVGAVideoEntity entity : giftMap.values()) {
entity.clear();
}
giftMap.clear();
}

static class GiftViewHolder extends RecyclerView.ViewHolder {

private SVGAImageView svgaImageView;

public GiftViewHolder(@NonNull View itemView) {
    super(itemView);
    svgaImageView = itemView.findViewById(R.id._gift);
}
}
}

**Comment by wodemisihuang** [comment]
这一段是我adapter中的代码，逻辑与你发的类似，没有什么效果
 if(showTimeRoom.cornerType == 1){
            item_room_svga.setVisibility(View.VISIBLE);
            item_room_svga.setLoops(SVGA_LOOP_TIMES);
            item_room_svga.setClearsAfterDetached(false);
            SVGAVideoEntity videoEntity = (SVGAVideoEntity) item_room_svga.getTag();
            if (videoEntity == null) {
                SVGAParser svgaParser = new SVGAParser(getContext());
                svgaParser.decodeFromAssets(WEEKLY_WISH_SVGA_FILE_NAME, new SVGAParser.ParseCompletion() {
                    @Override
                    public void onComplete(@NotNull SVGAVideoEntity videoItem) {
                        item_room_svga.setVideoItem(videoItem);
                        item_room_svga.startAnimation();
                        item_room_svga.setTag(videoItem);
                    }

                    @Override
                    public void onError() {

                    }
                });
            } else {
                item_room_svga.setVideoItem(videoEntity);
                item_room_svga.startAnimation();
            }
        }else{
            item_room_svga.setVisibility(View.GONE);
//            item_room_svga.clear();
        }


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "svga/SVGAPlayer-Android"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年2月3日(星期三) 中午12:11
收件人:&nbsp;"svga/SVGAPlayer-Android"<SVGAPlayer-Android@noreply.github.com&gt;;
抄送:&nbsp;"一头牛"<shmilynyf@foxmail.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [svga/SVGAPlayer-Android] 关于在RecycleView中使用Svga动画，不能复用的问题（在#287 issue closed的基础上仍出现） (#344)





  
在RecycleView中使用Svga动画，滑动时，依然有存在不能复用的情况，参照#287的做法，setClearsAfterDetached(false)，仍然不起作用
  
有缓存么？试试下面的代码？
 public class GiftAdapter extends RecyclerView.Adapter<GiftAdapter.GiftViewHolder&gt; {
 private Map<Gift, SVGAVideoEntity&gt; giftMap = new HashMap<&gt;();
 
@override
 public void onBindViewHolder(@nonnull GiftViewHolder holder, int position) {
 Gift gift = getItem(position);
 holder.svgaImageView.setClearsAfterDetached(false);
 SVGAVideoEntity entity = giftMap.get(gift);
 if (entity == null) {
 SVGAParser parser = new SVGAParser(holder.svgaImageView.getContext());
 try {
 parser.decodeFromURL(new URL(gift.svgaUrl), new SVGAParser.ParseCompletion() {
 @override
 public void onComplete(@nonnull SVGAVideoEntity svgaVideoEntity) {
 giftMap.put(gift, svgaVideoEntity);
 holder.svgaImageView.setVideoItem(svgaVideoEntity);
 holder.svgaImageView.startAnimation();
 }
         @Override         public void onError() {         }     }); } catch (MalformedURLException e) {     e.printStackTrace(); }  
} else {
 holder.svgaImageView.setVideoItem(entity);
 holder.svgaImageView.startAnimation();
 }
 }
 
public void clearSvgaCache() {
 for (SVGAVideoEntity entity : giftMap.values()) {
 entity.clear();
 }
 giftMap.clear();
 }
 
static class GiftViewHolder extends RecyclerView.ViewHolder {
 
private SVGAImageView svgaImageView;
 
public GiftViewHolder(@nonnull View itemView) {
 super(itemView);
 svgaImageView = itemView.findViewById(R.id._gift);
 }
 }
 }

**Comment by painld6** [comment]
> 这一段是我adapter中的代码，逻辑与你发的类似，没有什么效果 if(showTimeRoom.cornerType == 1){ item_room_svga.setVisibility(View.VISIBLE); item_room_svga.setLoops(SVGA_LOOP_TIMES); item_room_svga.setClearsAfterDetached(false); SVGAVideoEntity videoEntity = (SVGAVideoEntity) item_room_svga.getTag(); if (videoEntity == null) { SVGAParser svgaParser = new SVGAParser(getContext()); svgaParser.decodeFromAssets(WEEKLY_WISH_SVGA_FILE_NAME, new SVGAParser.ParseCompletion() { @override public void onComplete(@NotNull SVGAVideoEntity videoItem) { item_room_svga.setVideoItem(videoItem); item_room_svga.startAnimation(); item_room_svga.setTag(videoItem); } @override public void onError() { } }); } else { item_room_svga.setVideoItem(videoEntity); item_room_svga.startAnimation(); } }else{ item_room_svga.setVisibility(View.GONE); // item_room_svga.clear(); }
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "svga/SVGAPlayer-Android" <notifications@github.com&gt;; 发送时间:&nbsp;2021年2月3日(星期三) 中午12:11 收件人:&nbsp;"svga/SVGAPlayer-Android"<SVGAPlayer-Android@noreply.github.com&gt;; 抄送:&nbsp;"一头牛"<shmilynyf@foxmail.com&gt;;"Author"<author@noreply.github.com&gt;; 主题:&nbsp;Re: [svga/SVGAPlayer-Android] 关于在RecycleView中使用Svga动画，不能复用的问题（在#287 issue closed的基础上仍出现） (#344) 在RecycleView中使用Svga动画，滑动时，依然有存在不能复用的情况，参照#287的做法，setClearsAfterDetached(false)，仍然不起作用 有缓存么？试试下面的代码？ public class GiftAdapter extends RecyclerView.Adapter<GiftAdapter.GiftViewHolder&gt; { private Map<Gift, SVGAVideoEntity&gt; giftMap = new HashMap<&gt;(); @override public void onBindViewHolder(@nonnull GiftViewHolder holder, int position) { Gift gift = getItem(position); holder.svgaImageView.setClearsAfterDetached(false); SVGAVideoEntity entity = giftMap.get(gift); if (entity == null) { SVGAParser parser = new SVGAParser(holder.svgaImageView.getContext()); try { parser.decodeFromURL(new URL(gift.svgaUrl), new SVGAParser.ParseCompletion() { @override public void onComplete(@nonnull SVGAVideoEntity svgaVideoEntity) { giftMap.put(gift, svgaVideoEntity); holder.svgaImageView.setVideoItem(svgaVideoEntity); holder.svgaImageView.startAnimation(); } @override public void onError() { } }); } catch (MalformedURLException e) { e.printStackTrace(); } } else { holder.svgaImageView.setVideoItem(entity); holder.svgaImageView.startAnimation(); } } public void clearSvgaCache() { for (SVGAVideoEntity entity : giftMap.values()) { entity.clear(); } giftMap.clear(); } static class GiftViewHolder extends RecyclerView.ViewHolder { private SVGAImageView svgaImageView; public GiftViewHolder(@nonnull View itemView) { super(itemView); svgaImageView = itemView.findViewById(R.id._gift); } } } — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

请问有设置 SVGAImageView#clearsAfterStop 的属性为 false 吗？因为他默认值为 true，所以一旦播放完毕，他会标记该 SVGAImageView，则无法再次播放

**Comment by wodemisihuang** [comment]
大佬，方便的话，我传一个小视频给你看一眼，顺便贴上几个测试代码的java/kt文件




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "svga/SVGAPlayer-Android"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年2月3日(星期三) 中午12:11
收件人:&nbsp;"svga/SVGAPlayer-Android"<SVGAPlayer-Android@noreply.github.com&gt;;
抄送:&nbsp;"一头牛"<shmilynyf@foxmail.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [svga/SVGAPlayer-Android] 关于在RecycleView中使用Svga动画，不能复用的问题（在#287 issue closed的基础上仍出现） (#344)





  
在RecycleView中使用Svga动画，滑动时，依然有存在不能复用的情况，参照#287的做法，setClearsAfterDetached(false)，仍然不起作用
  
有缓存么？试试下面的代码？
 public class GiftAdapter extends RecyclerView.Adapter<GiftAdapter.GiftViewHolder&gt; {
 private Map<Gift, SVGAVideoEntity&gt; giftMap = new HashMap<&gt;();
 
@override
 public void onBindViewHolder(@nonnull GiftViewHolder holder, int position) {
 Gift gift = getItem(position);
 holder.svgaImageView.setClearsAfterDetached(false);
 SVGAVideoEntity entity = giftMap.get(gift);
 if (entity == null) {
 SVGAParser parser = new SVGAParser(holder.svgaImageView.getContext());
 try {
 parser.decodeFromURL(new URL(gift.svgaUrl), new SVGAParser.ParseCompletion() {
 @override
 public void onComplete(@nonnull SVGAVideoEntity svgaVideoEntity) {
 giftMap.put(gift, svgaVideoEntity);
 holder.svgaImageView.setVideoItem(svgaVideoEntity);
 holder.svgaImageView.startAnimation();
 }
         @Override         public void onError() {         }     }); } catch (MalformedURLException e) {     e.printStackTrace(); }  
} else {
 holder.svgaImageView.setVideoItem(entity);
 holder.svgaImageView.startAnimation();
 }
 }
 
public void clearSvgaCache() {
 for (SVGAVideoEntity entity : giftMap.values()) {
 entity.clear();
 }
 giftMap.clear();
 }
 
static class GiftViewHolder extends RecyclerView.ViewHolder {
 
private SVGAImageView svgaImageView;
 
public GiftViewHolder(@nonnull View itemView) {
 super(itemView);
 svgaImageView = itemView.findViewById(R.id._gift);
 }
 }
 }

**Comment by painld6** [comment]
> 大佬，方便的话，我传一个小视频给你看一眼，顺便贴上几个测试代码的java/kt文件

其实你可以直接写个 demo 到你的 github 上，然后贴个地址出来我们去看下也可以

**Comment by wodemisihuang** [comment]
大佬，这是测试代码的github地址
https://github.com/wodemisihuang/Svga-Animator-In-RecycleView.git


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "svga/SVGAPlayer-Android"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年2月7日(星期天) 凌晨0:20
收件人:&nbsp;"svga/SVGAPlayer-Android"<SVGAPlayer-Android@noreply.github.com&gt;;
抄送:&nbsp;"一头牛"<shmilynyf@foxmail.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [svga/SVGAPlayer-Android] 关于在RecycleView中使用Svga动画，不能复用的问题（在#287 issue closed的基础上仍出现） (#344)





  
大佬，方便的话，我传一个小视频给你看一眼，顺便贴上几个测试代码的java/kt文件
  
其实你可以直接写个 demo 到你的 github 上，然后贴个地址出来我们去看下也可以

**Comment by painld6** [comment]
> 大佬，这是测试代码的github地址 https://github.com/wodemisihuang/Svga-Animator-In-RecycleView.git

你去看下 pr，我改了部分代码，测试下来是没问题了

**Comment by nanxunwanfeng** [comment]
大家解决了吗，我也遇到了，拜谢各位大佬

**Comment by painld6** [comment]
> 大家解决了吗，我也遇到了，拜谢各位大佬

如果你的写法和原作者的一样，那你可以去看下我帮他改的那部分代码

**Comment by nanxunwanfeng** [comment]
我是用的BaseQuickAdapter 在这两个回调里面加了还是不行，可以帮忙看看吗
/**
 * @author GeYaoXiang
 * @description:
 */
public class MusicAdapter<T&gt; extends BaseQuickAdapter<T, BaseViewHolder&gt; {
    public String TAG, lastName = "";
    private SVGAImageView mSVGAImageView;
    private ImageView mImageView;
    private FrameLayout fl_svg;

    private MusicBean.DataBean.ListBean musicBean;

    public MusicAdapter(int layoutResId, String tag) {
        super(layoutResId);
        this.TAG = tag;
    }


    @Override
    protected void convert(BaseViewHolder helper, T item) {
        if (item == null) {
            return;
        }
        //通过tag将ViewHolder和itemView绑定
        helper.itemView.setTag(this);
        musicBean = (MusicBean.DataBean.ListBean) item;
        CircleProgressBar cpProgress = helper.getView(R.id.cp_progress);
        SwipeMenuLayout swipeMenuLayout = helper.getView(R.id.swipelayout);
        TextView btnDelete = helper.getView(R.id.btnDelete);
        if (TAG.equals("我的歌单")) {
            btnDelete.setBackgroundColor(mContext.getResources().getColor(R.color.red_ff6666));
            btnDelete.setTextColor(mContext.getResources().getColor(R.color.white));
            btnDelete.setText("删除");
        } else {
            btnDelete.setBackgroundColor(mContext.getResources().getColor(R.color.gray_f2f4f5));
            btnDelete.setTextColor(mContext.getResources().getColor(R.color.color_8A9199));
            btnDelete.setText("举报");
        }
        mImageView = helper.getView(R.id.iv_status);
        mSVGAImageView = helper.getView(R.id.iv_status_svg);
        mSVGAImageView.setClearsAfterDetached(false);
        mSVGAImageView.setClearsAfterStop(false);
        fl_svg = helper.getView(R.id.fl_svg);
        TextView name = helper.getView(R.id.tv_name);
        name.setText(musicBean.getName());
        lastName = musicBean.getName();
        helper.addOnClickListener(R.id.ll_layout)
                .addOnClickListener(R.id.btnDelete);
        cpProgress.setVisibility(View.GONE);

        if (musicBean.getStatus() != null) {
            if (!TextUtils.equals(musicBean.getStatus(), "1")) {
                if (mSVGAImageView.isAnimating()) {
                    mSVGAImageView.stopAnimation();
                }
            }
            switch (musicBean.getStatus()) {
                case "0":
                    fl_svg.setVisibility(View.VISIBLE);
                    mSVGAImageView.setVisibility(View.GONE);
                    mImageView.setVisibility(View.VISIBLE);
                    mImageView.setImageResource(R.drawable.live_music_play48_icon_nor);
                    break;
                case "1":
                    fl_svg.setVisibility(View.VISIBLE);
                    mSVGAImageView.setVisibility(View.VISIBLE);
                    mImageView.setVisibility(View.GONE);
                    if (!mSVGAImageView.isAnimating()) {
                        SvganimUtil.getInstance().startAnimt(Constant.LIVE_MUSIC_PLAYNOW_SVGA, mSVGAImageView);
                    }
                    break;
                case "2":
                    fl_svg.setVisibility(View.GONE);
                    cpProgress.setVisibility(View.VISIBLE);
                    cpProgress.setStatus(CircleProgressBar.Status.Loading);
                    cpProgress.setProgress(musicBean.getProgress());
                    break;
                case "3":
                    fl_svg.setVisibility(View.VISIBLE);
                    mSVGAImageView.setVisibility(View.GONE);
                    mImageView.setVisibility(View.VISIBLE);
                    mImageView.setImageResource(R.drawable.live_music_dow_icon_nor);
                    break;
                default:
                    break;
            }
        }
        swipeMenuLayout.addisExpandListner(new SwipeMenuLayout.isExpandListner() {
            @Override
            public void open(SwipeMenuLayout swipeMenuLayout) {

            }

            @Override
            public void close(SwipeMenuLayout swipeMenuLayout) {

            }
        });

    }

    @Override
    public void onViewAttachedToWindow(BaseViewHolder holder) {
        super.onViewAttachedToWindow(holder);
//        if (musicBean!=null&amp;&amp;musicBean.getStatus()!=null&amp;&amp;musicBean.getStatus().equals("1")) {
//
//        }
        if (mSVGAImageView!=null&amp;&amp;mSVGAImageView.isAnimating()) {
            mSVGAImageView.stopAnimation(false);
        }

    }

    @Override
    public void onViewDetachedFromWindow(@NonNull BaseViewHolder holder) {
        super.onViewDetachedFromWindow(holder);
//        if (musicBean!=null&amp;&amp;musicBean.getStatus()!=null&amp;&amp;musicBean.getStatus().equals("1")) {
//
//        }
        if (mSVGAImageView!=null&amp;&amp;!mSVGAImageView.isAnimating()) {
            SvganimUtil.getInstance().startAnimt(Constant.LIVE_MUSIC_PLAYNOW_SVGA, mSVGAImageView);
        }

    }
}





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "svga/SVGAPlayer-Android"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年2月8日(星期一) 中午11:36
收件人:&nbsp;"svga/SVGAPlayer-Android"<SVGAPlayer-Android@noreply.github.com&gt;;
抄送:&nbsp;"1055526137"<1055526137@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [svga/SVGAPlayer-Android] 关于在RecycleView中使用Svga动画，不能复用的问题（在#287 issue closed的基础上仍出现） (#344)





  
大家解决了吗，我也遇到了，拜谢各位大佬
  
如果你的写法和原作者的一样，那你可以去看下我帮他改的那部分代码

**Comment by painld6** [comment]
> 我是用的BaseQuickAdapter 在这两个回调里面加了还是不行，可以帮忙看看吗

你是不是写反了，onViewAttachedToWindow 是 startAnimation，onViewDetachedFromWindow 才是 stopAnimation
