### ISSUE TITLE
播放一个不存在的assets下的svga动画时将崩溃

### ISSUE THREAD

**Issue by wys619** [svga/SVGAPlayer-Android#357]
原因在于这里的try catch将无法捕获open方法抛出的异常：

https://github.com/svga/SVGAPlayer-Android/blob/7707a7cda7eceaf712da859d508195b72e933930/library/src/main/java/com/opensource/svgaplayer/SVGAParser.kt#L138

**Comment by painld6** [comment]
后续我们内部改下这个问题，但从理论上来说，这应该由业务层去判断文件是否存在才对

**Comment by shejishi** [comment]
新版本会有问题，旧版不会
```java
 threadPoolExecutor.execute {
                mContext?.assets?.open(name)?.let {
                    this.decodeFromInputStream(it, SVGACache.buildCacheKey("file:///assets/$name"), callback, true)
                }
            }
```
```java
mContext?.assets?.open(name)?.let {
                this.decodeFromInputStream(it, buildCacheKey("file:///assets/$name"), callback, true)
            }
```

**Comment by painld6** [comment]
> 新版本会有问题，旧版不会
> 
> ```java
>  threadPoolExecutor.execute {
>                 mContext?.assets?.open(name)?.let {
>                     this.decodeFromInputStream(it, SVGACache.buildCacheKey("file:///assets/$name"), callback, true)
>                 }
>             }
> ```
> 
> ```java
> mContext?.assets?.open(name)?.let {
>                 this.decodeFromInputStream(it, buildCacheKey("file:///assets/$name"), callback, true)
>             }
> ```

是，新版加了线程去处理耗时操作，但没有在内部捕获导致了这个问题
