### ISSUE TITLE
SVGAImageView点击事件

### ISSUE THREAD

**Issue by gaochang1993** [svga/SVGAPlayer-Android#358]
在断网情况下加载资源失败会导致SVGAImageView的点击事件没有响应，看源代码是SVGAImageView 是重写了onTouchEvent方法，在处理点击的时候，getDrawable为空的时候，返回false导致。这么做的出发点是什么？

**Comment by painld6** [comment]
是否查看的是的是最新源码吗？因为最新的并不是返回 false，而是交由上一级处理
