### ISSUE TITLE
在XML里面设置loopCount为1后，startAnimation一次结束后，如果想再次播放动画要怎么处理呢

### ISSUE THREAD

**Issue by ender115** [svga/SVGAPlayer-Android#363]
在XML里面设置loopCount为1后，startAnimation一次结束后，如果想再次播放动画要怎么处理呢，现在是第二次startAnimation后就没效果了

**Comment by painld6** [comment]
你的 SVGAImageView 是否有设置 setClearsAfterStop 为 false 呢？

**Comment by ender115** [comment]
没有设置，如果设置setClearsAfterStop为false的话是可以的，但是动画播放完成后会停留在最后一帧，我现在是在要用的时候通过动态创建SVGAImageView，添加到ViewGroup中，然后动画播放完成后再把SVGAImageView移除掉，要用的时候再创建添加，这样实现需求的。
不过是不是可以设置setClearsAfterStop为false，然后动画播放完成后设置SVGAImageView为GONE来实现，这个方式没试过，我现在通过动态添加的方式先做了

**Comment by PonyCui** [comment]
不建议使用 XML 方式实现复杂需求

**Comment by painld6** [comment]
> 没有设置，如果设置setClearsAfterStop为false的话是可以的，但是动画播放完成后会停留在最后一帧，我现在是在要用的时候通过动态创建SVGAImageView，添加到ViewGroup中，然后动画播放完成后再把SVGAImageView移除掉，要用的时候再创建添加，这样实现需求的。
> 不过是不是可以设置setClearsAfterStop为false，然后动画播放完成后设置SVGAImageView为GONE来实现，这个方式没试过，我现在通过动态添加的方式先做了

肯定的，你用基础的 Android 动画也一样，动画播放完要么回到第一帧，要么保持在最后一帧，如果你想播放完后隐藏，可以让设计师把 SVGA 最后一帧的所有元素去掉，或者就是设置监听播放完成后把 View 隐藏掉
