### ISSUE TITLE
SVGA Player sometime play, sometimes do not play

### ISSUE THREAD

**Issue by edmundsiah81** [svga/SVGAPlayer-Android#364]
## Attention

* Do not ask any usage question, issue board is a issue board, accept library bugs only.
* If you are facing any usage problem, read the README again.

## Issue Template

Issue Description(What's your problem)

How To Reappear(How to reappear the issue)

Any Attachment(Provide a sample about your issue)

------ 中文分割线 ------

## 注意 

* 不要在 Issue 板块提问使用问题，Issue 板块只接受 Bug 反馈。
* 如果遇到使用上的问题，仔细阅读 README。

## Issue 模板

请尽量使用英文提交 Issue

请确切回答：问题的描述、重现方式、附件（提供一个 Demo 以重现问题）

**Comment by edmundsiah81** [comment]
Hi Author,

I used your decodefromURL. Why sometime it play normally, & sometimes it does not decode & complete at all.

I have added this at my OnCreate function

parser = new SVGAParser(GoLiveStreamActivity.this);
File cacheDir = new File(getApplicationContext().getCacheDir(), "http");
try {
    HttpResponseCache.install(cacheDir, 1024 * 1024 * 128);
} catch (IOException e) {
    e.printStackTrace();
}

try {
        parser.decodeFromURL(new URL(playsvgaurl), new SVGAParser.ParseCompletion() {
            @Override
            public void onComplete(@NonNull SVGAVideoEntity svgaVideoEntity) {

                SVGADrawable drawable = new SVGADrawable(svgaVideoEntity);
                svgaImageView.setImageDrawable(drawable);
                svgaImageView.setLoops(1);
                svgaImageView.startAnimation();
            }

            @Override
            public void onError() {

            }
        });
    } catch (MalformedURLException e) {
        e.printStackTrace();
    }

    svgaImageView.setCallback(new SVGACallback() {
        @Override
        public void onPause() {

        }

        @Override
        public void onFinished() {
            svgaImageView.setVisibility(View.GONE);
            svgaanimating = false;
            svgaImageView.stopAnimation();
            svgaImageView.clearAnimation();
            svgaImageView.clear();
            svgaImageView.setCallback(null);
        }

        @Override
        public void onRepeat() {

        }

        @Override
        public void onStep(int i, double v) {

        }
    });

**Comment by painld6** [comment]
Try to set loopCount to 0 and see if it will appear again. It may be a loopCount problem

**Comment by edmundsiah81** [comment]
Hi,
After set to loopCount 0, it still the same, sometime play, sometime don't

**Comment by edmundsiah81** [comment]
what i did is that it based on triggering.
So every time when button is trigger, it will run this svgaplayer.
after the animation is done, i will switch off the animation.

During first trigger, it will works, however upon subsequence time trigger, it will sometime play, sometimes don't

**Comment by painld6** [comment]
Can you provide a Demo to reproduce the problem？It is also convenient for us to restore the usage

**Comment by edmundsiah81** [comment]
@Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_go_live_stream);
        ButterKnife.bind(this);
        
        parser = new SVGAParser(GoLiveStreamActivity.this);
        File cacheDir = new File(getApplicationContext().getCacheDir(), "http");
        try {
            HttpResponseCache.install(cacheDir, 1024 * 1024 * 128);
        } catch (IOException e) {
            e.printStackTrace();
        }
    }

**Comment by edmundsiah81** [comment]
function void animatesvga(){

                                svgaImageView.setVisibility(View.VISIBLE);
                                URL playsvga = null;
                                try {
                                    playsvga = new URL(playgifurl);
                                } catch (MalformedURLException e) {
                                    e.printStackTrace();
                                }

                                parser.decodeFromURL(playsvga, new SVGAParser.ParseCompletion() {
                                    @Override
                                    public void onComplete(@NotNull SVGAVideoEntity svgaVideoEntity) {

                                        SVGADrawable drawable = new SVGADrawable(svgaVideoEntity);
                                        svgaImageView.setImageDrawable(drawable);
                                        svgaImageView.setLoop(0);
                                        svgaImageView.startAnimation();

                                    }

                                    @Override
                                    public void onError() {

                                    }
                                });

                                gifthandler.removeCallbacks(giftrunnable);
                                giftrunnable = new Runnable() {
                                    @Override
                                    public void run() {
                                        
                                      
                                            svgaImageView.setVisibility(View.GONE);
                                            svgaanimating = false;
                                            svgaImageView.stopAnimation();
                                            svgaImageView.clearAnimation();
                                            svgaImageView.clear();
                                            svgaImageView.setCallback(null);
                                        
                                    }
                                };
                                gifthandler.postDelayed(giftrunnable, 10* 1000);
}

**Comment by edmundsiah81** [comment]
i have simply write above 2 codes.
So whenever trigger the function, it will display for 10 seconds before we stop the animation. 
then after that upon subsequence try, sometimes it display, sometimes it does not.

**Comment by edmundsiah81** [comment]
I realise that whenever I stop animation, when I try to start animation again, then it will sometimes play, sometimes do not play.


If I just hide the svga view, it will just keep playing without issues

**Comment by painld6** [comment]
Is it to call animatesvga to play after giftrunnable is executed? I tried it a few times here, but it didn't happen that it won't play. Also are you using the latest version? Finally, it is recommended to use SVGALogger to see what logs will be output inside SVGA, which is also convenient for troubleshooting

**Comment by edmundsiah81** [comment]
Hi Thanks for replying.

I realise it's due to one of the svga file issue.

When I tried to use other svga file it will perform normally even I set loop to 1.

Would you like to have that svga file to troubleshoot why your player didn't perform normally when running that file

**Comment by painld6** [comment]
Of course it is possible. If you agree to share the file, I can analyze the SVGA file. What is the difference compared to the normal one, so as to avoid this problem again。

**Comment by edmundsiah81** [comment]
https://firebasestorage.googleapis.com/v0/b/yume-live.appspot.com/o/banner_images%2F2021-06-08%2017%3A28%3A57.svga?alt=media&token=24b2c451-d3c6-404c-b111-92f146e868d9

**Comment by painld6** [comment]
#380
