### ISSUE TITLE
同时集成mpaas和SVGA，wire类文件冲突

### ISSUE THREAD

**Issue by lanran118** [svga/SVGAPlayer-Android#366]
##问题的描述
在项目中同时集成了svga库和mpaas框架，构建时报错 duplicate class in wire-runtime and wire-lite-runtime，尝试exclude module wire-runtime 或 wire-lite-runtime，能够打包，但无法使两者同时正常运行。求教，有什么办法可以解决？
##重现方式
在项目中同时集成SVGA库和mpaas框架的H5容器和RPC组件。

**Comment by PonyCui** [comment]
Fork 仓库后，自行解决 wire 冲突。
