### ISSUE TITLE
提一个api设计问题，版本2.5.15

### ISSUE THREAD

**Issue by Kuki93** [svga/SVGAPlayer-Android#371]
在SVGADrawable中为啥要设计这个属性
`var cleared = true`
有何意义？
这个属性设置成true只会导致drawable不能正常绘制，如果想达到清空视图的目的，完全可以使用`setImageDrawable(null)`，
cleared会导致出现问题难以排查。
另外在SVGADrawable中提供的clear()应该是由开发者主动调用，不应该在SVGAImageView自动触发这个方法，这会导致SVGADrawable资源被清空，变得不可用，SVGADrawable就无法被复用。并在SVGADrawable中提供相应的是否被isCleared()的方法，如在被clear后继续被使用，应抛出相对应的异常。

以上是个人的一点建议！

**Comment by PonyCui** [comment]
嗯，你说的有道理，确实应该由开发者调用 clear 方法清空资源。
