### ISSUE TITLE
Google still can't pick up this fix in latest version, maybe we need to use google recommended way to detect Zip Path Traversal Vulnerability

### ISSUE THREAD

**Issue by zx98cv12** [svga/SVGAPlayer-Android#373]
'com.github.svga:SVGAPlayer-Android:2.5.15'

GooglePlay:
Google still can't pick up this fix in latest version, maybe we need to use google recommended way to detect Zip Path Traversal Vulnerability

**Comment by painld6** [comment]
You can try version 2.6.0 later
