### ISSUE TITLE
动画还在播放声音播放一半就没声音了

### ISSUE THREAD

**Issue by daijunsheng** [svga/SVGAPlayer-Android#375]
动画还在播放声音播放一半就没声音了

**Comment by daijunsheng** [comment]
svga文件连接地址
链接：https://pan.baidu.com/s/1j-kxddcpNR0Y3Zvt78WJjA 
提取码：1111

**Comment by painld6** [comment]
> svga文件连接地址
> 链接：https://pan.baidu.com/s/1j-kxddcpNR0Y3Zvt78WJjA
> 提取码：1111

提取码不对，不过 svga 内部的音频是不是很长呢？一般来说 svga 内部音频不能太长，尽量在几秒内

**Comment by daijunsheng** [comment]
您好，要不您试试这个链接：
https://pan.baidu.com/s/1PVTUOgZqnNRy4HquMXS9DA 
提取码：qazx
我这边demo里面播放正常，链接里面只能播放5秒钟后面的就不能播放了，demo里面是可以正常播放到结束，麻烦有时间看下，谢了

**Comment by painld6** [comment]
demo 播放正常？链接里面只能播放 5 秒钟？你是想说本地播放没问题，通过 url 解析播放就有问题？

**Comment by senonwx** [comment]
我也遇到过这个问题，我们svga有长达15s的，而这个库源码使用的声音播放是soundPool，只能播放短音频。所以只能曲线救国啦，用无声svga配合能播放长音频的MediaPlayer使用。
方法是1.在ParseCompletion的onComplete回调中开启播放
2.在SVGACallback的onFinished中停止播放

**Comment by daijunsheng** [comment]
> demo 播放正常？链接里面只能播放 5 秒钟？你是想说本地播放没问题，通过 url 解析播放就有问题？

不好意思可能我表达不清楚，我是说链接也就是百度云盘那个链接，目前我是在demo里面测试，都是本地播放，我们svga有长达10几秒的只能播放一半，demo里面带的svga也就8秒能播放完成

**Comment by daijunsheng** [comment]
> 我也遇到过这个问题，我们svga有长达15s的，而这个库源码使用的声音播放是soundPool，只能播放短音频。所以只能曲线救国啦，用无声svga配合能播放长音频的MediaPlayer使用。
> 方法是1.在ParseCompletion的onComplete回调中开启播放
> 2.在SVGACallback的onFinished中停止播放

感谢大神

**Comment by painld6** [comment]
这个问题是因为 SoundPool 能播放的音频大致为 5s，你可以提取内部的音频并播放就知道了，但有人提交了一个方法，可以让 SVGA 内部音频回传给开发者本身，这样你们可以自行选择播放器去播放音频 #380

**Comment by huhb618923** [comment]
实测，可以将svga动画中的音频拆分成多段5s时长的，就可以正常播放音频了

**Comment by huhb618923** [comment]
> svga文件连接地址 链接：https://pan.baidu.com/s/1j-kxddcpNR0Y3Zvt78WJjA 提取码：1111

可以将svga中的音频拆成多个音频文件
