### ISSUE TITLE
repair some  svga contain mp3  can not callback  

### ISSUE THREAD

**Issue by SakyaZsl** [svga/SVGAPlayer-Android#378]
problem: some  svga contain mp3  can not callback  
#line  259 ----263
val fileTag = byteArray.slice(IntRange(0, 3))
 if (fileTag[0].toInt() == 73 && fileTag[1].toInt() == 68 && fileTag[2].toInt() == 51) {
                audiosDataMap[imageKey] = byteArray
            }
if  audio byteArray not start with  this     audiosFileMap.size==0   and  soundPool?.load  will not go  
so  setOnLoadCompleteListener {} will not in    
so  completionBlock() will not run  

videoItem.prepare {
                                LogUtils.info(TAG, "decode from input stream, inflate end")
                                this.invokeCompleteCallback(videoItem, callback)
                            }

prepare { } the unit will not run  

val audiosFileMap = generateAudioFileMap(entity)
        //should  callback   but  audio will not play 
        if(audiosFileMap.size==0 ){
            run(completionBlock)
        }

**Comment by PonyCui** [comment]
Please feel free to provide a PR.

**Comment by Adaclass** [comment]
PonyCui是外国的吗

**Comment by SakyaZsl** [comment]
> PonyCui是外国的吗

不知道  但是  if(audiosFileMap.size==0 ){
run(completionBlock)
}  这个能解决音频svga 不回调 但是无法播放声音

**Comment by painld6** [comment]
> > PonyCui是外国的吗
> 
> 不知道 但是 if(audiosFileMap.size==0 ){
> run(completionBlock)
> } 这个能解决音频svga 不回调 但是无法播放声音

感谢，目前推测根本原因大概率是 soundpool#load 同一个音频文件时会导致其中有一次调用 load 会失败，这个直接测试 soundpool 也是可以复现的，但还不能完全肯定就是这个问题

**Comment by SakyaZsl** [comment]
> Please feel free to provide a PR.

已经给官方提供pr 官方也合并进去 做了这个bug修复
