### ISSUE TITLE
当设置  SVGACache  的  type 为 Type.FILE 时，对于 zip 压缩的 svga 无法展示

### ISSUE THREAD

**Issue by Timor2016** [svga/SVGAPlayer-Android#383]
设置 type 为 Type.FILE 时 ，加载 zip 压缩的 svga 会报  DataFormatException

**Comment by painld6** [comment]
能否把 demo 或者 svga 文件发上来？不行的话，你可以直接发我邮箱也可以，在我主页可以看到

**Comment by Timor2016** [comment]
[这里是问题的Demo](http://appupdate.chaochaoke.top/SVGDemo.zip)
SVG 文件地址：
[会出现问题的地址](http://appupdate.chaochaoke.top/750x80.svga)
[不会出现问题的地址](http://appupdate.chaochaoke.top/MerryChristmas.svga

**Comment by painld6** [comment]
感谢提供的 demo，还是挺神奇的，我直接在项目中跑没有出现，你的 demo 倒是可以复现，目前已经修复并更新到 2.6.1 了
