### ISSUE TITLE
svga动画不能播放，web和ios都能正常播放

### ISSUE THREAD

**Issue by NieJianJian** [svga/SVGAPlayer-Android#386]
测试了很多svga文件都能正常播放，目前只发现这一个svga不能播放，ios和web都能正常播放。
资源地址：https://github.com/NieJianJian/AndroidNotes/blob/master/Picture/jingang.svga
麻烦看一下，谢谢

**Comment by painld6** [comment]
是不是播放出来后只有一个蓝色的圈？还是完全没有画面？

**Comment by NieJianJian** [comment]
> 是不是播放出来后只有一个蓝色的圈？还是完全没有画面？

是一个蓝色的圈

**Comment by NieJianJian** [comment]
> 是不是播放出来后只有一个蓝色的圈？还是完全没有画面？

1. 如果是资源的问题，那资源是触发了什么条件导致的吗？资源该如何调整？如果资源不调整，通过代码设置能否兼容？
2. 如果是代码的问题，能解吗？

**Comment by NieJianJian** [comment]
从源码跟踪来看，其实并不是动画没有播放，由于动图资源有一个圆圈背景色，背景色和动画元素的颜色一直，背景色设置了6%的透明度，但是透明度没有生效，所以就显示了蓝色大圆圈，还有部分矢量元素无法显示。
目前存在的问题：
1. 矢量元素的展示
2. 颜色透明度未生效
不知道我分析的对不对。后来全部改成非矢量元素，动画正常了

**Comment by Adaclass** [comment]
666

**Comment by NieJianJian** [comment]
矢量图可以绘制，问题的根本原因是alpha获取的值不对，背景色的为 #0f0084ff，按理说透明度是0.06%，但是在FrameEntity.decoe()方法中通过builder.alpha(ProtoAdapter.FLOAT.decode(reader))获取的alpha一直是1.0，所以导致透明度0.06的背景图绘制成了非透明的背景，把其他两个元素覆盖了，所以显示成了一个蓝色的圆。
那我理解，是不是解码器有问题？

**Comment by painld6** [comment]
> 矢量图可以绘制，问题的根本原因是alpha获取的值不对，背景色的为 #0f0084ff，按理说透明度是0.06%，但是在FrameEntity.decoe()方法中通过builder.alpha(ProtoAdapter.FLOAT.decode(reader))获取的alpha一直是1.0，所以导致透明度0.06的背景图绘制成了非透明的背景，把其他两个元素覆盖了，所以显示成了一个蓝色的圆。
> 那我理解，是不是解码器有问题？

![image](https://github.com/painld6/image_repository/blob/master/svga/issue386_1.png?raw=true)

那我先把了解到的说一下，我也 debug 解析器解析出来的 sprites，内部总共有 9 个 sprite，其中第 0 个 sprite 正是那个蓝色圆形，其中也可以看出 FrameEntity 中的 alpha 值为 1，也正是导致我一开始说的那样，蓝色圆形一直存在，但我一开始以为你们是设计蓝色的底，然后通过遮罩层完成整个 svga 动画，但我发现其他 sprite 都有设置颜色为 蓝色，所以就不太明白这个蓝色的圆形作用是做什么。。。

不过我也看到你说的设置 0.06% 的透明度，应该是这个数值没有用上吧，具体晚点我对应到代码上的逻辑后，再和你说下

**Comment by NieJianJian** [comment]
> > 矢量图可以绘制，问题的根本原因是alpha获取的值不对，背景色的为 #0f0084ff，按理说透明度是0.06%，但是在FrameEntity.decoe()方法中通过builder.alpha(ProtoAdapter.FLOAT.decode(reader))获取的alpha一直是1.0，所以导致透明度0.06的背景图绘制成了非透明的背景，把其他两个元素覆盖了，所以显示成了一个蓝色的圆。
> > 那我理解，是不是解码器有问题？
> 
> ![image](https://github.com/painld6/image_repository/blob/master/svga/issue386_1.png?raw=true)
> 
> 那我先把了解到的说一下，我也 debug 解析器解析出来的 sprites，内部总共有 9 个 sprite，其中第 0 个 sprite 正是那个蓝色圆形，其中也可以看出 FrameEntity 中的 alpha 值为 1，也正是导致我一开始说的那样，蓝色圆形一直存在，但我一开始以为你们是设计蓝色的底，然后通过遮罩层完成整个 svga 动画，但我发现其他 sprite 都有设置颜色为 蓝色，所以就不太明白这个蓝色的圆形作用是做什么。。。
> 
> 不过我也看到你说的设置 0.06% 的透明度，应该是这个数值没有用上吧，具体晚点我对应到代码上的逻辑后，再和你说下

好的

**Comment by NieJianJian** [comment]
> > 矢量图可以绘制，问题的根本原因是alpha获取的值不对，背景色的为 #0f0084ff，按理说透明度是0.06%，但是在FrameEntity.decoe()方法中通过builder.alpha(ProtoAdapter.FLOAT.decode(reader))获取的alpha一直是1.0，所以导致透明度0.06的背景图绘制成了非透明的背景，把其他两个元素覆盖了，所以显示成了一个蓝色的圆。
> > 那我理解，是不是解码器有问题？
> 
> ![image](https://github.com/painld6/image_repository/blob/master/svga/issue386_1.png?raw=true)
> 
> 那我先把了解到的说一下，我也 debug 解析器解析出来的 sprites，内部总共有 9 个 sprite，其中第 0 个 sprite 正是那个蓝色圆形，其中也可以看出 FrameEntity 中的 alpha 值为 1，也正是导致我一开始说的那样，蓝色圆形一直存在，但我一开始以为你们是设计蓝色的底，然后通过遮罩层完成整个 svga 动画，但我发现其他 sprite 都有设置颜色为 蓝色，所以就不太明白这个蓝色的圆形作用是做什么。。。
> 
> 不过我也看到你说的设置 0.06% 的透明度，应该是这个数值没有用上吧，具体晚点我对应到代码上的逻辑后，再和你说下

您好，请问这个问题有什么进展吗？

**Comment by painld6** [comment]
> > > 矢量图可以绘制，问题的根本原因是alpha获取的值不对，背景色的为 #0f0084ff，按理说透明度是0.06%，但是在FrameEntity.decoe()方法中通过builder.alpha(ProtoAdapter.FLOAT.decode(reader))获取的alpha一直是1.0，所以导致透明度0.06的背景图绘制成了非透明的背景，把其他两个元素覆盖了，所以显示成了一个蓝色的圆。
> > > 那我理解，是不是解码器有问题？
> > 
> > 
> > ![image](https://github.com/painld6/image_repository/blob/master/svga/issue386_1.png?raw=true)
> > 那我先把了解到的说一下，我也 debug 解析器解析出来的 sprites，内部总共有 9 个 sprite，其中第 0 个 sprite 正是那个蓝色圆形，其中也可以看出 FrameEntity 中的 alpha 值为 1，也正是导致我一开始说的那样，蓝色圆形一直存在，但我一开始以为你们是设计蓝色的底，然后通过遮罩层完成整个 svga 动画，但我发现其他 sprite 都有设置颜色为 蓝色，所以就不太明白这个蓝色的圆形作用是做什么。。。
> > 不过我也看到你说的设置 0.06% 的透明度，应该是这个数值没有用上吧，具体晚点我对应到代码上的逻辑后，再和你说下
> 
> 您好，请问这个问题有什么进展吗？

已经确认并修复了，现在再看另一个 issue 的问题，想看看今天能不能一起处理了，然后提个 pr

**Comment by painld6** [comment]
已经更新到 2.6.1 了

**Comment by NieJianJian** [comment]
> 已经更新到 2.6.1 了

好的，谢谢
