### ISSUE TITLE
SVGAImage怎么实现宽度充满屏幕，高度自适应啊

### ISSUE THREAD

**Issue by rng2020** [svga/SVGAPlayer-Android#389]
1、SVGAImage怎么实现宽度充满屏幕，高度自适应啊？scaleType设置的不能满足需求，且自定义也无效

**Comment by painld6** [comment]
目前来说是自适应，如果 SVGA 画面为 100 * 100，SVGAImageView 是 100 * 50，最后的绘制出来的效果是 50 * 50
其他方式和 ImageView 一样，设置对应的 scaleType 可以达到类似的效果，你说的是怎样的一个自适应？可以详细说下吗？

**Comment by rng2020** [comment]
好的，我明白了，我再想想, 谢谢。
