### ISSUE TITLE
获取缓存时报错

### ISSUE THREAD

**Issue by shenshuo** [svga/SVGAPlayer-Android#391]
## Attention

* Do not ask any usage question, issue board is a issue board, accept library bugs only.
* If you are facing any usage problem, read the README again.

## Issue Template

Issue Description(What's your problem)

How To Reappear(How to reappear the issue)

Any Attachment(Provide a sample about your issue)

------ 中文分割线 ------

## 注意 

* 不要在 Issue 板块提问使用问题，Issue 板块只接受 Bug 反馈。
* 如果遇到使用上的问题，仔细阅读 README。

## Issue 模板

请尽量使用英文提交 Issue

请确切回答：问题的描述、重现方式、附件（提供一个 Demo 以重现问题）

**Comment by shenshuo** [comment]
是不是缓存时没下载完 文件不完整没有自动删除啊

**Comment by painld6** [comment]
我这边没有这种情况，可以贴下错误信息吗？或者给个 Demo 或者链接试试

**Comment by shenshuo** [comment]
@painld6  实在抱歉我们服务端同学svga文件 配成了png图片 不好意思
