### ISSUE TITLE
it.setRequestProperty("Connection", "close")要删掉

### ISSUE THREAD

**Issue by DemaHamson** [svga/SVGAPlayer-Android#392]
https://github.com/svga/SVGAPlayer-Android/blob/9456d5823cd14b692e926b9ea5bb1c7b7f55397c/library/src/main/java/com/opensource/svgaplayer/SVGAParser.kt#L66

**Comment by painld6** [comment]
会有什么影响吗？理论上不需要说保持内部连接状态，后续你们可以通过缓存的 entity 去加载就足够了
