### ISSUE TITLE
【建议】希望SVGAParser callback?.onError()能传参Exception

### ISSUE THREAD

**Issue by kkmike999** [svga/SVGAPlayer-Android#395]
![image](https://user-images.githubusercontent.com/3726375/135385784-25e1e9ed-2be2-4406-9e7a-08ac0a8f398d.png)

希望`SVGAParser.ParseCompletion.onError()`接口，能增加`Exception`参数。SVGAParser调`invokeErrorCallback` `callback?.onError()`时，能把`Exception`回调给外部。

如果`Exception`不暴露出去，我们定位错误很难。例如svga报错，我们希望通过神策、本地日志能记录这个错误。希望团队能优化，不然得开发中改源码了

**Comment by painld6** [comment]
如果直接加这个参数会影响大部分已接入的开发者，所以，我们多了 SVGALogger，需要业务自己实现，具体实现方式看看文档
