### ISSUE TITLE
Android 10 occasionally plays an svga file with sound will not call back "pool_complete", resulting in no return from the "ParseCompletion" interface.

### ISSUE THREAD

**Issue by HelloJokerWord** [svga/SVGAPlayer-Android#398]
Android 10 偶发播放有声音的svga文件不会回调pool_complete ， 导致ParseCompletion接口无返回

source log:

![1634042350065_E7F7BA5E-EB07-4199-AFE1-993345ED1375](https://user-images.githubusercontent.com/18359626/136958871-8be35a94-1303-42ef-b75b-712c3edc846f.png)

step:
use  "parser.decodeFromInputStream()"  function  many time.

**Comment by WhitePhoenixv5870** [comment]
你好,我也遇到了这个问题,有时候收不到pool_complete这个回调,请问你是怎么解决的呢
![image](https://user-images.githubusercontent.com/28918738/142170606-5f246852-d51f-40a2-bbad-81f814221762.png)

**Comment by HelloJokerWord** [comment]
有个声音回调初始化一下。
SVGACache.INSTANCE.onCreate(sAppCallback.getAppContext(), SVGACache.Type.FILE);
SVGAParser.Companion.shareParser().init(sAppCallback.getAppContext());
SVGASoundManager.INSTANCE.init();



在 2021-11-17 17:08:41，"WhitePhoenixv5870" ***@***.***> 写道：

你好,我也遇到了这个问题,有时候收不到pool_complete这个回调,请问你是怎么解决的呢


—
You are receiving this because you modified the open/close state.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
