### ISSUE TITLE
文件本地缓存问题

### ISSUE THREAD

**Issue by 2022happynew** [svga/SVGAPlayer-Android#399]
跟com.opensource.svgaplayer.SVGAParser#decodeFromInputStream这个方法里面逻辑
1、如果是zip file,缓存文件不存在,然后就创建缓存dir，然后将解压的数据往这个缓存dir中写，最后读取缓存数据展示动画。
2、如果不是zip file， SVGACache 设置类型为 FILE，创建svgaFile缓存文件，然后往缓存文件写数据，最后展示动画。
这里有个疑问，SVGACache 设置类型为 DEFAULT的话，就没有缓存了，为什么不能在SVGACache 设置类型为 DEFAULT的时候，通过buildCacheDir创建缓存来缓存数据

**Comment by painld6** [comment]
因为 DEFAULT 应该代表是不缓存，FILE 表示缓存到本地，可能有点点误解

你可以看下之前他提 pr 时的说法
#293
