### ISSUE TITLE
SVGAImageView 支持wrap_content吗？

### ISSUE THREAD

**Issue by Labmem003** [svga/SVGAPlayer-Android#4]
SVGAImageView 的宽高必须固定吗？怎么做到类似 wrap_content 的效果，让素材有多大View就多大。

**Comment by PonyCui** [comment]
可以在下个版本添加这个支持

**Comment by PonyCui** [comment]
经过考虑，我们决定不支持这个功能，具体的原因，和 Fresco 库是一致的。
https://www.fresco-cn.org/docs/wrap-content.html

**Comment by Labmem003** [comment]
明白。我还是用 ugly 的方法来干这个 ugly thing 吧。
