### ISSUE TITLE
 java.lang.OutOfMemoryError: Failed to allocate a 16 byte allocation with 0 free bytes and 3GB until OOM

### ISSUE THREAD

**Issue by 13120241790** [svga/SVGAPlayer-Android#408]
PID: 12878
    Reason: Input dispatching timed out (Waiting to send non-key event because the touched window has not finished processing certain input events that were delivered to it over 500.0ms ago.  Wait queue length: 42.  Wait queue head age: 5576.9ms.)
    Load: 14.11 / 13.48 / 13.18
    CPU usage from 135804ms to 0ms ago (2022-01-19 19:20:40.482 to 2022-01-19 19:22:56.285):
......
     
 101% 12878/com.thunder.ktv: 99% user + 1.9% kernel / faults: 891 minor
        57% 12878/com.thunder.ktv: 57% user + 0% kernel
        28% 13071/SVGAParse
2022-01-19 19:23:01.952 12878-12887/com.thunder.ktv E/System: Uncaught exception thrown by finalizer
2022-01-19 19:23:06.597 12878-12878/com.thunder.ktv E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.thunder.ktv, PID: 12878
    java.lang.OutOfMemoryError: Failed to allocate a 16 byte allocation with 0 free bytes and 3GB until OOM

1 没用缓存纯标准用法
2 场景：一个弹窗里面使用 svga 快速的关闭这个弹窗然后再点开再关闭在点开 2 ~ 3 次就直接给应用干死了

尝试调用如下代码去解决，未取得效果

initview(){
svgaImageView.setClearsAfterDetached(true);
}

    @Override
    public void onDismiss() {
        if (svgaImageView != null) {
            svgaImageView.stopAnimation(true);
            svgaImageView = null;
        }
        super.onDismiss();
    }

**Comment by PonyCui** [comment]
先看看动画文件本身有没有问题？

**Comment by 13120241790** [comment]
动画本身没有问题 只是帧数稍微多一点 svga 2.9MB 我加您Q或者wx文件发给您？ ，如果不是快速关闭弹窗 再打开播放是正常的 。崔神再请教下如何去看这个 svga 的动画的内存大小呢？ 

svgaVideoEntity.getFrames() 只能看到帧数

**Comment by PonyCui** [comment]
这是文件大小 2.9M 吧？内存占用呢，可以到 https://svga.io 查看内存占用。

**Comment by 13120241790** [comment]
1 您好 崔神   https://svga.io/intro.html 的 介绍 集成指南 社区生态  都点了 没有看到可查看内存占用的工具，https://www.nangonghan.com/svga/ 这个可以预览以及帧数 

2 是的 svga 的文件 2.9MB

3 弹窗开启关闭反复几次就 oom 应该是 parser 解析还没解析完 关闭弹窗再开启又触发了下一次 parser 去解析 svga 文件，可否提供一个类似中断解析的接口 这样应该能解决这类场景的问题

**Comment by 13120241790** [comment]
[freqyen.svga.zip](https://github.com/svga/SVGAPlayer-Android/files/7901998/freqyen.svga.zip)

**Comment by PonyCui** [comment]
内存占用：211.72 M

**Comment by PonyCui** [comment]
全是序列帧，让设计师重新导出吧。

**Comment by 13120241790** [comment]
好吧，谢谢了。
