### ISSUE TITLE
UI设计需要注意什么

### ISSUE THREAD

**Issue by wilsonchouu** [svga/SVGAPlayer-Android#42]
Pony大大您好，最近接触到这个库觉得非常棒，很好改善了UI和猿猿的亲（si）密（bi）关系~ 希望大大能指教一下AE导出动画内存占用过大的问题，例如需要注意的地方是哪些等等，毕竟猿猿看到UI的头发都快挠没了也十分心（kai）疼（xin）。

**Comment by PonyCui** [comment]
我们在 AE 转换器中也发现了这个 BUG，正在想办法修复，请耐心等候一下。

**Comment by PonyCui** [comment]
临时的解决方案是，先把矢量的图层转换成智能对象，再放入 AE 中。
后续的解决方案是，我们会在 AE 转换器上修正这个问题，这个问题是由 Adobe 导致的。

**Comment by PonyCui** [comment]
@wilsonchouu 这个问题已经修复了，更新 AE 插件重新导出就可以。
https://github.com/yyued/SVGA-AEConverter/issues/11
