### ISSUE TITLE
文件占用内存19.29M，frames=241，vivo手机加载很慢，内存容易爆掉

### ISSUE THREAD

**Issue by chenjx888** [svga/SVGAPlayer-Android#426]
## 文件占用内存19.29M，frames=241，vivo手机加载很慢，内存容易爆掉
机型：vivo IQOO Neo5
系统：android12
player版本：2.6.1
文件地址：https://github.com/chenjx888/svga/blob/main/1651892151.svga

**Comment by PonyCui** [comment]
建议在低端机上做一下效果降级

**Comment by chenjx888** [comment]
我还有另一台三星Note8，手机比这台vivo的要低，怎么加载这个文件都没问题

**Comment by chenjx888** [comment]
好像vivo/oppo的手机会有问题，用户反馈上来的几乎都是vivo的，华为就没事

**Comment by PonyCui** [comment]
可能你需要在 demo 工程里复现一下问题了，我手上没有这台手机。
