### ISSUE TITLE
内存泄露

### ISSUE THREAD

**Issue by leviluo** [svga/SVGAPlayer-Android#433]
<img width="886" alt="截屏2022-06-07 19 54 47" src="https://user-images.githubusercontent.com/19730473/172373117-6a48389f-722f-49e3-b030-870c6f65d4b4.png">
<img width="1069" alt="截屏2022-06-07 19 54 05" src="https://user-images.githubusercontent.com/19730473/172373137-83d57df0-5077-446b-a448-68910cc4ab38.png">
<img width="1287" alt="截屏2022-06-07 20 05 31" src="https://user-images.githubusercontent.com/19730473/172374900-1f7a3e2b-4a8c-4912-8056-1bdb74865d45.png">

groupsessionactivity关闭后 recyclerView列表中自定义View的svga内存泄露，怎么治？

**Comment by NathanLi** [comment]
请问你怎么解决的啊？
