### ISSUE TITLE
为什么在加载内存比较大的图片时会内存溢出

### ISSUE THREAD

**Issue by mlzhang920802** [svga/SVGAPlayer-Android#46]
1 dalvik.system.VMRuntime.newNonMovableArray(Native Method)
--
2 android.graphics.BitmapFactory.nativeDecodeByteArray(Native Method)
3 android.graphics.BitmapFactory.decodeByteArray(BitmapFactory.java:526)
4 android.graphics.BitmapFactory.decodeByteArray(BitmapFactory.java:549)
5 com.opensource.svgaplayer.SVGAVideoEntity.resetImages(SVGAVideoEntity.kt:80)
6 com.opensource.svgaplayer.SVGAVideoEntity.<init>(SVGAVideoEntity.kt:54)
7 com.opensource.svgaplayer.SVGAParser.parse(SVGAParser.kt:169)
8 com.opensource.svgaplayer.SVGAParser.access$parse(SVGAParser.kt:23)
9 com.opensource.svgaplayer.SVGAParser$parse$5.run(SVGAParser.kt:96)
10 java.lang.Thread.run(Thread.java:818)

**Comment by PonyCui** [comment]
这不是很正常吗？你加载一张国际地图大小的 PNG 你的机器会不崩吗？

**Comment by PonyCui** [comment]
找设计师把素材优化
