### ISSUE TITLE
kingset.svga这个文件旋转问题

### ISSUE THREAD

**Issue by xieyangxuejun** [svga/SVGAPlayer-Android#49]
还有一个是alarm.svga这个文件旋转会偏移.请问怎么解决.我试了其他素材旋转没有问题.
刚开始以为是canvas画的时候问题,我在canvas上加了旋转角度也不对..我在考虑是否是素材有问题?

**Comment by PonyCui** [comment]
请具体描述问题

**Comment by xieyangxuejun** [comment]
旋转的时候,渲染的时候会混乱

**Comment by PonyCui** [comment]
请提供一个可重现的 Demo

**Comment by PonyCui** [comment]
@errnull 请确认一下问题

**Comment by errnull** [comment]
下了你这个Demo 好像没看明白是什么问题。
麻烦你可以提供一下联系方式我吗？

**Comment by xieyangxuejun** [comment]
旋转一下就看见了

**Comment by xieyangxuejun** [comment]
我的QQ729104978，不明白的话，可以找我确定问题…

**Comment by errnull** [comment]
已私聊，确定是 issue 会更新到这里。
