### ISSUE TITLE
怎么动态加载assets中的文件？

### ISSUE THREAD

**Issue by onecoders** [svga/SVGAPlayer-Android#5]
demo和介绍都没有提到如何动态加载assets中的svga文件，请问，如何动态加载？有提供相应的方法么

**Comment by PonyCui** [comment]
https://github.com/yyued/SVGAPlayer-Android/blob/master/library/src/main/java/com/opensource/svgaplayer/SVGAParser.kt
fun parse(assetsName: String, callback: ParseCompletion)
