### ISSUE TITLE
svga文件超过1000kb，导致播放动画的时候没有播放完成直接走onfinished回调，或者oom

### ISSUE THREAD

**Issue by wzhangmoumou** [svga/SVGAPlayer-Android#54]
如题

**Comment by PonyCui** [comment]
一般 SVGA 文件不会超过 1000kb

**Comment by wzhangmoumou** [comment]
我们项目里面有，svga文件1200多K，有什么解决办法没 @PonyCui

**Comment by xieyangxuejun** [comment]
对象回收和销毁方法 参考 https://github.com/xieyangxuejun/SVGAPlayer-Android/blob/master/app/src/main/java/com/foretree/player/DemoActivity.kt

**Comment by wonxll** [comment]
我们的好像也是序列帧，不然用啥做呢
