### ISSUE TITLE
同一个SVGA动画在Android端和其它端显示的效果不一致

### ISSUE THREAD

**Issue by xchdong** [svga/SVGAPlayer-Android#56]
同一个SVGA动画在浏览器，ios，h5显示的都是灰色的背景。在Android显示的是黑色的背景。这个问题应该怎么解？用的版本：2.1.1
这是SVGA官网显示效果：
![hi hzu_u 9 44nci c1tb](https://user-images.githubusercontent.com/24906931/39036077-ff59e336-44ae-11e8-9d9e-cb58b5d8ac1b.png)
这是Android端显示效果：
![np l_ etkayn5sdzk vq11o](https://user-images.githubusercontent.com/24906931/39036086-060f2e20-44af-11e8-8b61-eca1a99cae79.jpg)

**Comment by PonyCui** [comment]
请提供一下 SVGA 文件和源文件，发送至 help@svga.io

**Comment by PonyCui** [comment]
有一个 BUG 存在于 AE 中，如果是这个问题，请让设计师修改一下。
形状的透明度会被忽略，需要将透明度设置至图层中。

**Comment by xchdong** [comment]
设计师做了修改，bug已经解决。感谢支持
