### ISSUE TITLE
发现在 三星 Galaxy A5 ， Android 4.4.4 上面都放不了动画

### ISSUE THREAD

**Issue by W-quan** [svga/SVGAPlayer-Android#57]
之前是用     com.github.yyued:SVGAPlayer-Android:2.0.4-okio-1.13.0

**Comment by W-quan** [comment]
另外，发现在  三星 Galaxy A5  ， Android 4.4.4 上面都放不了动画

**Comment by PonyCui** [comment]
你看看开发者选项 - 动画缩放一项，是不是关闭了。

**Comment by W-quan** [comment]
发觉是我们后台有问题。
