### ISSUE TITLE
内存泄漏问题

### ISSUE THREAD

**Issue by wangyoucheng** [svga/SVGAPlayer-Android#66]
在多次播放的时候会偶发性出现内存泄漏(OOM)问题。这个现在有优化吗？

**Comment by PonyCui** [comment]
一般情况下是 SVGA 文件本身存在问题

**Comment by lgengsy** [comment]
svga文件本身为什么会导致内存泄漏？

**Comment by PonyCui** [comment]
@lgengsy  设计不当的 SVGA 文件，素材展开后会占据相当大的内存，最终导致系统无法回收。

**Comment by lgengsy** [comment]
How to avoid

**Comment by PonyCui** [comment]
在设计师使用工具导出时，就会提示内存占用值，越低越好。
