### ISSUE TITLE
demo下载了只能播放资源动画，网络加载的并没有用

### ISSUE THREAD

**Issue by CrackgmKey** [svga/SVGAPlayer-Android#68]
不知道是我没用好还是啥问题，网上查资料寥寥无几 几乎么有这个框架的

**Comment by PonyCui** [comment]
## Issue Template

Issue Description(What's your problem)

How To Reappear(How to reappear the issue)

Any Attachment(Provide a sample about your issue)

------ 中文分割线 ------

## Issue 模板

请尽量使用英文提交 Issue

请确切回答：问题的描述、重现方式、附件（提供一个 Demo 以重现问题）
