### ISSUE TITLE
项目和腾讯云liteavsdk.jar有冲突。

### ISSUE THREAD

**Issue by z2045217** [svga/SVGAPlayer-Android#7]
作者能看下怎么解决了吗？

**Comment by z2045217** [comment]
compile ('com.github.yyued:SVGAPlayer-Android:2.0.0') {
        exclude module: 'annotations'
    }

**Comment by z2045217** [comment]
我这么导入解决了
 compile ('com.github.yyued:SVGAPlayer-Android:2.0.0') {
        exclude module: 'annotations'
    }

**Comment by PonyCui** [comment]
因为 Kotlin 依赖了 annotations 导致的，非常感谢你提供解决方案。

**Comment by z2045217** [comment]
可以增加一个动画正在展示的方法吗。isAnimation();

**Comment by z2045217** [comment]
可以增加一个动画是否正在展示的方法吗。isAnimation();
