### ISSUE TITLE
导出SVG文件提示内存占用超过8M，可能导致目标应用奔溃

### ISSUE THREAD

**Issue by DevXue** [svga/SVGAPlayer-Android#71]
设计师在导出SVG文件的时候，提示内存占用超过8M，可能导致目标应用奔溃，    而且之前的文件比这个还要大 还要复杂，也没有提示这个内存超过8M的问题，  然而这次就出现了， 请问大佬这个是啥原因？ 谢谢
![sa](https://user-images.githubusercontent.com/9455329/40697475-eb91e00c-63fc-11e8-9535-79a69daff5b0.png)

**Comment by DevXue** [comment]
@PonyCui

**Comment by DevXue** [comment]
大佬，  这个生成svg 对 源文件有什么要求吗(aep文件)？  比如说文件大小，  文件动画效果时长 有什么限制要求吗？   我们设计师设计的生成svg后  发现文件90M以上了 ，   而且播放没效果  卡死了···
@PonyCui

**Comment by PonyCui** [comment]
内存占用高，就代表设计有问题，只能找设计师解决问题。

**Comment by PonyCui** [comment]
我估计是你的设计师偷懒使用序列帧导出给你了，这是绝对禁止的。

**Comment by DevXue** [comment]
@PonyCui   嗯嗯，谢大佬回复，    设计师设计的东西有160多张图片 ， 刚开始导出是svg的时候 提示什么  after effect警告：撤销组不匹配，请尝试修复。后来修改了后 90多张图，现在生成svg后 大小为2.2M 也可以运行成功！
  大佬  我还是不明白设计师那边咋搞，  你有什么建议吗？  我转告一下设计师！

**Comment by PonyCui** [comment]
设计师的事情让设计师解决就好

**Comment by DevXue** [comment]
谢谢
