### ISSUE TITLE
这个必须在xml文件中执行动画效果吗？

### ISSUE THREAD

**Issue by DevXue** [svga/SVGAPlayer-Android#72]
我的界面中要加载多个svg文件， 起码有10个以上吧，  看了下demo 没有Java代码控制加载svg的方法， 
我担心的是 我把这些svg全部写到布局中  加载出来会内存溢出····     而且控制显示隐藏很麻烦，  请问是我没有找到相关的方法呢？ 还是这个库目前就是不支持Java代码控制加载svga，   求帮助  谢谢！
@PonyCui

**Comment by PonyCui** [comment]
https://github.com/yyued/SVGAPlayer-Android#code
