### ISSUE TITLE
大佬，2.1.1不是最新的吧？

### ISSUE THREAD

**Issue by DevXue** [svga/SVGAPlayer-Android#73]
我现在用的是2.1.1版本， 但是我在Demo中看到SVGADynamicEntity 这个类 和我引入的2.1.1一点也不一样！
如图：
2.1.1  进入的 SVGADynamicEntity类截图
![0cb dm3 39o 2nzl3 rom_m](https://user-images.githubusercontent.com/9455329/40928299-8bc1a940-6853-11e8-9a2e-0be53248284f.png)
Demo中 SVGADynamicEntity类截图
![demo](https://user-images.githubusercontent.com/9455329/40928320-95bb034c-6853-11e8-95d4-d495a6fce519.png)

@PonyCui

**Comment by PonyCui** [comment]
https://jitpack.io/#yyued/SVGAPlayer-Android/
2.1.4
