### ISSUE TITLE
jitpack上已经找不到这个项目了？

### ISSUE THREAD

**Issue by jwdtommy** [svga/SVGAPlayer-Android#75]
访问http://jitpack.io/com/github/yyued/SVGAPlayer-Android/2.1.4/SVGAPlayer-Android-2.1.4.pom

返回
<a href="https://jitpack.io/com/github/yyued/SVGAPlayer-Android/2.1.4/SVGAPlayer-Android-2.1.4.pom">Moved Permanently</a>.
是说这个项目永久转移了？

**Comment by PonyCui** [comment]
你到墙外看看
