### ISSUE TITLE
关于动画暂停以后如何接着播放？

### ISSUE THREAD

**Issue by Kuki93** [svga/SVGAPlayer-Android#76]
暂停以后继续调用startAnimation会重头开始播放。
虽然提供了stepToFrame方法，但是无法知道当前是多少frame

**Comment by Kuki93** [comment]
@PonyCui 非常感谢，我之前没注意这个回调方法。
还想请教一下，parser.parse(InputStream inputStream,String cacheKey,ParseCompletion callback);
这个方法中cachekey是指什么，这个方法可以实现缓存吗？

**Comment by PonyCui** [comment]
你可以忽略这个 key 的，就是，你可以随便传一个 key 进去。

**Comment by clunyes** [comment]
哪个回调

**Comment by qiushihang** [comment]
在回调中拿到当前播放帧后，设置setImageDrawable 再 执行stepToFrame 仍然没有动画出现？这个怎么解决

**Comment by Kuki93** [comment]
> 在回调中拿到当前播放帧后，设置setImageDrawable 再 执行stepToFrame 仍然没有动画出现？这个怎么解决

为什么要重新set drawable
