### ISSUE TITLE
there is missing Supported After Effects Features

### ISSUE THREAD

**Issue by leleliu008** [svga/SVGAPlayer-Android#77]
Hi, 
    I'm a Lottie user, recently, I am focus on SVGAPlayer, I want to use SVGAPlayer instead of Lottie, so I use Converter for After Effects generate .svga file, these AE source files have been working well on Lottie, so I want to know SVGAPlayer Supported After Effects Features list, thank you!

**Comment by PonyCui** [comment]
We are writing now.

**Comment by errnull** [comment]
https://docs.qq.com/sheet/DT3Z2ektWRnZPaFJM?c=A1A0A0
Related documents here
