### ISSUE TITLE
缓存支持

### ISSUE THREAD

**Issue by cxrenbin** [svga/SVGAPlayer-Android#78]
想给框架加缓存管理，不知道怎么下手。。有缓存方面的demo嘛

**Comment by PonyCui** [comment]
see https://github.com/yyued/SVGAPlayer-Android#cache

**Comment by socker565** [comment]
据分析你的源码得知，在cache目录下，目前只支持HttpResponseCache的网络请求cache和文件cache两种；但缓存目录下有“movie.binary”和"movie.spec"没给出Api上的解释，是否这两部分cache也可以为我们所用？
