### ISSUE TITLE
能否增加一个是否正在播放动画。

### ISSUE THREAD

**Issue by z2045217** [svga/SVGAPlayer-Android#8]
这个方法对我们项目很重要。希望作者能考虑下。因为动画是否正常结束，能否回调finish监听，开发者无法知道。错误情况下队列无法判断是否进行下个动画。

**Comment by PonyCui** [comment]
下一版本加入

**Comment by PonyCui** [comment]
https://github.com/yyued/SVGAPlayer-Android/commit/8e29235239edb86b097785379a80e8dec6ffc5b9
Add at Tag 2.0.1

**Comment by z2045217** [comment]
非常感谢。
