### ISSUE TITLE
小米4横屏动画展示不全

### ISSUE THREAD

**Issue by eterualrb** [svga/SVGAPlayer-Android#82]
### 小米4手机横屏画面时展示的动画不全(如下视频：左侧是小米5s的效果，右侧是小米4的效果)
![_88e63a1f-e2b6-41ea-8cd9-c35cf5d0b2bb](https://user-images.githubusercontent.com/8297450/45070608-a9b50b00-b104-11e8-9d17-d2bfdd62bab6.png)
### 测试svga文件如下：
[Uploading 测试svga.zip…]()

**Comment by PonyCui** [comment]
可能跟分辨率有关，看看怎么解决这个问题。@errnull

**Comment by errnull** [comment]
你好，测试的 SVGA 文件链接似乎有误。

**Comment by eterualrb** [comment]
[test_svga.zip](https://github.com/yyued/SVGAPlayer-Android/files/2359924/test_svga.zip)
 再试下

**Comment by eterualrb** [comment]
再补充个问题：我在 http://svga.io/svga-preview.html 上预览的时候白色线条是有透明度的，但是在android手机上运行起来发现没有透明度效果，ios是有效果的
![_786af2c9-ab47-40b5-941c-d4ce6e581581](https://user-images.githubusercontent.com/8297450/45205092-bdeb3a80-b2b3-11e8-9452-d9dcfd70265a.png)

**Comment by PonyCui** [comment]
@eterualrb 透明度的问题已经在最新版本中解决。
