### ISSUE TITLE
Android端和http://svga.io/svga-preview.html展示的效果不一致

### ISSUE THREAD

**Issue by hzl123456** [svga/SVGAPlayer-Android#84]
同样的一个svga动画在android手机（华为荣耀v9）和 http://svga.io/svga-preview.html 界面展示的效果不一致（外圈扩散的透明效果消失了）。
![android端](https://user-images.githubusercontent.com/11958961/45674898-9e2ffe00-bb60-11e8-9000-32729d75a817.jpg)
![svga.io端](https://user-images.githubusercontent.com/11958961/45674946-b6a01880-bb60-11e8-9ca1-bae41037e618.png)
[动画资源](https://github.com/yyued/SVGAPlayer-Android/files/2391846/audio_homepage.svga.zip)

**Comment by PonyCui** [comment]
It's a BUG, we will try to fix it.

**Comment by hzl123456** [comment]
thanks
