### ISSUE TITLE
svga内存飙升

### ISSUE THREAD

**Issue by hzl123456** [svga/SVGAPlayer-Android#85]
把 svga 封装给 react native 调用，第一级页面循环播放一个 svga 动画。当跳转到二级页面的时候（路由框架是 react-navigation），这个时候前一级页面的 svga 的内存会疯狂飙升，最终导致 oom crash掉。

**Comment by PonyCui** [comment]
You may resolve this problem by yourself, find out the OOM reason, if relate to SVGAPlayer, I will fix it.
