### ISSUE TITLE
AE使用插件预览与导出动画不一致

### ISSUE THREAD

**Issue by 1290846731** [svga/SVGAPlayer-Android#86]
多张图片（测试56张）添加位移，非序列帧，生成的动画工具中预览没问题，导出svga文件，查看与预览不一致，缺图片

**Comment by 1290846731** [comment]
对图片做位移做的动画   不是序列帧转的

**Comment by PonyCui** [comment]
Provide sample file, please.

**Comment by 1290846731** [comment]
[svga2.zip](https://github.com/yyued/SVGAPlayer-Android/files/2454558/svga2.zip)


这是导出后的svga文件，AE中预览没问题，导出就少了很多图片
麻烦大佬看一下

**Comment by 1290846731** [comment]
![svga](https://user-images.githubusercontent.com/18045368/46591552-05045f80-caee-11e8-88cf-192982e27e96.jpg)

ae截图

**Comment by GoingAI** [comment]
年初的时候我们也遇到这个问题，位移动画导出后会重影

**Comment by GoingAI** [comment]
@PonyCui 后来换Gif了，不过我试过同样的动画导出为 Lottie 是没有问题的

**Comment by errnull** [comment]
你好，提供的 .svga 文件中发现有 56 和素材，
是如果是 AE 和播放效果差异麻烦提供一下 .aep + 素材压缩包。
这边会尽快比对确认问题。
@1290846731
