### ISSUE TITLE
能否支持在开始播放后再替换 SVGADynamicEntity ？

### ISSUE THREAD

**Issue by Labmem003** [svga/SVGAPlayer-Android#9]
可能开始播放时，有些要替换到动画中的 Bitmap 还没准备好，希望可以先用默认的播，Bitmap准备好了再替换。我准备先修改源码支持这个需求，但是想问下 SVGA 只提供在生成 SVGADrawable 的时候传入动态Bitmap 而没有提供播放时动态设置，是有考虑到什么坑吗？以后会考虑支持吗？

**Comment by PonyCui** [comment]
有计划支持

**Comment by PonyCui** [comment]
实际上是支持的，我测试了一下。
