### ISSUE TITLE
请问您,同样的SVG文件(heartbeat.svga)在demo项目中有声音,移植到自己的项目中没声音,这该怎么解决!

### ISSUE THREAD

**Issue by zhukai123** [svga/SVGAPlayer-Android#91]
## Attention

* Do not ask any usage question, issue board is a issue board, accept library bugs only.
* If you are facing any usage problem, read the README again.

## Issue Template

Issue Description(What's your problem)

How To Reappear(How to reappear the issue)

Any Attachment(Provide a sample about your issue)

------ 中文分割线 ------

## 注意 

* 不要在 Issue 板块提问使用问题，Issue 板块只接受 Bug 反馈。
* 如果遇到使用上的问题，仔细阅读 README。

## Issue 模板

请尽量使用英文提交 Issue

请确切回答：问题的描述、重现方式、附件（提供一个 Demo 以重现问题）

**Comment by zhukai123** [comment]
问题:我在build.gradle文件中:compile 'com.github.yyued:SVGAPlayer-Android:2.1.9'
然后在:xml布局中添加了一个SVGAImageView,source="heartbeat.svga" (是从官方demo拷贝)
默认为GONE,当我把他设置为visible时能正常显示.
目前问题是: 在官方demo使用svga文件能播放声音,但是我的不能播放声音,求解答谢谢!

**Comment by PonyCui** [comment]
请使用 2.3.0
